# syntax=docker/dockerfile:1

FROM arigaio/atlas:1.3.0-alpine AS migrations

COPY migrations /migrations

RUN /atlas migrate hash --dir file:///migrations

FROM arigaio/atlas:1.3.0-alpine

COPY --from=migrations /migrations /migrations

ENTRYPOINT ["/atlas"]
