// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing_settlement.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const applyOCSChargeProjection = `-- name: ApplyOCSChargeProjection :one
UPDATE charges
SET
    status = $1,
    authorized_micros = $2,
    consumed_micros = $3,
    reserved_micros = $4,
    ocs_sequence = $5,
    closed_at = $6,
    updated_at = NOW()
WHERE id = $7
  AND organization_id = $8
  AND wallet_id = $9
  AND ocs_sequence = $10
RETURNING id, organization_id, wallet_id, resource_type, resource_id, charging_mode, currency, idempotency_key, request_hash, pricing_snapshot, status, authorized_micros, consumed_micros, reserved_micros, closed_at, created_at, updated_at, ocs_sequence
`

type ApplyOCSChargeProjectionParams struct {
	ChargeStatus           string             `db:"charge_status" json:"charge_status"`
	AuthorizedMicros       int64              `db:"authorized_micros" json:"authorized_micros"`
	ConsumedMicros         int64              `db:"consumed_micros" json:"consumed_micros"`
	ReservedMicros         int64              `db:"reserved_micros" json:"reserved_micros"`
	ChargeSequence         int64              `db:"charge_sequence" json:"charge_sequence"`
	ClosedAt               pgtype.Timestamptz `db:"closed_at" json:"closed_at"`
	ChargeID               uuid.UUID          `db:"charge_id" json:"charge_id"`
	OrganizationID         uuid.UUID          `db:"organization_id" json:"organization_id"`
	WalletID               uuid.UUID          `db:"wallet_id" json:"wallet_id"`
	PreviousChargeSequence int64              `db:"previous_charge_sequence" json:"previous_charge_sequence"`
}

func (q *Queries) ApplyOCSChargeProjection(ctx context.Context, arg ApplyOCSChargeProjectionParams) (Charge, error) {
	row := q.db.QueryRow(ctx, applyOCSChargeProjection,
		arg.ChargeStatus,
		arg.AuthorizedMicros,
		arg.ConsumedMicros,
		arg.ReservedMicros,
		arg.ChargeSequence,
		arg.ClosedAt,
		arg.ChargeID,
		arg.OrganizationID,
		arg.WalletID,
		arg.PreviousChargeSequence,
	)
	var i Charge
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WalletID,
		&i.ResourceType,
		&i.ResourceID,
		&i.ChargingMode,
		&i.Currency,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.PricingSnapshot,
		&i.Status,
		&i.AuthorizedMicros,
		&i.ConsumedMicros,
		&i.ReservedMicros,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OcsSequence,
	)
	return i, err
}

const applyOCSWalletProjection = `-- name: ApplyOCSWalletProjection :one
UPDATE wallets
SET
    balance_micros = $1,
    reserved_micros = $2,
    ocs_version = $3,
    updated_at = NOW()
WHERE id = $4
  AND organization_id = $5
  AND ocs_version = $6
RETURNING id, organization_id, currency, status, balance_micros, reserved_micros, ocs_version, created_at, updated_at
`

type ApplyOCSWalletProjectionParams struct {
	BalanceAfterMicros    int64     `db:"balance_after_micros" json:"balance_after_micros"`
	ReservedAfterMicros   int64     `db:"reserved_after_micros" json:"reserved_after_micros"`
	WalletVersion         int64     `db:"wallet_version" json:"wallet_version"`
	WalletID              uuid.UUID `db:"wallet_id" json:"wallet_id"`
	OrganizationID        uuid.UUID `db:"organization_id" json:"organization_id"`
	PreviousWalletVersion int64     `db:"previous_wallet_version" json:"previous_wallet_version"`
}

func (q *Queries) ApplyOCSWalletProjection(ctx context.Context, arg ApplyOCSWalletProjectionParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, applyOCSWalletProjection,
		arg.BalanceAfterMicros,
		arg.ReservedAfterMicros,
		arg.WalletVersion,
		arg.WalletID,
		arg.OrganizationID,
		arg.PreviousWalletVersion,
	)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Currency,
		&i.Status,
		&i.BalanceMicros,
		&i.ReservedMicros,
		&i.OcsVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOCSLedgerEntry = `-- name: CreateOCSLedgerEntry :one
INSERT INTO wallet_ledger_entries (
    wallet_event_id,
    wallet_id,
    organization_id,
    charge_id,
    direction,
    reason,
    amount_micros,
    balance_after_micros,
    occurred_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, wallet_event_id, wallet_id, organization_id, charge_id, direction, reason, amount_micros, balance_after_micros, occurred_at, created_at
`

type CreateOCSLedgerEntryParams struct {
	WalletEventID      uuid.UUID          `db:"wallet_event_id" json:"wallet_event_id"`
	WalletID           uuid.UUID          `db:"wallet_id" json:"wallet_id"`
	OrganizationID     uuid.UUID          `db:"organization_id" json:"organization_id"`
	ChargeID           *uuid.UUID         `db:"charge_id" json:"charge_id"`
	Direction          string             `db:"direction" json:"direction"`
	Reason             string             `db:"reason" json:"reason"`
	AmountMicros       int64              `db:"amount_micros" json:"amount_micros"`
	BalanceAfterMicros int64              `db:"balance_after_micros" json:"balance_after_micros"`
	OccurredAt         pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) CreateOCSLedgerEntry(ctx context.Context, arg CreateOCSLedgerEntryParams) (WalletLedgerEntry, error) {
	row := q.db.QueryRow(ctx, createOCSLedgerEntry,
		arg.WalletEventID,
		arg.WalletID,
		arg.OrganizationID,
		arg.ChargeID,
		arg.Direction,
		arg.Reason,
		arg.AmountMicros,
		arg.BalanceAfterMicros,
		arg.OccurredAt,
	)
	var i WalletLedgerEntry
	err := row.Scan(
		&i.ID,
		&i.WalletEventID,
		&i.WalletID,
		&i.OrganizationID,
		&i.ChargeID,
		&i.Direction,
		&i.Reason,
		&i.AmountMicros,
		&i.BalanceAfterMicros,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOCSWalletEvent = `-- name: CreateOCSWalletEvent :one
INSERT INTO wallet_events (
    wallet_id,
    organization_id,
    charge_id,
    operation_id,
    wallet_version,
    charge_sequence,
    event_type,
    balance_delta_micros,
    reserved_delta_micros,
    balance_after_micros,
    reserved_after_micros,
    charge_authorized_after_micros,
    charge_consumed_after_micros,
    charge_reserved_after_micros,
    charge_status,
    occurred_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16
)
RETURNING id, wallet_id, organization_id, charge_id, operation_id, wallet_version, charge_sequence, event_type, balance_delta_micros, reserved_delta_micros, balance_after_micros, reserved_after_micros, occurred_at, created_at, charge_authorized_after_micros, charge_consumed_after_micros, charge_reserved_after_micros, charge_status
`

type CreateOCSWalletEventParams struct {
	WalletID                    uuid.UUID          `db:"wallet_id" json:"wallet_id"`
	OrganizationID              uuid.UUID          `db:"organization_id" json:"organization_id"`
	ChargeID                    *uuid.UUID         `db:"charge_id" json:"charge_id"`
	OperationID                 uuid.UUID          `db:"operation_id" json:"operation_id"`
	WalletVersion               int64              `db:"wallet_version" json:"wallet_version"`
	ChargeSequence              *int64             `db:"charge_sequence" json:"charge_sequence"`
	EventType                   string             `db:"event_type" json:"event_type"`
	BalanceDeltaMicros          int64              `db:"balance_delta_micros" json:"balance_delta_micros"`
	ReservedDeltaMicros         int64              `db:"reserved_delta_micros" json:"reserved_delta_micros"`
	BalanceAfterMicros          int64              `db:"balance_after_micros" json:"balance_after_micros"`
	ReservedAfterMicros         int64              `db:"reserved_after_micros" json:"reserved_after_micros"`
	ChargeAuthorizedAfterMicros *int64             `db:"charge_authorized_after_micros" json:"charge_authorized_after_micros"`
	ChargeConsumedAfterMicros   *int64             `db:"charge_consumed_after_micros" json:"charge_consumed_after_micros"`
	ChargeReservedAfterMicros   *int64             `db:"charge_reserved_after_micros" json:"charge_reserved_after_micros"`
	ChargeStatus                *string            `db:"charge_status" json:"charge_status"`
	OccurredAt                  pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) CreateOCSWalletEvent(ctx context.Context, arg CreateOCSWalletEventParams) (WalletEvent, error) {
	row := q.db.QueryRow(ctx, createOCSWalletEvent,
		arg.WalletID,
		arg.OrganizationID,
		arg.ChargeID,
		arg.OperationID,
		arg.WalletVersion,
		arg.ChargeSequence,
		arg.EventType,
		arg.BalanceDeltaMicros,
		arg.ReservedDeltaMicros,
		arg.BalanceAfterMicros,
		arg.ReservedAfterMicros,
		arg.ChargeAuthorizedAfterMicros,
		arg.ChargeConsumedAfterMicros,
		arg.ChargeReservedAfterMicros,
		arg.ChargeStatus,
		arg.OccurredAt,
	)
	var i WalletEvent
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.OrganizationID,
		&i.ChargeID,
		&i.OperationID,
		&i.WalletVersion,
		&i.ChargeSequence,
		&i.EventType,
		&i.BalanceDeltaMicros,
		&i.ReservedDeltaMicros,
		&i.BalanceAfterMicros,
		&i.ReservedAfterMicros,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.ChargeAuthorizedAfterMicros,
		&i.ChargeConsumedAfterMicros,
		&i.ChargeReservedAfterMicros,
		&i.ChargeStatus,
	)
	return i, err
}

const lockOCSCharge = `-- name: LockOCSCharge :one
SELECT id, organization_id, wallet_id, resource_type, resource_id, charging_mode, currency, idempotency_key, request_hash, pricing_snapshot, status, authorized_micros, consumed_micros, reserved_micros, closed_at, created_at, updated_at, ocs_sequence
FROM charges
WHERE id = $1
  AND organization_id = $2
  AND wallet_id = $3
FOR UPDATE
`

type LockOCSChargeParams struct {
	ChargeID       uuid.UUID `db:"charge_id" json:"charge_id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	WalletID       uuid.UUID `db:"wallet_id" json:"wallet_id"`
}

func (q *Queries) LockOCSCharge(ctx context.Context, arg LockOCSChargeParams) (Charge, error) {
	row := q.db.QueryRow(ctx, lockOCSCharge, arg.ChargeID, arg.OrganizationID, arg.WalletID)
	var i Charge
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WalletID,
		&i.ResourceType,
		&i.ResourceID,
		&i.ChargingMode,
		&i.Currency,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.PricingSnapshot,
		&i.Status,
		&i.AuthorizedMicros,
		&i.ConsumedMicros,
		&i.ReservedMicros,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OcsSequence,
	)
	return i, err
}

const lockOCSOperation = `-- name: LockOCSOperation :exec
SELECT pg_advisory_xact_lock(
    hashtextextended($1::text, 0)
)
`

func (q *Queries) LockOCSOperation(ctx context.Context, operationID string) error {
	_, err := q.db.Exec(ctx, lockOCSOperation, operationID)
	return err
}

const lockOCSWallet = `-- name: LockOCSWallet :one
SELECT id, organization_id, currency, status, balance_micros, reserved_micros, ocs_version, created_at, updated_at
FROM wallets
WHERE id = $1
  AND organization_id = $2
FOR UPDATE
`

type LockOCSWalletParams struct {
	WalletID       uuid.UUID `db:"wallet_id" json:"wallet_id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) LockOCSWallet(ctx context.Context, arg LockOCSWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, lockOCSWallet, arg.WalletID, arg.OrganizationID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Currency,
		&i.Status,
		&i.BalanceMicros,
		&i.ReservedMicros,
		&i.OcsVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
