// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing_wallets.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createBillingWallet = `-- name: CreateBillingWallet :one
INSERT INTO wallets (
    organization_id,
    currency
)
SELECT
    organization.id,
    $1
FROM organizations AS organization
WHERE organization.id = $2
  AND organization.status = 'active'
  AND organization.deleted_at IS NULL
ON CONFLICT (organization_id, currency) DO NOTHING
RETURNING id, organization_id, currency, status, balance_micros, reserved_micros, ocs_version, created_at, updated_at
`

type CreateBillingWalletParams struct {
	Currency       string    `db:"currency" json:"currency"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) CreateBillingWallet(ctx context.Context, arg CreateBillingWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createBillingWallet, arg.Currency, arg.OrganizationID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Currency,
		&i.Status,
		&i.BalanceMicros,
		&i.ReservedMicros,
		&i.OcsVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillingWallet = `-- name: GetBillingWallet :one
SELECT wallet.id, wallet.organization_id, wallet.currency, wallet.status, wallet.balance_micros, wallet.reserved_micros, wallet.ocs_version, wallet.created_at, wallet.updated_at
FROM wallets AS wallet
JOIN organizations AS organization
  ON organization.id = wallet.organization_id
WHERE wallet.organization_id = $1
  AND wallet.currency = $2
  AND organization.status = 'active'
  AND organization.deleted_at IS NULL
LIMIT 1
`

type GetBillingWalletParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	Currency       string    `db:"currency" json:"currency"`
}

func (q *Queries) GetBillingWallet(ctx context.Context, arg GetBillingWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, getBillingWallet, arg.OrganizationID, arg.Currency)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Currency,
		&i.Status,
		&i.BalanceMicros,
		&i.ReservedMicros,
		&i.OcsVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillingWalletByID = `-- name: GetBillingWalletByID :one
SELECT wallet.id, wallet.organization_id, wallet.currency, wallet.status, wallet.balance_micros, wallet.reserved_micros, wallet.ocs_version, wallet.created_at, wallet.updated_at
FROM wallets AS wallet
JOIN organizations AS organization
  ON organization.id = wallet.organization_id
WHERE wallet.id = $1
  AND wallet.organization_id = $2
  AND organization.status = 'active'
  AND organization.deleted_at IS NULL
LIMIT 1
`

type GetBillingWalletByIDParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetBillingWalletByID(ctx context.Context, arg GetBillingWalletByIDParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, getBillingWalletByID, arg.ID, arg.OrganizationID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Currency,
		&i.Status,
		&i.BalanceMicros,
		&i.ReservedMicros,
		&i.OcsVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletEventByOperationID = `-- name: GetWalletEventByOperationID :one
SELECT id, wallet_id, organization_id, charge_id, operation_id, wallet_version, charge_sequence, event_type, balance_delta_micros, reserved_delta_micros, balance_after_micros, reserved_after_micros, occurred_at, created_at, charge_authorized_after_micros, charge_consumed_after_micros, charge_reserved_after_micros, charge_status
FROM wallet_events
WHERE operation_id = $1
LIMIT 1
`

func (q *Queries) GetWalletEventByOperationID(ctx context.Context, operationID uuid.UUID) (WalletEvent, error) {
	row := q.db.QueryRow(ctx, getWalletEventByOperationID, operationID)
	var i WalletEvent
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.OrganizationID,
		&i.ChargeID,
		&i.OperationID,
		&i.WalletVersion,
		&i.ChargeSequence,
		&i.EventType,
		&i.BalanceDeltaMicros,
		&i.ReservedDeltaMicros,
		&i.BalanceAfterMicros,
		&i.ReservedAfterMicros,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.ChargeAuthorizedAfterMicros,
		&i.ChargeConsumedAfterMicros,
		&i.ChargeReservedAfterMicros,
		&i.ChargeStatus,
	)
	return i, err
}

const listBillingWallets = `-- name: ListBillingWallets :many
SELECT wallet.id, wallet.organization_id, wallet.currency, wallet.status, wallet.balance_micros, wallet.reserved_micros, wallet.ocs_version, wallet.created_at, wallet.updated_at
FROM wallets AS wallet
JOIN organizations AS organization
  ON organization.id = wallet.organization_id
WHERE wallet.organization_id = $1
  AND organization.status = 'active'
  AND organization.deleted_at IS NULL
ORDER BY wallet.created_at DESC
`

func (q *Queries) ListBillingWallets(ctx context.Context, organizationID uuid.UUID) ([]Wallet, error) {
	rows, err := q.db.Query(ctx, listBillingWallets, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Wallet{}
	for rows.Next() {
		var i Wallet
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Currency,
			&i.Status,
			&i.BalanceMicros,
			&i.ReservedMicros,
			&i.OcsVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChargeWalletEvents = `-- name: ListChargeWalletEvents :many
SELECT event.id, event.wallet_id, event.organization_id, event.charge_id, event.operation_id, event.wallet_version, event.charge_sequence, event.event_type, event.balance_delta_micros, event.reserved_delta_micros, event.balance_after_micros, event.reserved_after_micros, event.occurred_at, event.created_at, event.charge_authorized_after_micros, event.charge_consumed_after_micros, event.charge_reserved_after_micros, event.charge_status
FROM wallet_events AS event
JOIN charges AS charge
  ON charge.id = event.charge_id
 AND charge.organization_id = event.organization_id
WHERE event.organization_id = $1
  AND event.charge_id = $2
ORDER BY event.charge_sequence ASC
`

type ListChargeWalletEventsParams struct {
	OrganizationID uuid.UUID  `db:"organization_id" json:"organization_id"`
	ChargeID       *uuid.UUID `db:"charge_id" json:"charge_id"`
}

func (q *Queries) ListChargeWalletEvents(ctx context.Context, arg ListChargeWalletEventsParams) ([]WalletEvent, error) {
	rows, err := q.db.Query(ctx, listChargeWalletEvents, arg.OrganizationID, arg.ChargeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WalletEvent{}
	for rows.Next() {
		var i WalletEvent
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.OrganizationID,
			&i.ChargeID,
			&i.OperationID,
			&i.WalletVersion,
			&i.ChargeSequence,
			&i.EventType,
			&i.BalanceDeltaMicros,
			&i.ReservedDeltaMicros,
			&i.BalanceAfterMicros,
			&i.ReservedAfterMicros,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.ChargeAuthorizedAfterMicros,
			&i.ChargeConsumedAfterMicros,
			&i.ChargeReservedAfterMicros,
			&i.ChargeStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletEvents = `-- name: ListWalletEvents :many
SELECT id, wallet_id, organization_id, charge_id, operation_id, wallet_version, charge_sequence, event_type, balance_delta_micros, reserved_delta_micros, balance_after_micros, reserved_after_micros, occurred_at, created_at, charge_authorized_after_micros, charge_consumed_after_micros, charge_reserved_after_micros, charge_status
FROM wallet_events
WHERE wallet_id = $1
  AND organization_id = $2
ORDER BY wallet_version DESC
LIMIT $3
`

type ListWalletEventsParams struct {
	WalletID       uuid.UUID `db:"wallet_id" json:"wallet_id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	PageLimit      int32     `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListWalletEvents(ctx context.Context, arg ListWalletEventsParams) ([]WalletEvent, error) {
	rows, err := q.db.Query(ctx, listWalletEvents, arg.WalletID, arg.OrganizationID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WalletEvent{}
	for rows.Next() {
		var i WalletEvent
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.OrganizationID,
			&i.ChargeID,
			&i.OperationID,
			&i.WalletVersion,
			&i.ChargeSequence,
			&i.EventType,
			&i.BalanceDeltaMicros,
			&i.ReservedDeltaMicros,
			&i.BalanceAfterMicros,
			&i.ReservedAfterMicros,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.ChargeAuthorizedAfterMicros,
			&i.ChargeConsumedAfterMicros,
			&i.ChargeReservedAfterMicros,
			&i.ChargeStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBillingWalletStatus = `-- name: SetBillingWalletStatus :one
UPDATE wallets AS wallet
SET
    status = $1,
    updated_at = NOW()
FROM organizations AS organization
WHERE wallet.id = $2
  AND wallet.organization_id = $3
  AND organization.id = wallet.organization_id
  AND organization.status = 'active'
  AND organization.deleted_at IS NULL
RETURNING wallet.id, wallet.organization_id, wallet.currency, wallet.status, wallet.balance_micros, wallet.reserved_micros, wallet.ocs_version, wallet.created_at, wallet.updated_at
`

type SetBillingWalletStatusParams struct {
	Status         string    `db:"status" json:"status"`
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) SetBillingWalletStatus(ctx context.Context, arg SetBillingWalletStatusParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, setBillingWalletStatus, arg.Status, arg.ID, arg.OrganizationID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Currency,
		&i.Status,
		&i.BalanceMicros,
		&i.ReservedMicros,
		&i.OcsVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
