// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing_charges.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createBillingCharge = `-- name: CreateBillingCharge :one
INSERT INTO charges (
    organization_id,
    wallet_id,
    resource_type,
    resource_id,
    charging_mode,
    currency,
    idempotency_key,
    request_hash,
    pricing_snapshot
)
SELECT
    organization.id,
    wallet.id,
    $1,
    $2,
    $3,
    wallet.currency,
    $4,
    $5,
    $6::jsonb
FROM organizations AS organization
JOIN wallets AS wallet
  ON wallet.id = $7
 AND wallet.organization_id = organization.id
WHERE organization.id = $8
  AND organization.status = 'active'
  AND organization.deleted_at IS NULL
  AND wallet.status = 'active'
  AND wallet.currency = $9
ON CONFLICT (organization_id, idempotency_key) DO NOTHING
RETURNING id, organization_id, wallet_id, resource_type, resource_id, charging_mode, currency, idempotency_key, request_hash, pricing_snapshot, status, authorized_micros, consumed_micros, reserved_micros, closed_at, created_at, updated_at
`

type CreateBillingChargeParams struct {
	ResourceType    string    `db:"resource_type" json:"resource_type"`
	ResourceID      uuid.UUID `db:"resource_id" json:"resource_id"`
	ChargingMode    string    `db:"charging_mode" json:"charging_mode"`
	IdempotencyKey  string    `db:"idempotency_key" json:"idempotency_key"`
	RequestHash     string    `db:"request_hash" json:"request_hash"`
	PricingSnapshot []byte    `db:"pricing_snapshot" json:"pricing_snapshot"`
	WalletID        uuid.UUID `db:"wallet_id" json:"wallet_id"`
	OrganizationID  uuid.UUID `db:"organization_id" json:"organization_id"`
	Currency        string    `db:"currency" json:"currency"`
}

func (q *Queries) CreateBillingCharge(ctx context.Context, arg CreateBillingChargeParams) (Charge, error) {
	row := q.db.QueryRow(ctx, createBillingCharge,
		arg.ResourceType,
		arg.ResourceID,
		arg.ChargingMode,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.PricingSnapshot,
		arg.WalletID,
		arg.OrganizationID,
		arg.Currency,
	)
	var i Charge
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WalletID,
		&i.ResourceType,
		&i.ResourceID,
		&i.ChargingMode,
		&i.Currency,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.PricingSnapshot,
		&i.Status,
		&i.AuthorizedMicros,
		&i.ConsumedMicros,
		&i.ReservedMicros,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillingCharge = `-- name: GetBillingCharge :one
SELECT id, organization_id, wallet_id, resource_type, resource_id, charging_mode, currency, idempotency_key, request_hash, pricing_snapshot, status, authorized_micros, consumed_micros, reserved_micros, closed_at, created_at, updated_at
FROM charges
WHERE id = $1
  AND organization_id = $2
LIMIT 1
`

type GetBillingChargeParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetBillingCharge(ctx context.Context, arg GetBillingChargeParams) (Charge, error) {
	row := q.db.QueryRow(ctx, getBillingCharge, arg.ID, arg.OrganizationID)
	var i Charge
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WalletID,
		&i.ResourceType,
		&i.ResourceID,
		&i.ChargingMode,
		&i.Currency,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.PricingSnapshot,
		&i.Status,
		&i.AuthorizedMicros,
		&i.ConsumedMicros,
		&i.ReservedMicros,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillingChargeByIdempotencyKey = `-- name: GetBillingChargeByIdempotencyKey :one
SELECT id, organization_id, wallet_id, resource_type, resource_id, charging_mode, currency, idempotency_key, request_hash, pricing_snapshot, status, authorized_micros, consumed_micros, reserved_micros, closed_at, created_at, updated_at
FROM charges
WHERE organization_id = $1
  AND idempotency_key = $2
LIMIT 1
`

type GetBillingChargeByIdempotencyKeyParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	IdempotencyKey string    `db:"idempotency_key" json:"idempotency_key"`
}

func (q *Queries) GetBillingChargeByIdempotencyKey(ctx context.Context, arg GetBillingChargeByIdempotencyKeyParams) (Charge, error) {
	row := q.db.QueryRow(ctx, getBillingChargeByIdempotencyKey, arg.OrganizationID, arg.IdempotencyKey)
	var i Charge
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WalletID,
		&i.ResourceType,
		&i.ResourceID,
		&i.ChargingMode,
		&i.Currency,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.PricingSnapshot,
		&i.Status,
		&i.AuthorizedMicros,
		&i.ConsumedMicros,
		&i.ReservedMicros,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillingChargeByResource = `-- name: GetBillingChargeByResource :one
SELECT id, organization_id, wallet_id, resource_type, resource_id, charging_mode, currency, idempotency_key, request_hash, pricing_snapshot, status, authorized_micros, consumed_micros, reserved_micros, closed_at, created_at, updated_at
FROM charges
WHERE organization_id = $1
  AND resource_type = $2
  AND resource_id = $3
LIMIT 1
`

type GetBillingChargeByResourceParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ResourceType   string    `db:"resource_type" json:"resource_type"`
	ResourceID     uuid.UUID `db:"resource_id" json:"resource_id"`
}

func (q *Queries) GetBillingChargeByResource(ctx context.Context, arg GetBillingChargeByResourceParams) (Charge, error) {
	row := q.db.QueryRow(ctx, getBillingChargeByResource, arg.OrganizationID, arg.ResourceType, arg.ResourceID)
	var i Charge
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WalletID,
		&i.ResourceType,
		&i.ResourceID,
		&i.ChargingMode,
		&i.Currency,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.PricingSnapshot,
		&i.Status,
		&i.AuthorizedMicros,
		&i.ConsumedMicros,
		&i.ReservedMicros,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBillingCharges = `-- name: ListBillingCharges :many
SELECT id, organization_id, wallet_id, resource_type, resource_id, charging_mode, currency, idempotency_key, request_hash, pricing_snapshot, status, authorized_micros, consumed_micros, reserved_micros, closed_at, created_at, updated_at
FROM charges
WHERE organization_id = $1
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY created_at DESC
LIMIT $4
OFFSET $3
`

type ListBillingChargesParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	Status         *string   `db:"status" json:"status"`
	PageOffset     int32     `db:"page_offset" json:"page_offset"`
	PageLimit      int32     `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListBillingCharges(ctx context.Context, arg ListBillingChargesParams) ([]Charge, error) {
	rows, err := q.db.Query(ctx, listBillingCharges,
		arg.OrganizationID,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Charge{}
	for rows.Next() {
		var i Charge
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.WalletID,
			&i.ResourceType,
			&i.ResourceID,
			&i.ChargingMode,
			&i.Currency,
			&i.IdempotencyKey,
			&i.RequestHash,
			&i.PricingSnapshot,
			&i.Status,
			&i.AuthorizedMicros,
			&i.ConsumedMicros,
			&i.ReservedMicros,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
