// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: carrier_rates.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCarrierRate = `-- name: CreateCarrierRate :one
INSERT INTO carrier_rates (
    organization_id,
    destination_prefix,
    direction,
    currency,
    rate_micros,
    effective_at,
    expires_at
)
SELECT
    $1::UUID,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
WHERE $1::UUID IS NULL
   OR EXISTS (
       SELECT 1
       FROM organizations AS o
       WHERE o.id = $1::UUID
         AND o.status = 'active'
         AND o.deleted_at IS NULL
   )
RETURNING id, organization_id, destination_prefix, direction, currency, rate_micros, effective_at, expires_at, created_at
`

type CreateCarrierRateParams struct {
	OrganizationID    *uuid.UUID         `db:"organization_id" json:"organization_id"`
	DestinationPrefix string             `db:"destination_prefix" json:"destination_prefix"`
	Direction         string             `db:"direction" json:"direction"`
	Currency          string             `db:"currency" json:"currency"`
	RateMicros        int64              `db:"rate_micros" json:"rate_micros"`
	EffectiveAt       pgtype.Timestamptz `db:"effective_at" json:"effective_at"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateCarrierRate(ctx context.Context, arg CreateCarrierRateParams) (CarrierRate, error) {
	row := q.db.QueryRow(ctx, createCarrierRate,
		arg.OrganizationID,
		arg.DestinationPrefix,
		arg.Direction,
		arg.Currency,
		arg.RateMicros,
		arg.EffectiveAt,
		arg.ExpiresAt,
	)
	var i CarrierRate
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DestinationPrefix,
		&i.Direction,
		&i.Currency,
		&i.RateMicros,
		&i.EffectiveAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCarrierRateByID = `-- name: GetCarrierRateByID :one
SELECT id, organization_id, destination_prefix, direction, currency, rate_micros, effective_at, expires_at, created_at
FROM carrier_rates
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCarrierRateByID(ctx context.Context, id uuid.UUID) (CarrierRate, error) {
	row := q.db.QueryRow(ctx, getCarrierRateByID, id)
	var i CarrierRate
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DestinationPrefix,
		&i.Direction,
		&i.Currency,
		&i.RateMicros,
		&i.EffectiveAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const resolveCarrierRate = `-- name: ResolveCarrierRate :one
SELECT cr.id, cr.organization_id, cr.destination_prefix, cr.direction, cr.currency, cr.rate_micros, cr.effective_at, cr.expires_at, cr.created_at
FROM carrier_rates AS cr
JOIN organizations AS o
  ON o.id = $1
 AND o.status = 'active'
 AND o.deleted_at IS NULL
WHERE (cr.organization_id = o.id OR cr.organization_id IS NULL)
  AND cr.direction = $2
  AND cr.currency = $3
  AND $4::TEXT LIKE cr.destination_prefix || '%'
  AND cr.effective_at <= $5
  AND (cr.expires_at IS NULL OR cr.expires_at > $5)
ORDER BY
    (cr.organization_id IS NOT NULL) DESC,
    length(cr.destination_prefix) DESC,
    cr.effective_at DESC
LIMIT 1
`

type ResolveCarrierRateParams struct {
	OrganizationID    uuid.UUID          `db:"organization_id" json:"organization_id"`
	Direction         string             `db:"direction" json:"direction"`
	Currency          string             `db:"currency" json:"currency"`
	DestinationDigits string             `db:"destination_digits" json:"destination_digits"`
	ResolvedAt        pgtype.Timestamptz `db:"resolved_at" json:"resolved_at"`
}

func (q *Queries) ResolveCarrierRate(ctx context.Context, arg ResolveCarrierRateParams) (CarrierRate, error) {
	row := q.db.QueryRow(ctx, resolveCarrierRate,
		arg.OrganizationID,
		arg.Direction,
		arg.Currency,
		arg.DestinationDigits,
		arg.ResolvedAt,
	)
	var i CarrierRate
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DestinationPrefix,
		&i.Direction,
		&i.Currency,
		&i.RateMicros,
		&i.EffectiveAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
