// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkouts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeCheckout = `-- name: CompleteCheckout :one
UPDATE checkouts AS c
SET
    status = 'succeeded',
    next_action = 'none',
    provider_message = NULL,
    completed_at = $1
WHERE c.id = $2
  AND c.organization_id = $3
  AND c.status = 'processing'
RETURNING c.id, c.organization_id, c.purpose, c.subscription_id, c.reference, c.amount_micros, c.currency, c.status, c.provider, c.payment_method, c.next_action, c.provider_message, c.expires_at, c.failure_code, c.completed_at, c.created_at, c.updated_at
`

type CompleteCheckoutParams struct {
	CompletedAt    pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CheckoutID     uuid.UUID          `db:"checkout_id" json:"checkout_id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
}

func (q *Queries) CompleteCheckout(ctx context.Context, arg CompleteCheckoutParams) (Checkout, error) {
	row := q.db.QueryRow(ctx, completeCheckout, arg.CompletedAt, arg.CheckoutID, arg.OrganizationID)
	var i Checkout
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Purpose,
		&i.SubscriptionID,
		&i.Reference,
		&i.AmountMicros,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.PaymentMethod,
		&i.NextAction,
		&i.ProviderMessage,
		&i.ExpiresAt,
		&i.FailureCode,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const confirmCheckout = `-- name: ConfirmCheckout :one
UPDATE checkouts AS c
SET
    status = 'processing',
    provider = $1,
    payment_method = $2,
    next_action = 'wait'
WHERE c.id = $3
  AND c.organization_id = $4
  AND c.status = 'pending'
  AND c.expires_at > $5
RETURNING c.id, c.organization_id, c.purpose, c.subscription_id, c.reference, c.amount_micros, c.currency, c.status, c.provider, c.payment_method, c.next_action, c.provider_message, c.expires_at, c.failure_code, c.completed_at, c.created_at, c.updated_at
`

type ConfirmCheckoutParams struct {
	Provider       *string            `db:"provider" json:"provider"`
	PaymentMethod  *string            `db:"payment_method" json:"payment_method"`
	CheckoutID     uuid.UUID          `db:"checkout_id" json:"checkout_id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	NowAt          pgtype.Timestamptz `db:"now_at" json:"now_at"`
}

func (q *Queries) ConfirmCheckout(ctx context.Context, arg ConfirmCheckoutParams) (Checkout, error) {
	row := q.db.QueryRow(ctx, confirmCheckout,
		arg.Provider,
		arg.PaymentMethod,
		arg.CheckoutID,
		arg.OrganizationID,
		arg.NowAt,
	)
	var i Checkout
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Purpose,
		&i.SubscriptionID,
		&i.Reference,
		&i.AmountMicros,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.PaymentMethod,
		&i.NextAction,
		&i.ProviderMessage,
		&i.ExpiresAt,
		&i.FailureCode,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCheckout = `-- name: CreateCheckout :one
INSERT INTO checkouts (
    organization_id,
    purpose,
    subscription_id,
    reference,
    amount_micros,
    currency,
    expires_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, organization_id, purpose, subscription_id, reference, amount_micros, currency, status, provider, payment_method, next_action, provider_message, expires_at, failure_code, completed_at, created_at, updated_at
`

type CreateCheckoutParams struct {
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	Purpose        string             `db:"purpose" json:"purpose"`
	SubscriptionID *uuid.UUID         `db:"subscription_id" json:"subscription_id"`
	Reference      string             `db:"reference" json:"reference"`
	AmountMicros   int64              `db:"amount_micros" json:"amount_micros"`
	Currency       string             `db:"currency" json:"currency"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateCheckout(ctx context.Context, arg CreateCheckoutParams) (Checkout, error) {
	row := q.db.QueryRow(ctx, createCheckout,
		arg.OrganizationID,
		arg.Purpose,
		arg.SubscriptionID,
		arg.Reference,
		arg.AmountMicros,
		arg.Currency,
		arg.ExpiresAt,
	)
	var i Checkout
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Purpose,
		&i.SubscriptionID,
		&i.Reference,
		&i.AmountMicros,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.PaymentMethod,
		&i.NextAction,
		&i.ProviderMessage,
		&i.ExpiresAt,
		&i.FailureCode,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireCheckout = `-- name: ExpireCheckout :one
UPDATE checkouts AS c
SET
    status = 'expired',
    next_action = 'none',
    completed_at = $1
WHERE c.id = $2
  AND c.organization_id = $3
  AND c.status IN ('pending', 'processing')
  AND c.expires_at <= $1
RETURNING c.id, c.organization_id, c.purpose, c.subscription_id, c.reference, c.amount_micros, c.currency, c.status, c.provider, c.payment_method, c.next_action, c.provider_message, c.expires_at, c.failure_code, c.completed_at, c.created_at, c.updated_at
`

type ExpireCheckoutParams struct {
	CompletedAt    pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CheckoutID     uuid.UUID          `db:"checkout_id" json:"checkout_id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
}

func (q *Queries) ExpireCheckout(ctx context.Context, arg ExpireCheckoutParams) (Checkout, error) {
	row := q.db.QueryRow(ctx, expireCheckout, arg.CompletedAt, arg.CheckoutID, arg.OrganizationID)
	var i Checkout
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Purpose,
		&i.SubscriptionID,
		&i.Reference,
		&i.AmountMicros,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.PaymentMethod,
		&i.NextAction,
		&i.ProviderMessage,
		&i.ExpiresAt,
		&i.FailureCode,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireDueCheckouts = `-- name: ExpireDueCheckouts :execrows
WITH due AS (
    SELECT id
    FROM checkouts
    WHERE status IN ('pending', 'processing')
      AND expires_at <= $1
    ORDER BY expires_at, id
    FOR UPDATE SKIP LOCKED
    LIMIT $2
)
UPDATE checkouts AS c
SET
    status = 'expired',
    next_action = 'none',
    provider_message = NULL,
    completed_at = $1
FROM due
WHERE c.id = due.id
`

type ExpireDueCheckoutsParams struct {
	CompletedAt pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	LimitCount  int32              `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ExpireDueCheckouts(ctx context.Context, arg ExpireDueCheckoutsParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireDueCheckouts, arg.CompletedAt, arg.LimitCount)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failCheckout = `-- name: FailCheckout :one
UPDATE checkouts AS c
SET
    status = 'failed',
    next_action = 'none',
    provider_message = $1,
    failure_code = $2,
    completed_at = $3
WHERE c.id = $4
  AND c.organization_id = $5
  AND c.status = 'processing'
RETURNING c.id, c.organization_id, c.purpose, c.subscription_id, c.reference, c.amount_micros, c.currency, c.status, c.provider, c.payment_method, c.next_action, c.provider_message, c.expires_at, c.failure_code, c.completed_at, c.created_at, c.updated_at
`

type FailCheckoutParams struct {
	ProviderMessage *string            `db:"provider_message" json:"provider_message"`
	FailureCode     *string            `db:"failure_code" json:"failure_code"`
	CompletedAt     pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CheckoutID      uuid.UUID          `db:"checkout_id" json:"checkout_id"`
	OrganizationID  uuid.UUID          `db:"organization_id" json:"organization_id"`
}

func (q *Queries) FailCheckout(ctx context.Context, arg FailCheckoutParams) (Checkout, error) {
	row := q.db.QueryRow(ctx, failCheckout,
		arg.ProviderMessage,
		arg.FailureCode,
		arg.CompletedAt,
		arg.CheckoutID,
		arg.OrganizationID,
	)
	var i Checkout
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Purpose,
		&i.SubscriptionID,
		&i.Reference,
		&i.AmountMicros,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.PaymentMethod,
		&i.NextAction,
		&i.ProviderMessage,
		&i.ExpiresAt,
		&i.FailureCode,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCheckoutByID = `-- name: GetCheckoutByID :one
SELECT id, organization_id, purpose, subscription_id, reference, amount_micros, currency, status, provider, payment_method, next_action, provider_message, expires_at, failure_code, completed_at, created_at, updated_at
FROM checkouts
WHERE id = $1
  AND organization_id = $2
LIMIT 1
`

type GetCheckoutByIDParams struct {
	CheckoutID     uuid.UUID `db:"checkout_id" json:"checkout_id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetCheckoutByID(ctx context.Context, arg GetCheckoutByIDParams) (Checkout, error) {
	row := q.db.QueryRow(ctx, getCheckoutByID, arg.CheckoutID, arg.OrganizationID)
	var i Checkout
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Purpose,
		&i.SubscriptionID,
		&i.Reference,
		&i.AmountMicros,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.PaymentMethod,
		&i.NextAction,
		&i.ProviderMessage,
		&i.ExpiresAt,
		&i.FailureCode,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCheckoutForContinuation = `-- name: GetCheckoutForContinuation :one
SELECT c.id, c.organization_id, c.purpose, c.subscription_id, c.reference, c.amount_micros, c.currency, c.status, c.provider, c.payment_method, c.next_action, c.provider_message, c.expires_at, c.failure_code, c.completed_at, c.created_at, c.updated_at
FROM checkouts AS c
WHERE c.id = $1
  AND c.organization_id = $2
  AND c.status = 'processing'
  AND c.expires_at > $3
LIMIT 1
`

type GetCheckoutForContinuationParams struct {
	CheckoutID     uuid.UUID          `db:"checkout_id" json:"checkout_id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	NowAt          pgtype.Timestamptz `db:"now_at" json:"now_at"`
}

func (q *Queries) GetCheckoutForContinuation(ctx context.Context, arg GetCheckoutForContinuationParams) (Checkout, error) {
	row := q.db.QueryRow(ctx, getCheckoutForContinuation, arg.CheckoutID, arg.OrganizationID, arg.NowAt)
	var i Checkout
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Purpose,
		&i.SubscriptionID,
		&i.Reference,
		&i.AmountMicros,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.PaymentMethod,
		&i.NextAction,
		&i.ProviderMessage,
		&i.ExpiresAt,
		&i.FailureCode,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCheckoutAction = `-- name: UpdateCheckoutAction :one
UPDATE checkouts AS c
SET
    next_action = $1,
    provider_message = $2
WHERE c.id = $3
  AND c.organization_id = $4
  AND c.status = 'processing'
RETURNING c.id, c.organization_id, c.purpose, c.subscription_id, c.reference, c.amount_micros, c.currency, c.status, c.provider, c.payment_method, c.next_action, c.provider_message, c.expires_at, c.failure_code, c.completed_at, c.created_at, c.updated_at
`

type UpdateCheckoutActionParams struct {
	NextAction      string    `db:"next_action" json:"next_action"`
	ProviderMessage *string   `db:"provider_message" json:"provider_message"`
	CheckoutID      uuid.UUID `db:"checkout_id" json:"checkout_id"`
	OrganizationID  uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) UpdateCheckoutAction(ctx context.Context, arg UpdateCheckoutActionParams) (Checkout, error) {
	row := q.db.QueryRow(ctx, updateCheckoutAction,
		arg.NextAction,
		arg.ProviderMessage,
		arg.CheckoutID,
		arg.OrganizationID,
	)
	var i Checkout
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Purpose,
		&i.SubscriptionID,
		&i.Reference,
		&i.AmountMicros,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.PaymentMethod,
		&i.NextAction,
		&i.ProviderMessage,
		&i.ExpiresAt,
		&i.FailureCode,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
