// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkouts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelWalletCheckout = `-- name: CancelWalletCheckout :one
UPDATE checkouts AS c
SET status = 'canceled'
WHERE c.id = $1::UUID
  AND c.status = 'pending'
  AND NOT EXISTS (
      SELECT 1 FROM payments AS p
      WHERE p.checkout_id = c.id
        AND p.status IN ('created', 'pending', 'succeeded')
  )
RETURNING c.id, c.wallet_id, c.amount_minor, c.currency, c.idempotency_key, c.request_hash, c.status, c.credited_transaction_id, c.expires_at, c.completed_at, c.created_at, c.updated_at
`

// A checkout cannot be canceled while a payment may still settle. Such
// attempts must be resolved or canceled at the provider first.
func (q *Queries) CancelWalletCheckout(ctx context.Context, id uuid.UUID) (Checkout, error) {
	row := q.db.QueryRow(ctx, cancelWalletCheckout, id)
	var i Checkout
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.AmountMinor,
		&i.Currency,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.CreditedTransactionID,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeWalletCheckout = `-- name: CompleteWalletCheckout :one
UPDATE checkouts SET status = 'completed',
    credited_transaction_id = $1::UUID,
    completed_at = now()
WHERE id = $2::UUID AND status = 'pending'
RETURNING id, wallet_id, amount_minor, currency, idempotency_key, request_hash, status, credited_transaction_id, expires_at, completed_at, created_at, updated_at
`

type CompleteWalletCheckoutParams struct {
	CreditedTransactionID uuid.UUID `db:"credited_transaction_id" json:"credited_transaction_id"`
	ID                    uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) CompleteWalletCheckout(ctx context.Context, arg CompleteWalletCheckoutParams) (Checkout, error) {
	row := q.db.QueryRow(ctx, completeWalletCheckout, arg.CreditedTransactionID, arg.ID)
	var i Checkout
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.AmountMinor,
		&i.Currency,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.CreditedTransactionID,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWalletCheckout = `-- name: CreateWalletCheckout :one
INSERT INTO checkouts (wallet_id, amount_minor, currency, idempotency_key, request_hash, expires_at)
SELECT w.id, $1::BIGINT, w.currency,
       $2::TEXT, $3::TEXT,
       $4::TIMESTAMPTZ
FROM wallets AS w
JOIN organizations AS o ON o.id = w.organization_id
WHERE w.id = $5::UUID
  AND w.organization_id = $6::UUID
  AND w.currency = $7::TEXT
  AND o.status = 'active' AND o.deleted_at IS NULL
  AND $4::TIMESTAMPTZ > now()
ON CONFLICT (wallet_id, idempotency_key) DO NOTHING
RETURNING id, wallet_id, amount_minor, currency, idempotency_key, request_hash, status, credited_transaction_id, expires_at, completed_at, created_at, updated_at
`

type CreateWalletCheckoutParams struct {
	AmountMinor    int64              `db:"amount_minor" json:"amount_minor"`
	IdempotencyKey string             `db:"idempotency_key" json:"idempotency_key"`
	RequestHash    string             `db:"request_hash" json:"request_hash"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	WalletID       uuid.UUID          `db:"wallet_id" json:"wallet_id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	Currency       string             `db:"currency" json:"currency"`
}

func (q *Queries) CreateWalletCheckout(ctx context.Context, arg CreateWalletCheckoutParams) (Checkout, error) {
	row := q.db.QueryRow(ctx, createWalletCheckout,
		arg.AmountMinor,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.ExpiresAt,
		arg.WalletID,
		arg.OrganizationID,
		arg.Currency,
	)
	var i Checkout
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.AmountMinor,
		&i.Currency,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.CreditedTransactionID,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletCheckout = `-- name: GetWalletCheckout :one
SELECT c.id, c.wallet_id, c.amount_minor, c.currency, c.idempotency_key, c.request_hash, c.status, c.credited_transaction_id, c.expires_at, c.completed_at, c.created_at, c.updated_at FROM checkouts AS c
JOIN wallets AS w ON w.id = c.wallet_id
WHERE w.organization_id = $1::UUID
  AND c.id = $2::UUID LIMIT 1
`

type GetWalletCheckoutParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetWalletCheckout(ctx context.Context, arg GetWalletCheckoutParams) (Checkout, error) {
	row := q.db.QueryRow(ctx, getWalletCheckout, arg.OrganizationID, arg.ID)
	var i Checkout
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.AmountMinor,
		&i.Currency,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.CreditedTransactionID,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletCheckoutByKey = `-- name: GetWalletCheckoutByKey :one
SELECT c.id, c.wallet_id, c.amount_minor, c.currency, c.idempotency_key, c.request_hash, c.status, c.credited_transaction_id, c.expires_at, c.completed_at, c.created_at, c.updated_at FROM checkouts AS c
JOIN wallets AS w ON w.id = c.wallet_id
WHERE w.organization_id = $1::UUID
  AND c.wallet_id = $2::UUID
  AND c.idempotency_key = $3::TEXT LIMIT 1
`

type GetWalletCheckoutByKeyParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	WalletID       uuid.UUID `db:"wallet_id" json:"wallet_id"`
	IdempotencyKey string    `db:"idempotency_key" json:"idempotency_key"`
}

func (q *Queries) GetWalletCheckoutByKey(ctx context.Context, arg GetWalletCheckoutByKeyParams) (Checkout, error) {
	row := q.db.QueryRow(ctx, getWalletCheckoutByKey, arg.OrganizationID, arg.WalletID, arg.IdempotencyKey)
	var i Checkout
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.AmountMinor,
		&i.Currency,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.CreditedTransactionID,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockWalletCheckout = `-- name: LockWalletCheckout :one
SELECT id, wallet_id, amount_minor, currency, idempotency_key, request_hash, status, credited_transaction_id, expires_at, completed_at, created_at, updated_at FROM checkouts WHERE id = $1::UUID FOR UPDATE
`

func (q *Queries) LockWalletCheckout(ctx context.Context, id uuid.UUID) (Checkout, error) {
	row := q.db.QueryRow(ctx, lockWalletCheckout, id)
	var i Checkout
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.AmountMinor,
		&i.Currency,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.CreditedTransactionID,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
