// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: managed_number_orders.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimManagedNumberPurchaseSubmission = `-- name: ClaimManagedNumberPurchaseSubmission :one
UPDATE managed_number_orders
SET status = 'submitting',
    submitted_at = now()
WHERE organization_id = $1
  AND id = $2
  AND status = 'ready'
  AND wallet_reservation_id IS NOT NULL
  AND quote_expires_at > now()
RETURNING id, organization_id, provider_id, phone_number_id, idempotency_key, request_hash, number, country_code, available_did_id, sku_id, quote_id, purchase_amount_minor, recurring_amount_minor, currency, quote_expires_at, wallet_reservation_id, provider_order_id, provider_did_id, status, submitted_at, error_code, error_message, created_at, updated_at
`

type ClaimManagedNumberPurchaseSubmissionParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

// Claim exactly once before any network call. An interrupted submission must
// be reconciled; it must never be blindly moved back to 'ready'.
func (q *Queries) ClaimManagedNumberPurchaseSubmission(ctx context.Context, arg ClaimManagedNumberPurchaseSubmissionParams) (ManagedNumberOrder, error) {
	row := q.db.QueryRow(ctx, claimManagedNumberPurchaseSubmission, arg.OrganizationID, arg.ID)
	var i ManagedNumberOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProviderID,
		&i.PhoneNumberID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Number,
		&i.CountryCode,
		&i.AvailableDidID,
		&i.SkuID,
		&i.QuoteID,
		&i.PurchaseAmountMinor,
		&i.RecurringAmountMinor,
		&i.Currency,
		&i.QuoteExpiresAt,
		&i.WalletReservationID,
		&i.ProviderOrderID,
		&i.ProviderDidID,
		&i.Status,
		&i.SubmittedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createManagedNumberPurchaseIntent = `-- name: CreateManagedNumberPurchaseIntent :one
INSERT INTO managed_number_orders (
    id,
    organization_id,
    provider_id,
    idempotency_key,
    request_hash,
    number,
    country_code,
    available_did_id,
    sku_id,
    quote_id,
    purchase_amount_minor,
    recurring_amount_minor,
    currency,
    quote_expires_at
)
SELECT
    $1::UUID,
    o.id,
    cp.id,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8::UUID,
    $9::BIGINT,
    $10::BIGINT,
    $11,
    $12::TIMESTAMPTZ
FROM organizations AS o
JOIN carrier_providers AS cp ON cp.slug = 'didww' AND cp.adapter = 'didww' AND cp.status = 'active'
WHERE o.id = $13::UUID
  AND o.status = 'active'
  AND o.deleted_at IS NULL
  AND $12::TIMESTAMPTZ > now()
ON CONFLICT DO NOTHING
RETURNING id, organization_id, provider_id, phone_number_id, idempotency_key, request_hash, number, country_code, available_did_id, sku_id, quote_id, purchase_amount_minor, recurring_amount_minor, currency, quote_expires_at, wallet_reservation_id, provider_order_id, provider_did_id, status, submitted_at, error_code, error_message, created_at, updated_at
`

type CreateManagedNumberPurchaseIntentParams struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	IdempotencyKey       string             `db:"idempotency_key" json:"idempotency_key"`
	RequestHash          string             `db:"request_hash" json:"request_hash"`
	Number               string             `db:"number" json:"number"`
	CountryCode          string             `db:"country_code" json:"country_code"`
	AvailableDidID       string             `db:"available_did_id" json:"available_did_id"`
	SkuID                string             `db:"sku_id" json:"sku_id"`
	QuoteID              uuid.UUID          `db:"quote_id" json:"quote_id"`
	PurchaseAmountMinor  int64              `db:"purchase_amount_minor" json:"purchase_amount_minor"`
	RecurringAmountMinor int64              `db:"recurring_amount_minor" json:"recurring_amount_minor"`
	Currency             string             `db:"currency" json:"currency"`
	QuoteExpiresAt       pgtype.Timestamptz `db:"quote_expires_at" json:"quote_expires_at"`
	OrganizationID       uuid.UUID          `db:"organization_id" json:"organization_id"`
}

// These are internal purchase primitives, not an HTTP purchase API.
// A trusted server-side quote/selection must be validated before the caller
// creates an intent. A zero-row insert can mean a replay, conflicting intent,
// unavailable tenant/provider, or an expired quote; inspect the existing key
// before deciding whether to return a replay or a conflict.
func (q *Queries) CreateManagedNumberPurchaseIntent(ctx context.Context, arg CreateManagedNumberPurchaseIntentParams) (ManagedNumberOrder, error) {
	row := q.db.QueryRow(ctx, createManagedNumberPurchaseIntent,
		arg.ID,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.Number,
		arg.CountryCode,
		arg.AvailableDidID,
		arg.SkuID,
		arg.QuoteID,
		arg.PurchaseAmountMinor,
		arg.RecurringAmountMinor,
		arg.Currency,
		arg.QuoteExpiresAt,
		arg.OrganizationID,
	)
	var i ManagedNumberOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProviderID,
		&i.PhoneNumberID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Number,
		&i.CountryCode,
		&i.AvailableDidID,
		&i.SkuID,
		&i.QuoteID,
		&i.PurchaseAmountMinor,
		&i.RecurringAmountMinor,
		&i.Currency,
		&i.QuoteExpiresAt,
		&i.WalletReservationID,
		&i.ProviderOrderID,
		&i.ProviderDidID,
		&i.Status,
		&i.SubmittedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failUnsubmittedManagedNumberPurchase = `-- name: FailUnsubmittedManagedNumberPurchase :one
UPDATE managed_number_orders
SET status = 'failed',
    error_code = $1,
    error_message = $2
WHERE organization_id = $3
  AND id = $4
  AND status IN ('pending_funding', 'ready')
  AND submitted_at IS NULL
RETURNING id, organization_id, provider_id, phone_number_id, idempotency_key, request_hash, number, country_code, available_did_id, sku_id, quote_id, purchase_amount_minor, recurring_amount_minor, currency, quote_expires_at, wallet_reservation_id, provider_order_id, provider_did_id, status, submitted_at, error_code, error_message, created_at, updated_at
`

type FailUnsubmittedManagedNumberPurchaseParams struct {
	ErrorCode      *string   `db:"error_code" json:"error_code"`
	ErrorMessage   *string   `db:"error_message" json:"error_message"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

// Failure before submitting to the provider is safe to record without
// upstream reconciliation; after submission it is not.
func (q *Queries) FailUnsubmittedManagedNumberPurchase(ctx context.Context, arg FailUnsubmittedManagedNumberPurchaseParams) (ManagedNumberOrder, error) {
	row := q.db.QueryRow(ctx, failUnsubmittedManagedNumberPurchase,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.OrganizationID,
		arg.ID,
	)
	var i ManagedNumberOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProviderID,
		&i.PhoneNumberID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Number,
		&i.CountryCode,
		&i.AvailableDidID,
		&i.SkuID,
		&i.QuoteID,
		&i.PurchaseAmountMinor,
		&i.RecurringAmountMinor,
		&i.Currency,
		&i.QuoteExpiresAt,
		&i.WalletReservationID,
		&i.ProviderOrderID,
		&i.ProviderDidID,
		&i.Status,
		&i.SubmittedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getManagedNumberPurchaseIntentByID = `-- name: GetManagedNumberPurchaseIntentByID :one
SELECT id, organization_id, provider_id, phone_number_id, idempotency_key, request_hash, number, country_code, available_did_id, sku_id, quote_id, purchase_amount_minor, recurring_amount_minor, currency, quote_expires_at, wallet_reservation_id, provider_order_id, provider_did_id, status, submitted_at, error_code, error_message, created_at, updated_at
FROM managed_number_orders
WHERE organization_id = $1
  AND id = $2
LIMIT 1
`

type GetManagedNumberPurchaseIntentByIDParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetManagedNumberPurchaseIntentByID(ctx context.Context, arg GetManagedNumberPurchaseIntentByIDParams) (ManagedNumberOrder, error) {
	row := q.db.QueryRow(ctx, getManagedNumberPurchaseIntentByID, arg.OrganizationID, arg.ID)
	var i ManagedNumberOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProviderID,
		&i.PhoneNumberID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Number,
		&i.CountryCode,
		&i.AvailableDidID,
		&i.SkuID,
		&i.QuoteID,
		&i.PurchaseAmountMinor,
		&i.RecurringAmountMinor,
		&i.Currency,
		&i.QuoteExpiresAt,
		&i.WalletReservationID,
		&i.ProviderOrderID,
		&i.ProviderDidID,
		&i.Status,
		&i.SubmittedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getManagedNumberPurchaseIntentByKey = `-- name: GetManagedNumberPurchaseIntentByKey :one
SELECT id, organization_id, provider_id, phone_number_id, idempotency_key, request_hash, number, country_code, available_did_id, sku_id, quote_id, purchase_amount_minor, recurring_amount_minor, currency, quote_expires_at, wallet_reservation_id, provider_order_id, provider_did_id, status, submitted_at, error_code, error_message, created_at, updated_at
FROM managed_number_orders
WHERE organization_id = $1
  AND idempotency_key = $2
LIMIT 1
`

type GetManagedNumberPurchaseIntentByKeyParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	IdempotencyKey string    `db:"idempotency_key" json:"idempotency_key"`
}

func (q *Queries) GetManagedNumberPurchaseIntentByKey(ctx context.Context, arg GetManagedNumberPurchaseIntentByKeyParams) (ManagedNumberOrder, error) {
	row := q.db.QueryRow(ctx, getManagedNumberPurchaseIntentByKey, arg.OrganizationID, arg.IdempotencyKey)
	var i ManagedNumberOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProviderID,
		&i.PhoneNumberID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Number,
		&i.CountryCode,
		&i.AvailableDidID,
		&i.SkuID,
		&i.QuoteID,
		&i.PurchaseAmountMinor,
		&i.RecurringAmountMinor,
		&i.Currency,
		&i.QuoteExpiresAt,
		&i.WalletReservationID,
		&i.ProviderOrderID,
		&i.ProviderDidID,
		&i.Status,
		&i.SubmittedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockManagedNumberPurchaseIntent = `-- name: LockManagedNumberPurchaseIntent :one
SELECT id, organization_id, provider_id, phone_number_id, idempotency_key, request_hash, number, country_code, available_did_id, sku_id, quote_id, purchase_amount_minor, recurring_amount_minor, currency, quote_expires_at, wallet_reservation_id, provider_order_id, provider_did_id, status, submitted_at, error_code, error_message, created_at, updated_at
FROM managed_number_orders
WHERE organization_id = $1
  AND id = $2
FOR UPDATE
`

type LockManagedNumberPurchaseIntentParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) LockManagedNumberPurchaseIntent(ctx context.Context, arg LockManagedNumberPurchaseIntentParams) (ManagedNumberOrder, error) {
	row := q.db.QueryRow(ctx, lockManagedNumberPurchaseIntent, arg.OrganizationID, arg.ID)
	var i ManagedNumberOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProviderID,
		&i.PhoneNumberID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Number,
		&i.CountryCode,
		&i.AvailableDidID,
		&i.SkuID,
		&i.QuoteID,
		&i.PurchaseAmountMinor,
		&i.RecurringAmountMinor,
		&i.Currency,
		&i.QuoteExpiresAt,
		&i.WalletReservationID,
		&i.ProviderOrderID,
		&i.ProviderDidID,
		&i.Status,
		&i.SubmittedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markManagedNumberPurchaseFunded = `-- name: MarkManagedNumberPurchaseFunded :one
UPDATE managed_number_orders
SET wallet_reservation_id = $1,
    status = 'ready'
WHERE organization_id = $2
  AND id = $3
  AND status = 'pending_funding'
  AND wallet_reservation_id IS NULL
  AND quote_expires_at > now()
RETURNING id, organization_id, provider_id, phone_number_id, idempotency_key, request_hash, number, country_code, available_did_id, sku_id, quote_id, purchase_amount_minor, recurring_amount_minor, currency, quote_expires_at, wallet_reservation_id, provider_order_id, provider_did_id, status, submitted_at, error_code, error_message, created_at, updated_at
`

type MarkManagedNumberPurchaseFundedParams struct {
	WalletReservationID *uuid.UUID `db:"wallet_reservation_id" json:"wallet_reservation_id"`
	OrganizationID      uuid.UUID  `db:"organization_id" json:"organization_id"`
	ID                  uuid.UUID  `db:"id" json:"id"`
}

// A wallet integration must actually reserve the accepted amount before
// invoking this transition. This UUID is a reference, not proof of funds.
func (q *Queries) MarkManagedNumberPurchaseFunded(ctx context.Context, arg MarkManagedNumberPurchaseFundedParams) (ManagedNumberOrder, error) {
	row := q.db.QueryRow(ctx, markManagedNumberPurchaseFunded, arg.WalletReservationID, arg.OrganizationID, arg.ID)
	var i ManagedNumberOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProviderID,
		&i.PhoneNumberID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Number,
		&i.CountryCode,
		&i.AvailableDidID,
		&i.SkuID,
		&i.QuoteID,
		&i.PurchaseAmountMinor,
		&i.RecurringAmountMinor,
		&i.Currency,
		&i.QuoteExpiresAt,
		&i.WalletReservationID,
		&i.ProviderOrderID,
		&i.ProviderDidID,
		&i.Status,
		&i.SubmittedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markManagedNumberPurchaseOutcomeUnknown = `-- name: MarkManagedNumberPurchaseOutcomeUnknown :one
UPDATE managed_number_orders
SET status = 'outcome_unknown'
WHERE organization_id = $1
  AND id = $2
  AND status = 'submitting'
RETURNING id, organization_id, provider_id, phone_number_id, idempotency_key, request_hash, number, country_code, available_did_id, sku_id, quote_id, purchase_amount_minor, recurring_amount_minor, currency, quote_expires_at, wallet_reservation_id, provider_order_id, provider_did_id, status, submitted_at, error_code, error_message, created_at, updated_at
`

type MarkManagedNumberPurchaseOutcomeUnknownParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkManagedNumberPurchaseOutcomeUnknown(ctx context.Context, arg MarkManagedNumberPurchaseOutcomeUnknownParams) (ManagedNumberOrder, error) {
	row := q.db.QueryRow(ctx, markManagedNumberPurchaseOutcomeUnknown, arg.OrganizationID, arg.ID)
	var i ManagedNumberOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProviderID,
		&i.PhoneNumberID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Number,
		&i.CountryCode,
		&i.AvailableDidID,
		&i.SkuID,
		&i.QuoteID,
		&i.PurchaseAmountMinor,
		&i.RecurringAmountMinor,
		&i.Currency,
		&i.QuoteExpiresAt,
		&i.WalletReservationID,
		&i.ProviderOrderID,
		&i.ProviderDidID,
		&i.Status,
		&i.SubmittedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordManagedNumberAcquiredDID = `-- name: RecordManagedNumberAcquiredDID :one
UPDATE managed_number_orders
SET provider_did_id = $1,
    status = 'configuring'
WHERE organization_id = $2
  AND id = $3
  AND status = 'provider_pending'
  AND provider_order_id IS NOT NULL
  AND provider_did_id IS NULL
RETURNING id, organization_id, provider_id, phone_number_id, idempotency_key, request_hash, number, country_code, available_did_id, sku_id, quote_id, purchase_amount_minor, recurring_amount_minor, currency, quote_expires_at, wallet_reservation_id, provider_order_id, provider_did_id, status, submitted_at, error_code, error_message, created_at, updated_at
`

type RecordManagedNumberAcquiredDIDParams struct {
	ProviderDidID  *string   `db:"provider_did_id" json:"provider_did_id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

// Only after the provider confirms ownership of the exact selected number
// and DID may the worker advance to inbound-trunk provisioning.
func (q *Queries) RecordManagedNumberAcquiredDID(ctx context.Context, arg RecordManagedNumberAcquiredDIDParams) (ManagedNumberOrder, error) {
	row := q.db.QueryRow(ctx, recordManagedNumberAcquiredDID, arg.ProviderDidID, arg.OrganizationID, arg.ID)
	var i ManagedNumberOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProviderID,
		&i.PhoneNumberID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Number,
		&i.CountryCode,
		&i.AvailableDidID,
		&i.SkuID,
		&i.QuoteID,
		&i.PurchaseAmountMinor,
		&i.RecurringAmountMinor,
		&i.Currency,
		&i.QuoteExpiresAt,
		&i.WalletReservationID,
		&i.ProviderOrderID,
		&i.ProviderDidID,
		&i.Status,
		&i.SubmittedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordManagedNumberProviderOrder = `-- name: RecordManagedNumberProviderOrder :one
UPDATE managed_number_orders
SET provider_order_id = $1,
    status = 'provider_pending'
WHERE organization_id = $2
  AND id = $3
  AND status IN ('submitting', 'outcome_unknown', 'provider_pending')
  AND (provider_order_id IS NULL OR provider_order_id = $1)
RETURNING id, organization_id, provider_id, phone_number_id, idempotency_key, request_hash, number, country_code, available_did_id, sku_id, quote_id, purchase_amount_minor, recurring_amount_minor, currency, quote_expires_at, wallet_reservation_id, provider_order_id, provider_did_id, status, submitted_at, error_code, error_message, created_at, updated_at
`

type RecordManagedNumberProviderOrderParams struct {
	ProviderOrderID *string   `db:"provider_order_id" json:"provider_order_id"`
	OrganizationID  uuid.UUID `db:"organization_id" json:"organization_id"`
	ID              uuid.UUID `db:"id" json:"id"`
}

// Only after reconciliation has matched the upstream order to this internal
// intent, including the original external reference, should it be persisted.
func (q *Queries) RecordManagedNumberProviderOrder(ctx context.Context, arg RecordManagedNumberProviderOrderParams) (ManagedNumberOrder, error) {
	row := q.db.QueryRow(ctx, recordManagedNumberProviderOrder, arg.ProviderOrderID, arg.OrganizationID, arg.ID)
	var i ManagedNumberOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProviderID,
		&i.PhoneNumberID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Number,
		&i.CountryCode,
		&i.AvailableDidID,
		&i.SkuID,
		&i.QuoteID,
		&i.PurchaseAmountMinor,
		&i.RecurringAmountMinor,
		&i.Currency,
		&i.QuoteExpiresAt,
		&i.WalletReservationID,
		&i.ProviderOrderID,
		&i.ProviderDidID,
		&i.Status,
		&i.SubmittedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
