// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: managed_number_orders.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimManagedNumberOrderSubmission = `-- name: ClaimManagedNumberOrderSubmission :one
UPDATE managed_number_orders
SET status = 'submitting', submitted_at = now(),
    error_code = NULL, error_message = NULL
WHERE id = $1 AND status = 'ready'
RETURNING id, organization_id, provider_id, phone_number_id, idempotency_key, request_hash, number, country_code, available_did_id, sku_id, provider_order_id, provider_did_id, inbound_trunk_id, status, submitted_at, ownership_verified_at, routing_verified_at, activated_at, reconcile_after, reconcile_attempts, error_code, error_message, created_at, updated_at
`

func (q *Queries) ClaimManagedNumberOrderSubmission(ctx context.Context, id uuid.UUID) (ManagedNumberOrder, error) {
	row := q.db.QueryRow(ctx, claimManagedNumberOrderSubmission, id)
	var i ManagedNumberOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProviderID,
		&i.PhoneNumberID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Number,
		&i.CountryCode,
		&i.AvailableDidID,
		&i.SkuID,
		&i.ProviderOrderID,
		&i.ProviderDidID,
		&i.InboundTrunkID,
		&i.Status,
		&i.SubmittedAt,
		&i.OwnershipVerifiedAt,
		&i.RoutingVerifiedAt,
		&i.ActivatedAt,
		&i.ReconcileAfter,
		&i.ReconcileAttempts,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeManagedNumberOrder = `-- name: CompleteManagedNumberOrder :one
UPDATE managed_number_orders
SET phone_number_id = $1,
    inbound_trunk_id = $2,
    routing_verified_at = $3,
    activated_at = $3, status = 'completed',
    error_code = NULL, error_message = NULL
WHERE id = $4 AND status = 'configuring'
RETURNING id, organization_id, provider_id, phone_number_id, idempotency_key, request_hash, number, country_code, available_did_id, sku_id, provider_order_id, provider_did_id, inbound_trunk_id, status, submitted_at, ownership_verified_at, routing_verified_at, activated_at, reconcile_after, reconcile_attempts, error_code, error_message, created_at, updated_at
`

type CompleteManagedNumberOrderParams struct {
	PhoneNumberID  *uuid.UUID         `db:"phone_number_id" json:"phone_number_id"`
	InboundTrunkID *string            `db:"inbound_trunk_id" json:"inbound_trunk_id"`
	VerifiedAt     pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	ID             uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) CompleteManagedNumberOrder(ctx context.Context, arg CompleteManagedNumberOrderParams) (ManagedNumberOrder, error) {
	row := q.db.QueryRow(ctx, completeManagedNumberOrder,
		arg.PhoneNumberID,
		arg.InboundTrunkID,
		arg.VerifiedAt,
		arg.ID,
	)
	var i ManagedNumberOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProviderID,
		&i.PhoneNumberID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Number,
		&i.CountryCode,
		&i.AvailableDidID,
		&i.SkuID,
		&i.ProviderOrderID,
		&i.ProviderDidID,
		&i.InboundTrunkID,
		&i.Status,
		&i.SubmittedAt,
		&i.OwnershipVerifiedAt,
		&i.RoutingVerifiedAt,
		&i.ActivatedAt,
		&i.ReconcileAfter,
		&i.ReconcileAttempts,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createManagedNumberOrder = `-- name: CreateManagedNumberOrder :one
INSERT INTO managed_number_orders (
    id, organization_id, provider_id, idempotency_key, request_hash,
    number, country_code, available_did_id, sku_id
)
SELECT $1, o.id, cp.id, $2,
       $3, $4, $5,
       $6, $7
FROM organizations AS o
JOIN carrier_providers AS cp
  ON cp.slug = 'didww' AND cp.adapter = 'didww' AND cp.status = 'active'
WHERE o.id = $8
  AND o.status = 'active'
  AND o.deleted_at IS NULL
ON CONFLICT (organization_id, idempotency_key) DO NOTHING
RETURNING id, organization_id, provider_id, phone_number_id, idempotency_key, request_hash, number, country_code, available_did_id, sku_id, provider_order_id, provider_did_id, inbound_trunk_id, status, submitted_at, ownership_verified_at, routing_verified_at, activated_at, reconcile_after, reconcile_attempts, error_code, error_message, created_at, updated_at
`

type CreateManagedNumberOrderParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	IdempotencyKey string    `db:"idempotency_key" json:"idempotency_key"`
	RequestHash    string    `db:"request_hash" json:"request_hash"`
	Number         string    `db:"number" json:"number"`
	CountryCode    string    `db:"country_code" json:"country_code"`
	AvailableDidID string    `db:"available_did_id" json:"available_did_id"`
	SkuID          string    `db:"sku_id" json:"sku_id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) CreateManagedNumberOrder(ctx context.Context, arg CreateManagedNumberOrderParams) (ManagedNumberOrder, error) {
	row := q.db.QueryRow(ctx, createManagedNumberOrder,
		arg.ID,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.Number,
		arg.CountryCode,
		arg.AvailableDidID,
		arg.SkuID,
		arg.OrganizationID,
	)
	var i ManagedNumberOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProviderID,
		&i.PhoneNumberID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Number,
		&i.CountryCode,
		&i.AvailableDidID,
		&i.SkuID,
		&i.ProviderOrderID,
		&i.ProviderDidID,
		&i.InboundTrunkID,
		&i.Status,
		&i.SubmittedAt,
		&i.OwnershipVerifiedAt,
		&i.RoutingVerifiedAt,
		&i.ActivatedAt,
		&i.ReconcileAfter,
		&i.ReconcileAttempts,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getManagedNumberOrder = `-- name: GetManagedNumberOrder :one
SELECT id, organization_id, provider_id, phone_number_id, idempotency_key, request_hash, number, country_code, available_did_id, sku_id, provider_order_id, provider_did_id, inbound_trunk_id, status, submitted_at, ownership_verified_at, routing_verified_at, activated_at, reconcile_after, reconcile_attempts, error_code, error_message, created_at, updated_at
FROM managed_number_orders
WHERE organization_id = $1
  AND id = $2
LIMIT 1
`

type GetManagedNumberOrderParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetManagedNumberOrder(ctx context.Context, arg GetManagedNumberOrderParams) (ManagedNumberOrder, error) {
	row := q.db.QueryRow(ctx, getManagedNumberOrder, arg.OrganizationID, arg.ID)
	var i ManagedNumberOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProviderID,
		&i.PhoneNumberID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Number,
		&i.CountryCode,
		&i.AvailableDidID,
		&i.SkuID,
		&i.ProviderOrderID,
		&i.ProviderDidID,
		&i.InboundTrunkID,
		&i.Status,
		&i.SubmittedAt,
		&i.OwnershipVerifiedAt,
		&i.RoutingVerifiedAt,
		&i.ActivatedAt,
		&i.ReconcileAfter,
		&i.ReconcileAttempts,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getManagedNumberOrderByKey = `-- name: GetManagedNumberOrderByKey :one
SELECT id, organization_id, provider_id, phone_number_id, idempotency_key, request_hash, number, country_code, available_did_id, sku_id, provider_order_id, provider_did_id, inbound_trunk_id, status, submitted_at, ownership_verified_at, routing_verified_at, activated_at, reconcile_after, reconcile_attempts, error_code, error_message, created_at, updated_at
FROM managed_number_orders
WHERE organization_id = $1
  AND idempotency_key = $2
LIMIT 1
`

type GetManagedNumberOrderByKeyParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	IdempotencyKey string    `db:"idempotency_key" json:"idempotency_key"`
}

func (q *Queries) GetManagedNumberOrderByKey(ctx context.Context, arg GetManagedNumberOrderByKeyParams) (ManagedNumberOrder, error) {
	row := q.db.QueryRow(ctx, getManagedNumberOrderByKey, arg.OrganizationID, arg.IdempotencyKey)
	var i ManagedNumberOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProviderID,
		&i.PhoneNumberID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Number,
		&i.CountryCode,
		&i.AvailableDidID,
		&i.SkuID,
		&i.ProviderOrderID,
		&i.ProviderDidID,
		&i.InboundTrunkID,
		&i.Status,
		&i.SubmittedAt,
		&i.OwnershipVerifiedAt,
		&i.RoutingVerifiedAt,
		&i.ActivatedAt,
		&i.ReconcileAfter,
		&i.ReconcileAttempts,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getManagedNumberOrderInternal = `-- name: GetManagedNumberOrderInternal :one
SELECT id, organization_id, provider_id, phone_number_id, idempotency_key, request_hash, number, country_code, available_did_id, sku_id, provider_order_id, provider_did_id, inbound_trunk_id, status, submitted_at, ownership_verified_at, routing_verified_at, activated_at, reconcile_after, reconcile_attempts, error_code, error_message, created_at, updated_at
FROM managed_number_orders
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetManagedNumberOrderInternal(ctx context.Context, id uuid.UUID) (ManagedNumberOrder, error) {
	row := q.db.QueryRow(ctx, getManagedNumberOrderInternal, id)
	var i ManagedNumberOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProviderID,
		&i.PhoneNumberID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Number,
		&i.CountryCode,
		&i.AvailableDidID,
		&i.SkuID,
		&i.ProviderOrderID,
		&i.ProviderDidID,
		&i.InboundTrunkID,
		&i.Status,
		&i.SubmittedAt,
		&i.OwnershipVerifiedAt,
		&i.RoutingVerifiedAt,
		&i.ActivatedAt,
		&i.ReconcileAfter,
		&i.ReconcileAttempts,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listManagedNumberOrdersForReconciliation = `-- name: ListManagedNumberOrdersForReconciliation :many
SELECT id, organization_id, provider_id, phone_number_id, idempotency_key, request_hash, number, country_code, available_did_id, sku_id, provider_order_id, provider_did_id, inbound_trunk_id, status, submitted_at, ownership_verified_at, routing_verified_at, activated_at, reconcile_after, reconcile_attempts, error_code, error_message, created_at, updated_at
FROM managed_number_orders
WHERE status IN ('submitting', 'outcome_unknown', 'provider_pending', 'configuring')
  AND reconcile_after <= now()
ORDER BY reconcile_after, created_at
LIMIT $1
`

func (q *Queries) ListManagedNumberOrdersForReconciliation(ctx context.Context, batchSize int32) ([]ManagedNumberOrder, error) {
	rows, err := q.db.Query(ctx, listManagedNumberOrdersForReconciliation, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManagedNumberOrder{}
	for rows.Next() {
		var i ManagedNumberOrder
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProviderID,
			&i.PhoneNumberID,
			&i.IdempotencyKey,
			&i.RequestHash,
			&i.Number,
			&i.CountryCode,
			&i.AvailableDidID,
			&i.SkuID,
			&i.ProviderOrderID,
			&i.ProviderDidID,
			&i.InboundTrunkID,
			&i.Status,
			&i.SubmittedAt,
			&i.OwnershipVerifiedAt,
			&i.RoutingVerifiedAt,
			&i.ActivatedAt,
			&i.ReconcileAfter,
			&i.ReconcileAttempts,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockManagedNumberOrder = `-- name: LockManagedNumberOrder :one
SELECT id, organization_id, provider_id, phone_number_id, idempotency_key, request_hash, number, country_code, available_did_id, sku_id, provider_order_id, provider_did_id, inbound_trunk_id, status, submitted_at, ownership_verified_at, routing_verified_at, activated_at, reconcile_after, reconcile_attempts, error_code, error_message, created_at, updated_at
FROM managed_number_orders
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockManagedNumberOrder(ctx context.Context, id uuid.UUID) (ManagedNumberOrder, error) {
	row := q.db.QueryRow(ctx, lockManagedNumberOrder, id)
	var i ManagedNumberOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProviderID,
		&i.PhoneNumberID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Number,
		&i.CountryCode,
		&i.AvailableDidID,
		&i.SkuID,
		&i.ProviderOrderID,
		&i.ProviderDidID,
		&i.InboundTrunkID,
		&i.Status,
		&i.SubmittedAt,
		&i.OwnershipVerifiedAt,
		&i.RoutingVerifiedAt,
		&i.ActivatedAt,
		&i.ReconcileAfter,
		&i.ReconcileAttempts,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markManagedNumberOrderManualReview = `-- name: MarkManagedNumberOrderManualReview :one
UPDATE managed_number_orders
SET status = 'manual_review', error_code = $1,
    error_message = 'provider identity requires manual review'
WHERE id = $2 AND status <> 'completed'
RETURNING id, organization_id, provider_id, phone_number_id, idempotency_key, request_hash, number, country_code, available_did_id, sku_id, provider_order_id, provider_did_id, inbound_trunk_id, status, submitted_at, ownership_verified_at, routing_verified_at, activated_at, reconcile_after, reconcile_attempts, error_code, error_message, created_at, updated_at
`

type MarkManagedNumberOrderManualReviewParams struct {
	ErrorCode *string   `db:"error_code" json:"error_code"`
	ID        uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkManagedNumberOrderManualReview(ctx context.Context, arg MarkManagedNumberOrderManualReviewParams) (ManagedNumberOrder, error) {
	row := q.db.QueryRow(ctx, markManagedNumberOrderManualReview, arg.ErrorCode, arg.ID)
	var i ManagedNumberOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProviderID,
		&i.PhoneNumberID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Number,
		&i.CountryCode,
		&i.AvailableDidID,
		&i.SkuID,
		&i.ProviderOrderID,
		&i.ProviderDidID,
		&i.InboundTrunkID,
		&i.Status,
		&i.SubmittedAt,
		&i.OwnershipVerifiedAt,
		&i.RoutingVerifiedAt,
		&i.ActivatedAt,
		&i.ReconcileAfter,
		&i.ReconcileAttempts,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markManagedNumberOrderOutcomeUnknown = `-- name: MarkManagedNumberOrderOutcomeUnknown :one
UPDATE managed_number_orders
SET status = 'outcome_unknown', error_code = $1,
    error_message = $2,
    reconcile_after = $3
WHERE id = $4 AND status = 'submitting'
RETURNING id, organization_id, provider_id, phone_number_id, idempotency_key, request_hash, number, country_code, available_did_id, sku_id, provider_order_id, provider_did_id, inbound_trunk_id, status, submitted_at, ownership_verified_at, routing_verified_at, activated_at, reconcile_after, reconcile_attempts, error_code, error_message, created_at, updated_at
`

type MarkManagedNumberOrderOutcomeUnknownParams struct {
	ErrorCode      *string            `db:"error_code" json:"error_code"`
	ErrorMessage   *string            `db:"error_message" json:"error_message"`
	ReconcileAfter pgtype.Timestamptz `db:"reconcile_after" json:"reconcile_after"`
	ID             uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) MarkManagedNumberOrderOutcomeUnknown(ctx context.Context, arg MarkManagedNumberOrderOutcomeUnknownParams) (ManagedNumberOrder, error) {
	row := q.db.QueryRow(ctx, markManagedNumberOrderOutcomeUnknown,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ReconcileAfter,
		arg.ID,
	)
	var i ManagedNumberOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProviderID,
		&i.PhoneNumberID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Number,
		&i.CountryCode,
		&i.AvailableDidID,
		&i.SkuID,
		&i.ProviderOrderID,
		&i.ProviderDidID,
		&i.InboundTrunkID,
		&i.Status,
		&i.SubmittedAt,
		&i.OwnershipVerifiedAt,
		&i.RoutingVerifiedAt,
		&i.ActivatedAt,
		&i.ReconcileAfter,
		&i.ReconcileAttempts,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordManagedNumberOwnedDID = `-- name: RecordManagedNumberOwnedDID :one
UPDATE managed_number_orders
SET provider_did_id = $1,
    ownership_verified_at = $2, status = 'configuring',
    error_code = NULL, error_message = NULL
WHERE id = $3 AND status IN ('provider_pending', 'configuring')
  AND (provider_did_id IS NULL OR provider_did_id = $1)
RETURNING id, organization_id, provider_id, phone_number_id, idempotency_key, request_hash, number, country_code, available_did_id, sku_id, provider_order_id, provider_did_id, inbound_trunk_id, status, submitted_at, ownership_verified_at, routing_verified_at, activated_at, reconcile_after, reconcile_attempts, error_code, error_message, created_at, updated_at
`

type RecordManagedNumberOwnedDIDParams struct {
	ProviderDidID *string            `db:"provider_did_id" json:"provider_did_id"`
	VerifiedAt    pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	ID            uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) RecordManagedNumberOwnedDID(ctx context.Context, arg RecordManagedNumberOwnedDIDParams) (ManagedNumberOrder, error) {
	row := q.db.QueryRow(ctx, recordManagedNumberOwnedDID, arg.ProviderDidID, arg.VerifiedAt, arg.ID)
	var i ManagedNumberOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProviderID,
		&i.PhoneNumberID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Number,
		&i.CountryCode,
		&i.AvailableDidID,
		&i.SkuID,
		&i.ProviderOrderID,
		&i.ProviderDidID,
		&i.InboundTrunkID,
		&i.Status,
		&i.SubmittedAt,
		&i.OwnershipVerifiedAt,
		&i.RoutingVerifiedAt,
		&i.ActivatedAt,
		&i.ReconcileAfter,
		&i.ReconcileAttempts,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordManagedNumberProviderOrder = `-- name: RecordManagedNumberProviderOrder :one
UPDATE managed_number_orders
SET provider_order_id = $1, status = 'provider_pending',
    error_code = NULL, error_message = NULL,
    reconcile_after = $2
WHERE id = $3
  AND status IN ('submitting', 'outcome_unknown', 'provider_pending')
  AND (provider_order_id IS NULL OR provider_order_id = $1)
RETURNING id, organization_id, provider_id, phone_number_id, idempotency_key, request_hash, number, country_code, available_did_id, sku_id, provider_order_id, provider_did_id, inbound_trunk_id, status, submitted_at, ownership_verified_at, routing_verified_at, activated_at, reconcile_after, reconcile_attempts, error_code, error_message, created_at, updated_at
`

type RecordManagedNumberProviderOrderParams struct {
	ProviderOrderID *string            `db:"provider_order_id" json:"provider_order_id"`
	ReconcileAfter  pgtype.Timestamptz `db:"reconcile_after" json:"reconcile_after"`
	ID              uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) RecordManagedNumberProviderOrder(ctx context.Context, arg RecordManagedNumberProviderOrderParams) (ManagedNumberOrder, error) {
	row := q.db.QueryRow(ctx, recordManagedNumberProviderOrder, arg.ProviderOrderID, arg.ReconcileAfter, arg.ID)
	var i ManagedNumberOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProviderID,
		&i.PhoneNumberID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Number,
		&i.CountryCode,
		&i.AvailableDidID,
		&i.SkuID,
		&i.ProviderOrderID,
		&i.ProviderDidID,
		&i.InboundTrunkID,
		&i.Status,
		&i.SubmittedAt,
		&i.OwnershipVerifiedAt,
		&i.RoutingVerifiedAt,
		&i.ActivatedAt,
		&i.ReconcileAfter,
		&i.ReconcileAttempts,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const scheduleManagedNumberReconciliation = `-- name: ScheduleManagedNumberReconciliation :one
UPDATE managed_number_orders
SET reconcile_after = $1,
    reconcile_attempts = reconcile_attempts + 1,
    error_code = $2, error_message = NULL
WHERE id = $3
  AND status IN ('submitting', 'outcome_unknown', 'provider_pending', 'configuring')
RETURNING id, organization_id, provider_id, phone_number_id, idempotency_key, request_hash, number, country_code, available_did_id, sku_id, provider_order_id, provider_did_id, inbound_trunk_id, status, submitted_at, ownership_verified_at, routing_verified_at, activated_at, reconcile_after, reconcile_attempts, error_code, error_message, created_at, updated_at
`

type ScheduleManagedNumberReconciliationParams struct {
	ReconcileAfter pgtype.Timestamptz `db:"reconcile_after" json:"reconcile_after"`
	ErrorCode      *string            `db:"error_code" json:"error_code"`
	ID             uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) ScheduleManagedNumberReconciliation(ctx context.Context, arg ScheduleManagedNumberReconciliationParams) (ManagedNumberOrder, error) {
	row := q.db.QueryRow(ctx, scheduleManagedNumberReconciliation, arg.ReconcileAfter, arg.ErrorCode, arg.ID)
	var i ManagedNumberOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProviderID,
		&i.PhoneNumberID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Number,
		&i.CountryCode,
		&i.AvailableDidID,
		&i.SkuID,
		&i.ProviderOrderID,
		&i.ProviderDidID,
		&i.InboundTrunkID,
		&i.Status,
		&i.SubmittedAt,
		&i.OwnershipVerifiedAt,
		&i.RoutingVerifiedAt,
		&i.ActivatedAt,
		&i.ReconcileAfter,
		&i.ReconcileAttempts,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
