// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: managed_number_renewals.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceManagedNumberRenewal = `-- name: AdvanceManagedNumberRenewal :execrows
UPDATE phone_numbers
SET
    next_renewal_at = $1,
    updated_at = now()
WHERE id = $2
  AND provisioning_mode = 'managed'
  AND status = 'active'
  AND next_renewal_at = $3
`

type AdvanceManagedNumberRenewalParams struct {
	PeriodEnd     pgtype.Timestamptz `db:"period_end" json:"period_end"`
	PhoneNumberID uuid.UUID          `db:"phone_number_id" json:"phone_number_id"`
	PeriodStart   pgtype.Timestamptz `db:"period_start" json:"period_start"`
}

func (q *Queries) AdvanceManagedNumberRenewal(ctx context.Context, arg AdvanceManagedNumberRenewalParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceManagedNumberRenewal, arg.PeriodEnd, arg.PhoneNumberID, arg.PeriodStart)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const advancePaidManagedNumberRenewals = `-- name: AdvancePaidManagedNumberRenewals :execrows
UPDATE phone_numbers AS pn
SET
    next_renewal_at = renewal.period_end,
    updated_at = now()
FROM managed_number_renewals AS renewal
WHERE renewal.phone_number_id = pn.id
  AND renewal.status = 'paid'
  AND pn.provisioning_mode = 'managed'
  AND pn.status = 'active'
  AND pn.next_renewal_at = renewal.period_start
`

func (q *Queries) AdvancePaidManagedNumberRenewals(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, advancePaidManagedNumberRenewals)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimManagedNumberRenewal = `-- name: ClaimManagedNumberRenewal :one
UPDATE managed_number_renewals
SET
    status = 'processing',
    attempt_count = attempt_count + 1,
    last_error = NULL
WHERE id = $1
  AND (
    status IN ('pending', 'payment_failed')
    OR (status = 'processing' AND updated_at <= $2 - INTERVAL '15 minutes')
  )
RETURNING id, organization_id, phone_number_id, period_start, period_end, operation_id, status, amount_micros, currency, attempt_count, next_attempt_at, paid_at, last_error, created_at, updated_at
`

type ClaimManagedNumberRenewalParams struct {
	ID  uuid.UUID   `db:"id" json:"id"`
	Now interface{} `db:"now" json:"now"`
}

func (q *Queries) ClaimManagedNumberRenewal(ctx context.Context, arg ClaimManagedNumberRenewalParams) (ManagedNumberRenewal, error) {
	row := q.db.QueryRow(ctx, claimManagedNumberRenewal, arg.ID, arg.Now)
	var i ManagedNumberRenewal
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PhoneNumberID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.OperationID,
		&i.Status,
		&i.AmountMicros,
		&i.Currency,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.PaidAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listManagedNumberRenewalsDue = `-- name: ListManagedNumberRenewalsDue :many
SELECT renewal.id, renewal.organization_id, renewal.phone_number_id, renewal.period_start, renewal.period_end, renewal.operation_id, renewal.status, renewal.amount_micros, renewal.currency, renewal.attempt_count, renewal.next_attempt_at, renewal.paid_at, renewal.last_error, renewal.created_at, renewal.updated_at, pn.country_code
FROM managed_number_renewals AS renewal
JOIN phone_numbers AS pn ON pn.id = renewal.phone_number_id
WHERE (
    renewal.status IN ('pending', 'payment_failed')
    AND renewal.next_attempt_at <= $1
  ) OR (
    renewal.status = 'processing'
    AND renewal.updated_at <= $1 - INTERVAL '15 minutes'
  )
ORDER BY renewal.next_attempt_at, renewal.period_start
LIMIT $2
`

type ListManagedNumberRenewalsDueParams struct {
	Now   pgtype.Timestamptz `db:"now" json:"now"`
	Batch int32              `db:"batch" json:"batch"`
}

type ListManagedNumberRenewalsDueRow struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	PhoneNumberID  uuid.UUID          `db:"phone_number_id" json:"phone_number_id"`
	PeriodStart    pgtype.Timestamptz `db:"period_start" json:"period_start"`
	PeriodEnd      pgtype.Timestamptz `db:"period_end" json:"period_end"`
	OperationID    uuid.UUID          `db:"operation_id" json:"operation_id"`
	Status         string             `db:"status" json:"status"`
	AmountMicros   *int64             `db:"amount_micros" json:"amount_micros"`
	Currency       *string            `db:"currency" json:"currency"`
	AttemptCount   int32              `db:"attempt_count" json:"attempt_count"`
	NextAttemptAt  pgtype.Timestamptz `db:"next_attempt_at" json:"next_attempt_at"`
	PaidAt         pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
	LastError      *string            `db:"last_error" json:"last_error"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CountryCode    string             `db:"country_code" json:"country_code"`
}

func (q *Queries) ListManagedNumberRenewalsDue(ctx context.Context, arg ListManagedNumberRenewalsDueParams) ([]ListManagedNumberRenewalsDueRow, error) {
	rows, err := q.db.Query(ctx, listManagedNumberRenewalsDue, arg.Now, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListManagedNumberRenewalsDueRow{}
	for rows.Next() {
		var i ListManagedNumberRenewalsDueRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PhoneNumberID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.OperationID,
			&i.Status,
			&i.AmountMicros,
			&i.Currency,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.PaidAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CountryCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markManagedNumberRenewalPaid = `-- name: MarkManagedNumberRenewalPaid :one
UPDATE managed_number_renewals AS renewal
SET
    status = 'paid',
    amount_micros = $1,
    currency = $2,
    paid_at = $3,
    last_error = NULL
FROM phone_numbers AS pn
WHERE renewal.id = $4
  AND renewal.status = 'processing'
  AND pn.id = renewal.phone_number_id
  AND pn.provisioning_mode = 'managed'
  AND pn.status = 'active'
RETURNING renewal.id, renewal.organization_id, renewal.phone_number_id, renewal.period_start, renewal.period_end, renewal.operation_id, renewal.status, renewal.amount_micros, renewal.currency, renewal.attempt_count, renewal.next_attempt_at, renewal.paid_at, renewal.last_error, renewal.created_at, renewal.updated_at
`

type MarkManagedNumberRenewalPaidParams struct {
	AmountMicros *int64             `db:"amount_micros" json:"amount_micros"`
	Currency     *string            `db:"currency" json:"currency"`
	PaidAt       pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
	ID           uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) MarkManagedNumberRenewalPaid(ctx context.Context, arg MarkManagedNumberRenewalPaidParams) (ManagedNumberRenewal, error) {
	row := q.db.QueryRow(ctx, markManagedNumberRenewalPaid,
		arg.AmountMicros,
		arg.Currency,
		arg.PaidAt,
		arg.ID,
	)
	var i ManagedNumberRenewal
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PhoneNumberID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.OperationID,
		&i.Status,
		&i.AmountMicros,
		&i.Currency,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.PaidAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const retryManagedNumberRenewal = `-- name: RetryManagedNumberRenewal :one
UPDATE managed_number_renewals
SET
    status = 'payment_failed',
    next_attempt_at = $1,
    last_error = $2
WHERE id = $3
  AND status = 'processing'
RETURNING id, organization_id, phone_number_id, period_start, period_end, operation_id, status, amount_micros, currency, attempt_count, next_attempt_at, paid_at, last_error, created_at, updated_at
`

type RetryManagedNumberRenewalParams struct {
	NextAttemptAt pgtype.Timestamptz `db:"next_attempt_at" json:"next_attempt_at"`
	LastError     *string            `db:"last_error" json:"last_error"`
	ID            uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) RetryManagedNumberRenewal(ctx context.Context, arg RetryManagedNumberRenewalParams) (ManagedNumberRenewal, error) {
	row := q.db.QueryRow(ctx, retryManagedNumberRenewal, arg.NextAttemptAt, arg.LastError, arg.ID)
	var i ManagedNumberRenewal
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PhoneNumberID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.OperationID,
		&i.Status,
		&i.AmountMicros,
		&i.Currency,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.PaidAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const scheduleManagedNumberRenewals = `-- name: ScheduleManagedNumberRenewals :execrows
INSERT INTO managed_number_renewals (
    organization_id,
    phone_number_id,
    period_start,
    period_end,
    operation_id
)
SELECT
    pn.organization_id,
    pn.id,
    pn.next_renewal_at,
    pn.next_renewal_at + INTERVAL '1 month',
    md5(pn.id::TEXT || ':' || pn.next_renewal_at::TEXT)::UUID
FROM phone_numbers AS pn
WHERE pn.provisioning_mode = 'managed'
  AND pn.status = 'active'
  AND pn.next_renewal_at <= $1
ON CONFLICT (phone_number_id, period_start) DO NOTHING
`

func (q *Queries) ScheduleManagedNumberRenewals(ctx context.Context, now pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, scheduleManagedNumberRenewals, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
