// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messaging_connections.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getMessagingConnection = `-- name: GetMessagingConnection :one
SELECT id, organization_id, channel, name, status, configuration, encrypted_secret, created_at, updated_at FROM messaging_connections
WHERE id = $1 AND status = 'active'
LIMIT 1
`

func (q *Queries) GetMessagingConnection(ctx context.Context, id uuid.UUID) (MessagingConnection, error) {
	row := q.db.QueryRow(ctx, getMessagingConnection, id)
	var i MessagingConnection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Channel,
		&i.Name,
		&i.Status,
		&i.Configuration,
		&i.EncryptedSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveMessagingConnections = `-- name: ListActiveMessagingConnections :many
SELECT id, organization_id, channel, name, status, configuration, encrypted_secret, created_at, updated_at FROM messaging_connections
WHERE status = 'active'
ORDER BY created_at ASC
`

func (q *Queries) ListActiveMessagingConnections(ctx context.Context) ([]MessagingConnection, error) {
	rows, err := q.db.Query(ctx, listActiveMessagingConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessagingConnection{}
	for rows.Next() {
		var i MessagingConnection
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Channel,
			&i.Name,
			&i.Status,
			&i.Configuration,
			&i.EncryptedSecret,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveMessagingConnection = `-- name: ResolveMessagingConnection :one
SELECT id, organization_id, channel, name, status, configuration, encrypted_secret, created_at, updated_at FROM messaging_connections
WHERE organization_id = $1
  AND channel = $2
  AND status = 'active'
ORDER BY created_at ASC
LIMIT 1
`

type ResolveMessagingConnectionParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	Channel        string    `db:"channel" json:"channel"`
}

func (q *Queries) ResolveMessagingConnection(ctx context.Context, arg ResolveMessagingConnectionParams) (MessagingConnection, error) {
	row := q.db.QueryRow(ctx, resolveMessagingConnection, arg.OrganizationID, arg.Channel)
	var i MessagingConnection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Channel,
		&i.Name,
		&i.Status,
		&i.Configuration,
		&i.EncryptedSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
