// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createInboundMessage = `-- name: CreateInboundMessage :one
INSERT INTO messages (
    organization_id,
    carrier_connection_id,
    channel,
    direction,
    status,
    from_address,
    to_address,
    body,
    media,
    provider_message_id,
    received_at
)
SELECT
    $1,
    connection.id,
    $2,
    'inbound',
    'received',
    $3,
    $4,
    $5,
    $6::jsonb,
    $7,
    NOW()
FROM carrier_connections AS connection
JOIN organizations AS organization
  ON organization.id = $1
WHERE connection.id = $8
  AND connection.status = 'active'
  AND organization.status = 'active'
  AND organization.deleted_at IS NULL
  AND (
      (
          connection.scope = 'organization'
          AND connection.organization_id = $1
      )
      OR (
          connection.scope = 'platform'
          AND connection.organization_id IS NULL
      )
  )
ON CONFLICT (carrier_connection_id, provider_message_id)
WHERE carrier_connection_id IS NOT NULL
  AND provider_message_id IS NOT NULL
DO NOTHING
RETURNING id, organization_id, carrier_connection_id, channel, direction, status, from_address, to_address, body, media, provider_message_id, idempotency_key, request_hash, failure_code, failure_message, queued_at, submitted_at, sent_at, delivered_at, received_at, failed_at, created_at, updated_at
`

type CreateInboundMessageParams struct {
	OrganizationID      uuid.UUID `db:"organization_id" json:"organization_id"`
	Channel             string    `db:"channel" json:"channel"`
	FromAddress         string    `db:"from_address" json:"from_address"`
	ToAddress           string    `db:"to_address" json:"to_address"`
	Body                *string   `db:"body" json:"body"`
	Media               []byte    `db:"media" json:"media"`
	ProviderMessageID   *string   `db:"provider_message_id" json:"provider_message_id"`
	CarrierConnectionID uuid.UUID `db:"carrier_connection_id" json:"carrier_connection_id"`
}

func (q *Queries) CreateInboundMessage(ctx context.Context, arg CreateInboundMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createInboundMessage,
		arg.OrganizationID,
		arg.Channel,
		arg.FromAddress,
		arg.ToAddress,
		arg.Body,
		arg.Media,
		arg.ProviderMessageID,
		arg.CarrierConnectionID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CarrierConnectionID,
		&i.Channel,
		&i.Direction,
		&i.Status,
		&i.FromAddress,
		&i.ToAddress,
		&i.Body,
		&i.Media,
		&i.ProviderMessageID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.FailureCode,
		&i.FailureMessage,
		&i.QueuedAt,
		&i.SubmittedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReceivedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOutboundMessage = `-- name: CreateOutboundMessage :one
INSERT INTO messages (
    organization_id,
    channel,
    direction,
    status,
    from_address,
    to_address,
    body,
    media,
    idempotency_key,
    request_hash,
    queued_at
) VALUES (
    $1,
    $2,
    'outbound',
    'queued',
    $3,
    $4,
    $5,
    $6::jsonb,
    $7,
    $8,
    NOW()
)
ON CONFLICT (organization_id, idempotency_key)
WHERE idempotency_key IS NOT NULL
DO NOTHING
RETURNING id, organization_id, carrier_connection_id, channel, direction, status, from_address, to_address, body, media, provider_message_id, idempotency_key, request_hash, failure_code, failure_message, queued_at, submitted_at, sent_at, delivered_at, received_at, failed_at, created_at, updated_at
`

type CreateOutboundMessageParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	Channel        string    `db:"channel" json:"channel"`
	FromAddress    string    `db:"from_address" json:"from_address"`
	ToAddress      string    `db:"to_address" json:"to_address"`
	Body           *string   `db:"body" json:"body"`
	Media          []byte    `db:"media" json:"media"`
	IdempotencyKey *string   `db:"idempotency_key" json:"idempotency_key"`
	RequestHash    *string   `db:"request_hash" json:"request_hash"`
}

func (q *Queries) CreateOutboundMessage(ctx context.Context, arg CreateOutboundMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createOutboundMessage,
		arg.OrganizationID,
		arg.Channel,
		arg.FromAddress,
		arg.ToAddress,
		arg.Body,
		arg.Media,
		arg.IdempotencyKey,
		arg.RequestHash,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CarrierConnectionID,
		&i.Channel,
		&i.Direction,
		&i.Status,
		&i.FromAddress,
		&i.ToAddress,
		&i.Body,
		&i.Media,
		&i.ProviderMessageID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.FailureCode,
		&i.FailureMessage,
		&i.QueuedAt,
		&i.SubmittedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReceivedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, organization_id, carrier_connection_id, channel, direction, status, from_address, to_address, body, media, provider_message_id, idempotency_key, request_hash, failure_code, failure_message, queued_at, submitted_at, sent_at, delivered_at, received_at, failed_at, created_at, updated_at
FROM messages
WHERE organization_id = $1
  AND id = $2
LIMIT 1
`

type GetMessageParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetMessage(ctx context.Context, arg GetMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, arg.OrganizationID, arg.ID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CarrierConnectionID,
		&i.Channel,
		&i.Direction,
		&i.Status,
		&i.FromAddress,
		&i.ToAddress,
		&i.Body,
		&i.Media,
		&i.ProviderMessageID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.FailureCode,
		&i.FailureMessage,
		&i.QueuedAt,
		&i.SubmittedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReceivedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessageByIdempotencyKey = `-- name: GetMessageByIdempotencyKey :one
SELECT id, organization_id, carrier_connection_id, channel, direction, status, from_address, to_address, body, media, provider_message_id, idempotency_key, request_hash, failure_code, failure_message, queued_at, submitted_at, sent_at, delivered_at, received_at, failed_at, created_at, updated_at
FROM messages
WHERE organization_id = $1
  AND idempotency_key = $2
LIMIT 1
`

type GetMessageByIdempotencyKeyParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	IdempotencyKey *string   `db:"idempotency_key" json:"idempotency_key"`
}

func (q *Queries) GetMessageByIdempotencyKey(ctx context.Context, arg GetMessageByIdempotencyKeyParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByIdempotencyKey, arg.OrganizationID, arg.IdempotencyKey)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CarrierConnectionID,
		&i.Channel,
		&i.Direction,
		&i.Status,
		&i.FromAddress,
		&i.ToAddress,
		&i.Body,
		&i.Media,
		&i.ProviderMessageID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.FailureCode,
		&i.FailureMessage,
		&i.QueuedAt,
		&i.SubmittedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReceivedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessageByProviderID = `-- name: GetMessageByProviderID :one
SELECT id, organization_id, carrier_connection_id, channel, direction, status, from_address, to_address, body, media, provider_message_id, idempotency_key, request_hash, failure_code, failure_message, queued_at, submitted_at, sent_at, delivered_at, received_at, failed_at, created_at, updated_at
FROM messages
WHERE carrier_connection_id = $1
  AND provider_message_id = $2
LIMIT 1
`

type GetMessageByProviderIDParams struct {
	CarrierConnectionID *uuid.UUID `db:"carrier_connection_id" json:"carrier_connection_id"`
	ProviderMessageID   *string    `db:"provider_message_id" json:"provider_message_id"`
}

func (q *Queries) GetMessageByProviderID(ctx context.Context, arg GetMessageByProviderIDParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByProviderID, arg.CarrierConnectionID, arg.ProviderMessageID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CarrierConnectionID,
		&i.Channel,
		&i.Direction,
		&i.Status,
		&i.FromAddress,
		&i.ToAddress,
		&i.Body,
		&i.Media,
		&i.ProviderMessageID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.FailureCode,
		&i.FailureMessage,
		&i.QueuedAt,
		&i.SubmittedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReceivedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, organization_id, carrier_connection_id, channel, direction, status, from_address, to_address, body, media, provider_message_id, idempotency_key, request_hash, failure_code, failure_message, queued_at, submitted_at, sent_at, delivered_at, received_at, failed_at, created_at, updated_at
FROM messages
WHERE organization_id = $1
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::text IS NULL OR direction = $3::text)
  AND ($4::text IS NULL OR channel = $4::text)
ORDER BY created_at DESC
LIMIT $6
OFFSET $5
`

type ListMessagesParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	Status         *string   `db:"status" json:"status"`
	Direction      *string   `db:"direction" json:"direction"`
	Channel        *string   `db:"channel" json:"channel"`
	PageOffset     int32     `db:"page_offset" json:"page_offset"`
	PageLimit      int32     `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages,
		arg.OrganizationID,
		arg.Status,
		arg.Direction,
		arg.Channel,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CarrierConnectionID,
			&i.Channel,
			&i.Direction,
			&i.Status,
			&i.FromAddress,
			&i.ToAddress,
			&i.Body,
			&i.Media,
			&i.ProviderMessageID,
			&i.IdempotencyKey,
			&i.RequestHash,
			&i.FailureCode,
			&i.FailureMessage,
			&i.QueuedAt,
			&i.SubmittedAt,
			&i.SentAt,
			&i.DeliveredAt,
			&i.ReceivedAt,
			&i.FailedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessageDelivered = `-- name: MarkMessageDelivered :one
UPDATE messages
SET
    status = 'delivered',
    delivered_at = COALESCE(delivered_at, NOW()),
    updated_at = NOW()
WHERE organization_id = $1
  AND id = $2
  AND direction = 'outbound'
  AND status IN ('submitted', 'sent')
RETURNING id, organization_id, carrier_connection_id, channel, direction, status, from_address, to_address, body, media, provider_message_id, idempotency_key, request_hash, failure_code, failure_message, queued_at, submitted_at, sent_at, delivered_at, received_at, failed_at, created_at, updated_at
`

type MarkMessageDeliveredParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkMessageDelivered(ctx context.Context, arg MarkMessageDeliveredParams) (Message, error) {
	row := q.db.QueryRow(ctx, markMessageDelivered, arg.OrganizationID, arg.ID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CarrierConnectionID,
		&i.Channel,
		&i.Direction,
		&i.Status,
		&i.FromAddress,
		&i.ToAddress,
		&i.Body,
		&i.Media,
		&i.ProviderMessageID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.FailureCode,
		&i.FailureMessage,
		&i.QueuedAt,
		&i.SubmittedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReceivedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markMessageFailed = `-- name: MarkMessageFailed :one
UPDATE messages
SET
    status = 'failed',
    failure_code = $1,
    failure_message = $2,
    failed_at = COALESCE(failed_at, NOW()),
    updated_at = NOW()
WHERE organization_id = $3
  AND id = $4
  AND direction = 'outbound'
  AND status IN ('queued', 'submitted', 'sent')
RETURNING id, organization_id, carrier_connection_id, channel, direction, status, from_address, to_address, body, media, provider_message_id, idempotency_key, request_hash, failure_code, failure_message, queued_at, submitted_at, sent_at, delivered_at, received_at, failed_at, created_at, updated_at
`

type MarkMessageFailedParams struct {
	FailureCode    *string   `db:"failure_code" json:"failure_code"`
	FailureMessage *string   `db:"failure_message" json:"failure_message"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkMessageFailed(ctx context.Context, arg MarkMessageFailedParams) (Message, error) {
	row := q.db.QueryRow(ctx, markMessageFailed,
		arg.FailureCode,
		arg.FailureMessage,
		arg.OrganizationID,
		arg.ID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CarrierConnectionID,
		&i.Channel,
		&i.Direction,
		&i.Status,
		&i.FromAddress,
		&i.ToAddress,
		&i.Body,
		&i.Media,
		&i.ProviderMessageID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.FailureCode,
		&i.FailureMessage,
		&i.QueuedAt,
		&i.SubmittedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReceivedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markMessageSent = `-- name: MarkMessageSent :one
UPDATE messages
SET
    status = 'sent',
    sent_at = COALESCE(sent_at, NOW()),
    updated_at = NOW()
WHERE organization_id = $1
  AND id = $2
  AND direction = 'outbound'
  AND status = 'submitted'
RETURNING id, organization_id, carrier_connection_id, channel, direction, status, from_address, to_address, body, media, provider_message_id, idempotency_key, request_hash, failure_code, failure_message, queued_at, submitted_at, sent_at, delivered_at, received_at, failed_at, created_at, updated_at
`

type MarkMessageSentParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkMessageSent(ctx context.Context, arg MarkMessageSentParams) (Message, error) {
	row := q.db.QueryRow(ctx, markMessageSent, arg.OrganizationID, arg.ID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CarrierConnectionID,
		&i.Channel,
		&i.Direction,
		&i.Status,
		&i.FromAddress,
		&i.ToAddress,
		&i.Body,
		&i.Media,
		&i.ProviderMessageID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.FailureCode,
		&i.FailureMessage,
		&i.QueuedAt,
		&i.SubmittedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReceivedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markMessageSubmitted = `-- name: MarkMessageSubmitted :one
UPDATE messages
SET
    status = 'submitted',
    provider_message_id = $1,
    submitted_at = COALESCE(submitted_at, NOW()),
    updated_at = NOW()
WHERE organization_id = $2
  AND id = $3
  AND direction = 'outbound'
  AND status = 'queued'
  AND carrier_connection_id IS NOT NULL
  AND provider_message_id IS NULL
RETURNING id, organization_id, carrier_connection_id, channel, direction, status, from_address, to_address, body, media, provider_message_id, idempotency_key, request_hash, failure_code, failure_message, queued_at, submitted_at, sent_at, delivered_at, received_at, failed_at, created_at, updated_at
`

type MarkMessageSubmittedParams struct {
	ProviderMessageID *string   `db:"provider_message_id" json:"provider_message_id"`
	OrganizationID    uuid.UUID `db:"organization_id" json:"organization_id"`
	ID                uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkMessageSubmitted(ctx context.Context, arg MarkMessageSubmittedParams) (Message, error) {
	row := q.db.QueryRow(ctx, markMessageSubmitted, arg.ProviderMessageID, arg.OrganizationID, arg.ID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CarrierConnectionID,
		&i.Channel,
		&i.Direction,
		&i.Status,
		&i.FromAddress,
		&i.ToAddress,
		&i.Body,
		&i.Media,
		&i.ProviderMessageID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.FailureCode,
		&i.FailureMessage,
		&i.QueuedAt,
		&i.SubmittedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReceivedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markMessageUndelivered = `-- name: MarkMessageUndelivered :one
UPDATE messages
SET
    status = 'undelivered',
    failure_code = $1,
    failure_message = $2,
    failed_at = COALESCE(failed_at, NOW()),
    updated_at = NOW()
WHERE organization_id = $3
  AND id = $4
  AND direction = 'outbound'
  AND status IN ('submitted', 'sent')
RETURNING id, organization_id, carrier_connection_id, channel, direction, status, from_address, to_address, body, media, provider_message_id, idempotency_key, request_hash, failure_code, failure_message, queued_at, submitted_at, sent_at, delivered_at, received_at, failed_at, created_at, updated_at
`

type MarkMessageUndeliveredParams struct {
	FailureCode    *string   `db:"failure_code" json:"failure_code"`
	FailureMessage *string   `db:"failure_message" json:"failure_message"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkMessageUndelivered(ctx context.Context, arg MarkMessageUndeliveredParams) (Message, error) {
	row := q.db.QueryRow(ctx, markMessageUndelivered,
		arg.FailureCode,
		arg.FailureMessage,
		arg.OrganizationID,
		arg.ID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CarrierConnectionID,
		&i.Channel,
		&i.Direction,
		&i.Status,
		&i.FromAddress,
		&i.ToAddress,
		&i.Body,
		&i.Media,
		&i.ProviderMessageID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.FailureCode,
		&i.FailureMessage,
		&i.QueuedAt,
		&i.SubmittedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReceivedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setMessageProviderAttribution = `-- name: SetMessageProviderAttribution :one
UPDATE messages AS message
SET
    carrier_connection_id = connection.id,
    updated_at = NOW()
FROM carrier_connections AS connection
JOIN organizations AS organization
  ON organization.id = $1
WHERE message.organization_id = $1
  AND message.id = $2
  AND message.direction = 'outbound'
  AND message.status = 'queued'
  AND connection.id = $3
  AND connection.status = 'active'
  AND organization.status = 'active'
  AND organization.deleted_at IS NULL
  AND (
      (
          connection.scope = 'organization'
          AND connection.organization_id = message.organization_id
      )
      OR (
          connection.scope = 'platform'
          AND connection.organization_id IS NULL
      )
  )
  AND (
      message.carrier_connection_id IS NULL
      OR message.carrier_connection_id = connection.id
  )
RETURNING message.id, message.organization_id, message.carrier_connection_id, message.channel, message.direction, message.status, message.from_address, message.to_address, message.body, message.media, message.provider_message_id, message.idempotency_key, message.request_hash, message.failure_code, message.failure_message, message.queued_at, message.submitted_at, message.sent_at, message.delivered_at, message.received_at, message.failed_at, message.created_at, message.updated_at
`

type SetMessageProviderAttributionParams struct {
	OrganizationID      uuid.UUID `db:"organization_id" json:"organization_id"`
	ID                  uuid.UUID `db:"id" json:"id"`
	CarrierConnectionID uuid.UUID `db:"carrier_connection_id" json:"carrier_connection_id"`
}

func (q *Queries) SetMessageProviderAttribution(ctx context.Context, arg SetMessageProviderAttributionParams) (Message, error) {
	row := q.db.QueryRow(ctx, setMessageProviderAttribution, arg.OrganizationID, arg.ID, arg.CarrierConnectionID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CarrierConnectionID,
		&i.Channel,
		&i.Direction,
		&i.Status,
		&i.FromAddress,
		&i.ToAddress,
		&i.Body,
		&i.Media,
		&i.ProviderMessageID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.FailureCode,
		&i.FailureMessage,
		&i.QueuedAt,
		&i.SubmittedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReceivedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
