// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: number_lifecycle.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateEmergencyRegistration = `-- name: ActivateEmergencyRegistration :one
UPDATE emergency_registrations
SET status = 'active', provider_reference = $1,
    validation_message = NULL, activated_at = now()
WHERE id = $2 AND status IN ('pending', 'validating')
RETURNING id, organization_id, phone_number_id, provider_id, status, name, address_line1, address_line2, locality, region, postal_code, country_code, provider_reference, validation_message, activated_at, deactivated_at, created_at, updated_at, idempotency_key, request_hash, reconcile_after, reconcile_attempts
`

type ActivateEmergencyRegistrationParams struct {
	ProviderReference *string   `db:"provider_reference" json:"provider_reference"`
	ID                uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) ActivateEmergencyRegistration(ctx context.Context, arg ActivateEmergencyRegistrationParams) (EmergencyRegistration, error) {
	row := q.db.QueryRow(ctx, activateEmergencyRegistration, arg.ProviderReference, arg.ID)
	var i EmergencyRegistration
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PhoneNumberID,
		&i.ProviderID,
		&i.Status,
		&i.Name,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Locality,
		&i.Region,
		&i.PostalCode,
		&i.CountryCode,
		&i.ProviderReference,
		&i.ValidationMessage,
		&i.ActivatedAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ReconcileAfter,
		&i.ReconcileAttempts,
	)
	return i, err
}

const activatePortInCase = `-- name: ActivatePortInCase :one
UPDATE port_in_cases
SET status = 'activated', activated_at = now()
WHERE id = $1
  AND status IN ('submitted', 'in_progress', 'foc_received')
RETURNING id, organization_id, lifecycle_operation_id, losing_carrier, account_number, account_pin_ciphertext, authorized_name, service_address, desired_port_date, status, provider_case_reference, rejection_code, rejection_message, foc_at, activated_at, created_at, updated_at
`

func (q *Queries) ActivatePortInCase(ctx context.Context, id uuid.UUID) (PortInCase, error) {
	row := q.db.QueryRow(ctx, activatePortInCase, id)
	var i PortInCase
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.LifecycleOperationID,
		&i.LosingCarrier,
		&i.AccountNumber,
		&i.AccountPinCiphertext,
		&i.AuthorizedName,
		&i.ServiceAddress,
		&i.DesiredPortDate,
		&i.Status,
		&i.ProviderCaseReference,
		&i.RejectionCode,
		&i.RejectionMessage,
		&i.FocAt,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addPortInDocument = `-- name: AddPortInDocument :one
INSERT INTO port_in_documents (
    organization_id, port_in_case_id, document_type, object_key, sha256
) VALUES (
    $1, $2, $3,
    $4, $5
)
RETURNING id, organization_id, port_in_case_id, document_type, object_key, sha256, status, provider_reference, created_at, updated_at
`

type AddPortInDocumentParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	PortInCaseID   uuid.UUID `db:"port_in_case_id" json:"port_in_case_id"`
	DocumentType   string    `db:"document_type" json:"document_type"`
	ObjectKey      string    `db:"object_key" json:"object_key"`
	Sha256         string    `db:"sha256" json:"sha256"`
}

func (q *Queries) AddPortInDocument(ctx context.Context, arg AddPortInDocumentParams) (PortInDocument, error) {
	row := q.db.QueryRow(ctx, addPortInDocument,
		arg.OrganizationID,
		arg.PortInCaseID,
		arg.DocumentType,
		arg.ObjectKey,
		arg.Sha256,
	)
	var i PortInDocument
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PortInCaseID,
		&i.DocumentType,
		&i.ObjectKey,
		&i.Sha256,
		&i.Status,
		&i.ProviderReference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimPortInSubmission = `-- name: ClaimPortInSubmission :one
UPDATE number_lifecycle_operations
SET status = 'submitted',
    submitted_at = now(),
    reconcile_after = now() + interval '2 minutes',
    reconcile_attempts = reconcile_attempts + 1
WHERE id = $1
  AND operation = 'port_in'
  AND status = 'pending'
  AND provider_reference IS NULL
RETURNING id, organization_id, phone_number_id, provider_id, idempotency_key, operation, status, provider_reference, requested_number, request_payload, failure_code, failure_message, submitted_at, completed_at, created_at, updated_at, reconcile_after, reconcile_attempts
`

func (q *Queries) ClaimPortInSubmission(ctx context.Context, id uuid.UUID) (NumberLifecycleOperation, error) {
	row := q.db.QueryRow(ctx, claimPortInSubmission, id)
	var i NumberLifecycleOperation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PhoneNumberID,
		&i.ProviderID,
		&i.IdempotencyKey,
		&i.Operation,
		&i.Status,
		&i.ProviderReference,
		&i.RequestedNumber,
		&i.RequestPayload,
		&i.FailureCode,
		&i.FailureMessage,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReconcileAfter,
		&i.ReconcileAttempts,
	)
	return i, err
}

const completeNumberLifecycleOperation = `-- name: CompleteNumberLifecycleOperation :one
UPDATE number_lifecycle_operations
SET status = 'completed', completed_at = now(), failure_code = NULL, failure_message = NULL
WHERE id = $1 AND status IN ('pending', 'submitted', 'in_progress')
RETURNING id, organization_id, phone_number_id, provider_id, idempotency_key, operation, status, provider_reference, requested_number, request_payload, failure_code, failure_message, submitted_at, completed_at, created_at, updated_at, reconcile_after, reconcile_attempts
`

func (q *Queries) CompleteNumberLifecycleOperation(ctx context.Context, id uuid.UUID) (NumberLifecycleOperation, error) {
	row := q.db.QueryRow(ctx, completeNumberLifecycleOperation, id)
	var i NumberLifecycleOperation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PhoneNumberID,
		&i.ProviderID,
		&i.IdempotencyKey,
		&i.Operation,
		&i.Status,
		&i.ProviderReference,
		&i.RequestedNumber,
		&i.RequestPayload,
		&i.FailureCode,
		&i.FailureMessage,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReconcileAfter,
		&i.ReconcileAttempts,
	)
	return i, err
}

const createEmergencyRegistration = `-- name: CreateEmergencyRegistration :one
INSERT INTO emergency_registrations (
    organization_id, phone_number_id, provider_id, idempotency_key, request_hash,
    name, address_line1, address_line2, locality, region, postal_code, country_code
)
SELECT pn.organization_id, pn.id, pn.provider_id, $1, $2,
       $3, $4, $5,
       $6, $7, $8, $9
FROM phone_numbers AS pn
WHERE pn.id = $10
  AND pn.organization_id = $11
  AND pn.provisioning_mode = 'managed'
  AND pn.status = 'active'
  AND pn.provider_id IS NOT NULL
ON CONFLICT (organization_id, idempotency_key) DO NOTHING
RETURNING id, organization_id, phone_number_id, provider_id, status, name, address_line1, address_line2, locality, region, postal_code, country_code, provider_reference, validation_message, activated_at, deactivated_at, created_at, updated_at, idempotency_key, request_hash, reconcile_after, reconcile_attempts
`

type CreateEmergencyRegistrationParams struct {
	IdempotencyKey *string   `db:"idempotency_key" json:"idempotency_key"`
	RequestHash    *string   `db:"request_hash" json:"request_hash"`
	Name           string    `db:"name" json:"name"`
	AddressLine1   string    `db:"address_line1" json:"address_line1"`
	AddressLine2   *string   `db:"address_line2" json:"address_line2"`
	Locality       string    `db:"locality" json:"locality"`
	Region         string    `db:"region" json:"region"`
	PostalCode     string    `db:"postal_code" json:"postal_code"`
	CountryCode    string    `db:"country_code" json:"country_code"`
	PhoneNumberID  uuid.UUID `db:"phone_number_id" json:"phone_number_id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) CreateEmergencyRegistration(ctx context.Context, arg CreateEmergencyRegistrationParams) (EmergencyRegistration, error) {
	row := q.db.QueryRow(ctx, createEmergencyRegistration,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.Name,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.Locality,
		arg.Region,
		arg.PostalCode,
		arg.CountryCode,
		arg.PhoneNumberID,
		arg.OrganizationID,
	)
	var i EmergencyRegistration
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PhoneNumberID,
		&i.ProviderID,
		&i.Status,
		&i.Name,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Locality,
		&i.Region,
		&i.PostalCode,
		&i.CountryCode,
		&i.ProviderReference,
		&i.ValidationMessage,
		&i.ActivatedAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ReconcileAfter,
		&i.ReconcileAttempts,
	)
	return i, err
}

const createManagedReleaseOperation = `-- name: CreateManagedReleaseOperation :one
INSERT INTO number_lifecycle_operations (
    organization_id, phone_number_id, provider_id, idempotency_key,
    operation, requested_number, request_payload
)
SELECT pn.organization_id, pn.id, pn.provider_id, $1,
       'release', pn.number, '{}'::JSONB
FROM phone_numbers AS pn
WHERE pn.id = $2
  AND pn.organization_id = $3
  AND pn.provisioning_mode = 'managed'
  AND pn.provider_id IS NOT NULL
  AND pn.provider_resource_id IS NOT NULL
  AND pn.status IN ('active', 'disabled')
ON CONFLICT (organization_id, idempotency_key) DO NOTHING
RETURNING id, organization_id, phone_number_id, provider_id, idempotency_key, operation, status, provider_reference, requested_number, request_payload, failure_code, failure_message, submitted_at, completed_at, created_at, updated_at, reconcile_after, reconcile_attempts
`

type CreateManagedReleaseOperationParams struct {
	IdempotencyKey string    `db:"idempotency_key" json:"idempotency_key"`
	PhoneNumberID  uuid.UUID `db:"phone_number_id" json:"phone_number_id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) CreateManagedReleaseOperation(ctx context.Context, arg CreateManagedReleaseOperationParams) (NumberLifecycleOperation, error) {
	row := q.db.QueryRow(ctx, createManagedReleaseOperation, arg.IdempotencyKey, arg.PhoneNumberID, arg.OrganizationID)
	var i NumberLifecycleOperation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PhoneNumberID,
		&i.ProviderID,
		&i.IdempotencyKey,
		&i.Operation,
		&i.Status,
		&i.ProviderReference,
		&i.RequestedNumber,
		&i.RequestPayload,
		&i.FailureCode,
		&i.FailureMessage,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReconcileAfter,
		&i.ReconcileAttempts,
	)
	return i, err
}

const createPortInCase = `-- name: CreatePortInCase :one
INSERT INTO port_in_cases (
    organization_id, lifecycle_operation_id, losing_carrier, account_number,
    authorized_name, service_address, desired_port_date
) VALUES (
    $1, $2, $3,
    $4, $5, $6::JSONB,
    $7
)
RETURNING id, organization_id, lifecycle_operation_id, losing_carrier, account_number, account_pin_ciphertext, authorized_name, service_address, desired_port_date, status, provider_case_reference, rejection_code, rejection_message, foc_at, activated_at, created_at, updated_at
`

type CreatePortInCaseParams struct {
	OrganizationID       uuid.UUID   `db:"organization_id" json:"organization_id"`
	LifecycleOperationID uuid.UUID   `db:"lifecycle_operation_id" json:"lifecycle_operation_id"`
	LosingCarrier        string      `db:"losing_carrier" json:"losing_carrier"`
	AccountNumber        string      `db:"account_number" json:"account_number"`
	AuthorizedName       string      `db:"authorized_name" json:"authorized_name"`
	ServiceAddress       []byte      `db:"service_address" json:"service_address"`
	DesiredPortDate      pgtype.Date `db:"desired_port_date" json:"desired_port_date"`
}

func (q *Queries) CreatePortInCase(ctx context.Context, arg CreatePortInCaseParams) (PortInCase, error) {
	row := q.db.QueryRow(ctx, createPortInCase,
		arg.OrganizationID,
		arg.LifecycleOperationID,
		arg.LosingCarrier,
		arg.AccountNumber,
		arg.AuthorizedName,
		arg.ServiceAddress,
		arg.DesiredPortDate,
	)
	var i PortInCase
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.LifecycleOperationID,
		&i.LosingCarrier,
		&i.AccountNumber,
		&i.AccountPinCiphertext,
		&i.AuthorizedName,
		&i.ServiceAddress,
		&i.DesiredPortDate,
		&i.Status,
		&i.ProviderCaseReference,
		&i.RejectionCode,
		&i.RejectionMessage,
		&i.FocAt,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPortInOperation = `-- name: CreatePortInOperation :one
INSERT INTO number_lifecycle_operations (
    organization_id, provider_id, idempotency_key, operation, requested_number, request_payload
)
SELECT $1, cp.id, $2, 'port_in',
       $3, $4::JSONB
FROM carrier_providers AS cp
JOIN organizations AS o ON o.id = $1
WHERE cp.slug = 'didww' AND cp.status = 'active'
  AND o.status = 'active' AND o.deleted_at IS NULL
ON CONFLICT (organization_id, idempotency_key) DO NOTHING
RETURNING id, organization_id, phone_number_id, provider_id, idempotency_key, operation, status, provider_reference, requested_number, request_payload, failure_code, failure_message, submitted_at, completed_at, created_at, updated_at, reconcile_after, reconcile_attempts
`

type CreatePortInOperationParams struct {
	OrganizationID  uuid.UUID `db:"organization_id" json:"organization_id"`
	IdempotencyKey  string    `db:"idempotency_key" json:"idempotency_key"`
	RequestedNumber string    `db:"requested_number" json:"requested_number"`
	RequestPayload  []byte    `db:"request_payload" json:"request_payload"`
}

func (q *Queries) CreatePortInOperation(ctx context.Context, arg CreatePortInOperationParams) (NumberLifecycleOperation, error) {
	row := q.db.QueryRow(ctx, createPortInOperation,
		arg.OrganizationID,
		arg.IdempotencyKey,
		arg.RequestedNumber,
		arg.RequestPayload,
	)
	var i NumberLifecycleOperation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PhoneNumberID,
		&i.ProviderID,
		&i.IdempotencyKey,
		&i.Operation,
		&i.Status,
		&i.ProviderReference,
		&i.RequestedNumber,
		&i.RequestPayload,
		&i.FailureCode,
		&i.FailureMessage,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReconcileAfter,
		&i.ReconcileAttempts,
	)
	return i, err
}

const deactivateCurrentEmergencyRegistration = `-- name: DeactivateCurrentEmergencyRegistration :exec
UPDATE emergency_registrations
SET status = 'deactivated', deactivated_at = now()
WHERE organization_id = $1
  AND phone_number_id = $2
  AND status = 'active'
`

type DeactivateCurrentEmergencyRegistrationParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	PhoneNumberID  uuid.UUID `db:"phone_number_id" json:"phone_number_id"`
}

func (q *Queries) DeactivateCurrentEmergencyRegistration(ctx context.Context, arg DeactivateCurrentEmergencyRegistrationParams) error {
	_, err := q.db.Exec(ctx, deactivateCurrentEmergencyRegistration, arg.OrganizationID, arg.PhoneNumberID)
	return err
}

const failNumberLifecycleOperation = `-- name: FailNumberLifecycleOperation :one
UPDATE number_lifecycle_operations
SET status = 'failed', failure_code = $1,
    failure_message = $2
WHERE id = $3 AND status IN ('pending', 'submitted', 'in_progress')
RETURNING id, organization_id, phone_number_id, provider_id, idempotency_key, operation, status, provider_reference, requested_number, request_payload, failure_code, failure_message, submitted_at, completed_at, created_at, updated_at, reconcile_after, reconcile_attempts
`

type FailNumberLifecycleOperationParams struct {
	FailureCode    *string   `db:"failure_code" json:"failure_code"`
	FailureMessage *string   `db:"failure_message" json:"failure_message"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) FailNumberLifecycleOperation(ctx context.Context, arg FailNumberLifecycleOperationParams) (NumberLifecycleOperation, error) {
	row := q.db.QueryRow(ctx, failNumberLifecycleOperation, arg.FailureCode, arg.FailureMessage, arg.ID)
	var i NumberLifecycleOperation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PhoneNumberID,
		&i.ProviderID,
		&i.IdempotencyKey,
		&i.Operation,
		&i.Status,
		&i.ProviderReference,
		&i.RequestedNumber,
		&i.RequestPayload,
		&i.FailureCode,
		&i.FailureMessage,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReconcileAfter,
		&i.ReconcileAttempts,
	)
	return i, err
}

const getCurrentEmergencyRegistration = `-- name: GetCurrentEmergencyRegistration :one
SELECT id, organization_id, phone_number_id, provider_id, status, name, address_line1, address_line2, locality, region, postal_code, country_code, provider_reference, validation_message, activated_at, deactivated_at, created_at, updated_at, idempotency_key, request_hash, reconcile_after, reconcile_attempts FROM emergency_registrations
WHERE organization_id = $1
  AND phone_number_id = $2
  AND status IN ('pending', 'validating', 'active')
ORDER BY CASE WHEN status = 'active' THEN 0 ELSE 1 END,
         created_at DESC
LIMIT 1
`

type GetCurrentEmergencyRegistrationParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	PhoneNumberID  uuid.UUID `db:"phone_number_id" json:"phone_number_id"`
}

func (q *Queries) GetCurrentEmergencyRegistration(ctx context.Context, arg GetCurrentEmergencyRegistrationParams) (EmergencyRegistration, error) {
	row := q.db.QueryRow(ctx, getCurrentEmergencyRegistration, arg.OrganizationID, arg.PhoneNumberID)
	var i EmergencyRegistration
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PhoneNumberID,
		&i.ProviderID,
		&i.Status,
		&i.Name,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Locality,
		&i.Region,
		&i.PostalCode,
		&i.CountryCode,
		&i.ProviderReference,
		&i.ValidationMessage,
		&i.ActivatedAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ReconcileAfter,
		&i.ReconcileAttempts,
	)
	return i, err
}

const getEmergencyRegistrationByKey = `-- name: GetEmergencyRegistrationByKey :one
SELECT id, organization_id, phone_number_id, provider_id, status, name, address_line1, address_line2, locality, region, postal_code, country_code, provider_reference, validation_message, activated_at, deactivated_at, created_at, updated_at, idempotency_key, request_hash, reconcile_after, reconcile_attempts FROM emergency_registrations
WHERE organization_id = $1
  AND idempotency_key = $2
`

type GetEmergencyRegistrationByKeyParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	IdempotencyKey *string   `db:"idempotency_key" json:"idempotency_key"`
}

func (q *Queries) GetEmergencyRegistrationByKey(ctx context.Context, arg GetEmergencyRegistrationByKeyParams) (EmergencyRegistration, error) {
	row := q.db.QueryRow(ctx, getEmergencyRegistrationByKey, arg.OrganizationID, arg.IdempotencyKey)
	var i EmergencyRegistration
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PhoneNumberID,
		&i.ProviderID,
		&i.Status,
		&i.Name,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Locality,
		&i.Region,
		&i.PostalCode,
		&i.CountryCode,
		&i.ProviderReference,
		&i.ValidationMessage,
		&i.ActivatedAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ReconcileAfter,
		&i.ReconcileAttempts,
	)
	return i, err
}

const getNumberLifecycleOperation = `-- name: GetNumberLifecycleOperation :one
SELECT id, organization_id, phone_number_id, provider_id, idempotency_key, operation, status, provider_reference, requested_number, request_payload, failure_code, failure_message, submitted_at, completed_at, created_at, updated_at, reconcile_after, reconcile_attempts FROM number_lifecycle_operations
WHERE id = $1 AND organization_id = $2
`

type GetNumberLifecycleOperationParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetNumberLifecycleOperation(ctx context.Context, arg GetNumberLifecycleOperationParams) (NumberLifecycleOperation, error) {
	row := q.db.QueryRow(ctx, getNumberLifecycleOperation, arg.ID, arg.OrganizationID)
	var i NumberLifecycleOperation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PhoneNumberID,
		&i.ProviderID,
		&i.IdempotencyKey,
		&i.Operation,
		&i.Status,
		&i.ProviderReference,
		&i.RequestedNumber,
		&i.RequestPayload,
		&i.FailureCode,
		&i.FailureMessage,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReconcileAfter,
		&i.ReconcileAttempts,
	)
	return i, err
}

const getNumberLifecycleOperationByKey = `-- name: GetNumberLifecycleOperationByKey :one
SELECT id, organization_id, phone_number_id, provider_id, idempotency_key, operation, status, provider_reference, requested_number, request_payload, failure_code, failure_message, submitted_at, completed_at, created_at, updated_at, reconcile_after, reconcile_attempts FROM number_lifecycle_operations
WHERE organization_id = $1
  AND idempotency_key = $2
`

type GetNumberLifecycleOperationByKeyParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	IdempotencyKey string    `db:"idempotency_key" json:"idempotency_key"`
}

func (q *Queries) GetNumberLifecycleOperationByKey(ctx context.Context, arg GetNumberLifecycleOperationByKeyParams) (NumberLifecycleOperation, error) {
	row := q.db.QueryRow(ctx, getNumberLifecycleOperationByKey, arg.OrganizationID, arg.IdempotencyKey)
	var i NumberLifecycleOperation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PhoneNumberID,
		&i.ProviderID,
		&i.IdempotencyKey,
		&i.Operation,
		&i.Status,
		&i.ProviderReference,
		&i.RequestedNumber,
		&i.RequestPayload,
		&i.FailureCode,
		&i.FailureMessage,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReconcileAfter,
		&i.ReconcileAttempts,
	)
	return i, err
}

const getPortInCase = `-- name: GetPortInCase :one
SELECT pc.id, pc.organization_id, pc.lifecycle_operation_id, pc.losing_carrier, pc.account_number, pc.account_pin_ciphertext, pc.authorized_name, pc.service_address, pc.desired_port_date, pc.status, pc.provider_case_reference, pc.rejection_code, pc.rejection_message, pc.foc_at, pc.activated_at, pc.created_at, pc.updated_at FROM port_in_cases AS pc
WHERE pc.id = $1 AND pc.organization_id = $2
`

type GetPortInCaseParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetPortInCase(ctx context.Context, arg GetPortInCaseParams) (PortInCase, error) {
	row := q.db.QueryRow(ctx, getPortInCase, arg.ID, arg.OrganizationID)
	var i PortInCase
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.LifecycleOperationID,
		&i.LosingCarrier,
		&i.AccountNumber,
		&i.AccountPinCiphertext,
		&i.AuthorizedName,
		&i.ServiceAddress,
		&i.DesiredPortDate,
		&i.Status,
		&i.ProviderCaseReference,
		&i.RejectionCode,
		&i.RejectionMessage,
		&i.FocAt,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPortInCaseByOperation = `-- name: GetPortInCaseByOperation :one
SELECT id, organization_id, lifecycle_operation_id, losing_carrier, account_number, account_pin_ciphertext, authorized_name, service_address, desired_port_date, status, provider_case_reference, rejection_code, rejection_message, foc_at, activated_at, created_at, updated_at FROM port_in_cases WHERE lifecycle_operation_id = $1
`

func (q *Queries) GetPortInCaseByOperation(ctx context.Context, lifecycleOperationID uuid.UUID) (PortInCase, error) {
	row := q.db.QueryRow(ctx, getPortInCaseByOperation, lifecycleOperationID)
	var i PortInCase
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.LifecycleOperationID,
		&i.LosingCarrier,
		&i.AccountNumber,
		&i.AccountPinCiphertext,
		&i.AuthorizedName,
		&i.ServiceAddress,
		&i.DesiredPortDate,
		&i.Status,
		&i.ProviderCaseReference,
		&i.RejectionCode,
		&i.RejectionMessage,
		&i.FocAt,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmergencyRegistrationsDue = `-- name: ListEmergencyRegistrationsDue :many
SELECT id, organization_id, phone_number_id, provider_id, status, name, address_line1, address_line2, locality, region, postal_code, country_code, provider_reference, validation_message, activated_at, deactivated_at, created_at, updated_at, idempotency_key, request_hash, reconcile_after, reconcile_attempts FROM emergency_registrations
WHERE status IN ('pending', 'validating') AND reconcile_after <= now()
ORDER BY reconcile_after, created_at LIMIT $1
`

func (q *Queries) ListEmergencyRegistrationsDue(ctx context.Context, batchSize int32) ([]EmergencyRegistration, error) {
	rows, err := q.db.Query(ctx, listEmergencyRegistrationsDue, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmergencyRegistration{}
	for rows.Next() {
		var i EmergencyRegistration
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PhoneNumberID,
			&i.ProviderID,
			&i.Status,
			&i.Name,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.Locality,
			&i.Region,
			&i.PostalCode,
			&i.CountryCode,
			&i.ProviderReference,
			&i.ValidationMessage,
			&i.ActivatedAt,
			&i.DeactivatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IdempotencyKey,
			&i.RequestHash,
			&i.ReconcileAfter,
			&i.ReconcileAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNumberLifecycleOperationsDue = `-- name: ListNumberLifecycleOperationsDue :many
SELECT id, organization_id, phone_number_id, provider_id, idempotency_key, operation, status, provider_reference, requested_number, request_payload, failure_code, failure_message, submitted_at, completed_at, created_at, updated_at, reconcile_after, reconcile_attempts FROM number_lifecycle_operations
WHERE status IN ('pending', 'submitted', 'in_progress')
  AND reconcile_after <= now()
ORDER BY reconcile_after, created_at
LIMIT $1
`

func (q *Queries) ListNumberLifecycleOperationsDue(ctx context.Context, batchSize int32) ([]NumberLifecycleOperation, error) {
	rows, err := q.db.Query(ctx, listNumberLifecycleOperationsDue, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NumberLifecycleOperation{}
	for rows.Next() {
		var i NumberLifecycleOperation
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PhoneNumberID,
			&i.ProviderID,
			&i.IdempotencyKey,
			&i.Operation,
			&i.Status,
			&i.ProviderReference,
			&i.RequestedNumber,
			&i.RequestPayload,
			&i.FailureCode,
			&i.FailureMessage,
			&i.SubmittedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReconcileAfter,
			&i.ReconcileAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortInDocuments = `-- name: ListPortInDocuments :many
SELECT id, organization_id, port_in_case_id, document_type, object_key, sha256, status, provider_reference, created_at, updated_at FROM port_in_documents
WHERE organization_id = $1 AND port_in_case_id = $2
ORDER BY created_at
`

type ListPortInDocumentsParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	PortInCaseID   uuid.UUID `db:"port_in_case_id" json:"port_in_case_id"`
}

func (q *Queries) ListPortInDocuments(ctx context.Context, arg ListPortInDocumentsParams) ([]PortInDocument, error) {
	rows, err := q.db.Query(ctx, listPortInDocuments, arg.OrganizationID, arg.PortInCaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PortInDocument{}
	for rows.Next() {
		var i PortInDocument
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PortInCaseID,
			&i.DocumentType,
			&i.ObjectKey,
			&i.Sha256,
			&i.Status,
			&i.ProviderReference,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmergencyRegistrationValidating = `-- name: MarkEmergencyRegistrationValidating :one
UPDATE emergency_registrations
SET status = 'validating', provider_reference = COALESCE($1, provider_reference),
    validation_message = $2, reconcile_after = $3,
    reconcile_attempts = reconcile_attempts + 1
WHERE id = $4 AND status IN ('pending', 'validating')
RETURNING id, organization_id, phone_number_id, provider_id, status, name, address_line1, address_line2, locality, region, postal_code, country_code, provider_reference, validation_message, activated_at, deactivated_at, created_at, updated_at, idempotency_key, request_hash, reconcile_after, reconcile_attempts
`

type MarkEmergencyRegistrationValidatingParams struct {
	ProviderReference *string            `db:"provider_reference" json:"provider_reference"`
	ValidationMessage *string            `db:"validation_message" json:"validation_message"`
	ReconcileAfter    pgtype.Timestamptz `db:"reconcile_after" json:"reconcile_after"`
	ID                uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) MarkEmergencyRegistrationValidating(ctx context.Context, arg MarkEmergencyRegistrationValidatingParams) (EmergencyRegistration, error) {
	row := q.db.QueryRow(ctx, markEmergencyRegistrationValidating,
		arg.ProviderReference,
		arg.ValidationMessage,
		arg.ReconcileAfter,
		arg.ID,
	)
	var i EmergencyRegistration
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PhoneNumberID,
		&i.ProviderID,
		&i.Status,
		&i.Name,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Locality,
		&i.Region,
		&i.PostalCode,
		&i.CountryCode,
		&i.ProviderReference,
		&i.ValidationMessage,
		&i.ActivatedAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ReconcileAfter,
		&i.ReconcileAttempts,
	)
	return i, err
}

const markNumberLifecycleSubmitted = `-- name: MarkNumberLifecycleSubmitted :one
UPDATE number_lifecycle_operations
SET status = 'submitted',
    provider_reference = COALESCE($1, provider_reference),
    submitted_at = COALESCE(submitted_at, now()),
    reconcile_after = $2,
    reconcile_attempts = reconcile_attempts + 1
WHERE id = $3
  AND status IN ('pending', 'submitted', 'in_progress')
RETURNING id, organization_id, phone_number_id, provider_id, idempotency_key, operation, status, provider_reference, requested_number, request_payload, failure_code, failure_message, submitted_at, completed_at, created_at, updated_at, reconcile_after, reconcile_attempts
`

type MarkNumberLifecycleSubmittedParams struct {
	ProviderReference *string            `db:"provider_reference" json:"provider_reference"`
	ReconcileAfter    pgtype.Timestamptz `db:"reconcile_after" json:"reconcile_after"`
	ID                uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) MarkNumberLifecycleSubmitted(ctx context.Context, arg MarkNumberLifecycleSubmittedParams) (NumberLifecycleOperation, error) {
	row := q.db.QueryRow(ctx, markNumberLifecycleSubmitted, arg.ProviderReference, arg.ReconcileAfter, arg.ID)
	var i NumberLifecycleOperation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PhoneNumberID,
		&i.ProviderID,
		&i.IdempotencyKey,
		&i.Operation,
		&i.Status,
		&i.ProviderReference,
		&i.RequestedNumber,
		&i.RequestPayload,
		&i.FailureCode,
		&i.FailureMessage,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReconcileAfter,
		&i.ReconcileAttempts,
	)
	return i, err
}

const markPortInDocumentsRequired = `-- name: MarkPortInDocumentsRequired :one
UPDATE port_in_cases SET status = 'documents_required'
WHERE id = $1 AND status IN ('draft', 'checking_portability')
RETURNING id, organization_id, lifecycle_operation_id, losing_carrier, account_number, account_pin_ciphertext, authorized_name, service_address, desired_port_date, status, provider_case_reference, rejection_code, rejection_message, foc_at, activated_at, created_at, updated_at
`

func (q *Queries) MarkPortInDocumentsRequired(ctx context.Context, id uuid.UUID) (PortInCase, error) {
	row := q.db.QueryRow(ctx, markPortInDocumentsRequired, id)
	var i PortInCase
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.LifecycleOperationID,
		&i.LosingCarrier,
		&i.AccountNumber,
		&i.AccountPinCiphertext,
		&i.AuthorizedName,
		&i.ServiceAddress,
		&i.DesiredPortDate,
		&i.Status,
		&i.ProviderCaseReference,
		&i.RejectionCode,
		&i.RejectionMessage,
		&i.FocAt,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPortInFOC = `-- name: MarkPortInFOC :one
UPDATE port_in_cases SET status = 'foc_received', foc_at = $1
WHERE id = $2 AND status IN ('submitted', 'in_progress')
RETURNING id, organization_id, lifecycle_operation_id, losing_carrier, account_number, account_pin_ciphertext, authorized_name, service_address, desired_port_date, status, provider_case_reference, rejection_code, rejection_message, foc_at, activated_at, created_at, updated_at
`

type MarkPortInFOCParams struct {
	FocAt pgtype.Timestamptz `db:"foc_at" json:"foc_at"`
	ID    uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) MarkPortInFOC(ctx context.Context, arg MarkPortInFOCParams) (PortInCase, error) {
	row := q.db.QueryRow(ctx, markPortInFOC, arg.FocAt, arg.ID)
	var i PortInCase
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.LifecycleOperationID,
		&i.LosingCarrier,
		&i.AccountNumber,
		&i.AccountPinCiphertext,
		&i.AuthorizedName,
		&i.ServiceAddress,
		&i.DesiredPortDate,
		&i.Status,
		&i.ProviderCaseReference,
		&i.RejectionCode,
		&i.RejectionMessage,
		&i.FocAt,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPortInSubmissionManualReview = `-- name: MarkPortInSubmissionManualReview :one
UPDATE number_lifecycle_operations
SET status = 'manual_review',
    reconcile_attempts = reconcile_attempts + 1
WHERE id = $1
  AND operation = 'port_in'
  AND status = 'submitted'
  AND provider_reference IS NULL
RETURNING id, organization_id, phone_number_id, provider_id, idempotency_key, operation, status, provider_reference, requested_number, request_payload, failure_code, failure_message, submitted_at, completed_at, created_at, updated_at, reconcile_after, reconcile_attempts
`

func (q *Queries) MarkPortInSubmissionManualReview(ctx context.Context, id uuid.UUID) (NumberLifecycleOperation, error) {
	row := q.db.QueryRow(ctx, markPortInSubmissionManualReview, id)
	var i NumberLifecycleOperation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PhoneNumberID,
		&i.ProviderID,
		&i.IdempotencyKey,
		&i.Operation,
		&i.Status,
		&i.ProviderReference,
		&i.RequestedNumber,
		&i.RequestPayload,
		&i.FailureCode,
		&i.FailureMessage,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReconcileAfter,
		&i.ReconcileAttempts,
	)
	return i, err
}

const markPortInSubmitted = `-- name: MarkPortInSubmitted :one
UPDATE port_in_cases
SET status = 'submitted', provider_case_reference = $1
WHERE id = $2 AND status IN ('draft', 'checking_portability', 'documents_required')
RETURNING id, organization_id, lifecycle_operation_id, losing_carrier, account_number, account_pin_ciphertext, authorized_name, service_address, desired_port_date, status, provider_case_reference, rejection_code, rejection_message, foc_at, activated_at, created_at, updated_at
`

type MarkPortInSubmittedParams struct {
	ProviderCaseReference *string   `db:"provider_case_reference" json:"provider_case_reference"`
	ID                    uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkPortInSubmitted(ctx context.Context, arg MarkPortInSubmittedParams) (PortInCase, error) {
	row := q.db.QueryRow(ctx, markPortInSubmitted, arg.ProviderCaseReference, arg.ID)
	var i PortInCase
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.LifecycleOperationID,
		&i.LosingCarrier,
		&i.AccountNumber,
		&i.AccountPinCiphertext,
		&i.AuthorizedName,
		&i.ServiceAddress,
		&i.DesiredPortDate,
		&i.Status,
		&i.ProviderCaseReference,
		&i.RejectionCode,
		&i.RejectionMessage,
		&i.FocAt,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rejectEmergencyRegistration = `-- name: RejectEmergencyRegistration :one
UPDATE emergency_registrations
SET status = 'rejected', validation_message = $1
WHERE id = $2 AND status IN ('pending', 'validating')
RETURNING id, organization_id, phone_number_id, provider_id, status, name, address_line1, address_line2, locality, region, postal_code, country_code, provider_reference, validation_message, activated_at, deactivated_at, created_at, updated_at, idempotency_key, request_hash, reconcile_after, reconcile_attempts
`

type RejectEmergencyRegistrationParams struct {
	ValidationMessage *string   `db:"validation_message" json:"validation_message"`
	ID                uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) RejectEmergencyRegistration(ctx context.Context, arg RejectEmergencyRegistrationParams) (EmergencyRegistration, error) {
	row := q.db.QueryRow(ctx, rejectEmergencyRegistration, arg.ValidationMessage, arg.ID)
	var i EmergencyRegistration
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PhoneNumberID,
		&i.ProviderID,
		&i.Status,
		&i.Name,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Locality,
		&i.Region,
		&i.PostalCode,
		&i.CountryCode,
		&i.ProviderReference,
		&i.ValidationMessage,
		&i.ActivatedAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ReconcileAfter,
		&i.ReconcileAttempts,
	)
	return i, err
}

const rejectPortInCase = `-- name: RejectPortInCase :one
UPDATE port_in_cases
SET status = 'rejected', rejection_code = $1,
    rejection_message = $2
WHERE id = $3
  AND status IN ('draft', 'checking_portability', 'documents_required', 'submitted', 'in_progress')
RETURNING id, organization_id, lifecycle_operation_id, losing_carrier, account_number, account_pin_ciphertext, authorized_name, service_address, desired_port_date, status, provider_case_reference, rejection_code, rejection_message, foc_at, activated_at, created_at, updated_at
`

type RejectPortInCaseParams struct {
	RejectionCode    *string   `db:"rejection_code" json:"rejection_code"`
	RejectionMessage *string   `db:"rejection_message" json:"rejection_message"`
	ID               uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) RejectPortInCase(ctx context.Context, arg RejectPortInCaseParams) (PortInCase, error) {
	row := q.db.QueryRow(ctx, rejectPortInCase, arg.RejectionCode, arg.RejectionMessage, arg.ID)
	var i PortInCase
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.LifecycleOperationID,
		&i.LosingCarrier,
		&i.AccountNumber,
		&i.AccountPinCiphertext,
		&i.AuthorizedName,
		&i.ServiceAddress,
		&i.DesiredPortDate,
		&i.Status,
		&i.ProviderCaseReference,
		&i.RejectionCode,
		&i.RejectionMessage,
		&i.FocAt,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const scheduleNumberLifecycleReconciliation = `-- name: ScheduleNumberLifecycleReconciliation :one
UPDATE number_lifecycle_operations
SET reconcile_after = $1,
    reconcile_attempts = reconcile_attempts + 1,
    failure_code = NULL,
    failure_message = NULL
WHERE id = $2
  AND status IN ('pending', 'submitted', 'in_progress')
RETURNING id, organization_id, phone_number_id, provider_id, idempotency_key, operation, status, provider_reference, requested_number, request_payload, failure_code, failure_message, submitted_at, completed_at, created_at, updated_at, reconcile_after, reconcile_attempts
`

type ScheduleNumberLifecycleReconciliationParams struct {
	ReconcileAfter pgtype.Timestamptz `db:"reconcile_after" json:"reconcile_after"`
	ID             uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) ScheduleNumberLifecycleReconciliation(ctx context.Context, arg ScheduleNumberLifecycleReconciliationParams) (NumberLifecycleOperation, error) {
	row := q.db.QueryRow(ctx, scheduleNumberLifecycleReconciliation, arg.ReconcileAfter, arg.ID)
	var i NumberLifecycleOperation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PhoneNumberID,
		&i.ProviderID,
		&i.IdempotencyKey,
		&i.Operation,
		&i.Status,
		&i.ProviderReference,
		&i.RequestedNumber,
		&i.RequestPayload,
		&i.FailureCode,
		&i.FailureMessage,
		&i.SubmittedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReconcileAfter,
		&i.ReconcileAttempts,
	)
	return i, err
}
