// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization_entitlements.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getOrganizationEntitlement = `-- name: GetOrganizationEntitlement :one
SELECT organization_id, capability, enabled, created_at, updated_at
FROM organization_entitlements
WHERE organization_id = $1
  AND capability = $2
LIMIT 1
`

type GetOrganizationEntitlementParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	Capability     string    `db:"capability" json:"capability"`
}

func (q *Queries) GetOrganizationEntitlement(ctx context.Context, arg GetOrganizationEntitlementParams) (OrganizationEntitlement, error) {
	row := q.db.QueryRow(ctx, getOrganizationEntitlement, arg.OrganizationID, arg.Capability)
	var i OrganizationEntitlement
	err := row.Scan(
		&i.OrganizationID,
		&i.Capability,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganizationEntitlements = `-- name: ListOrganizationEntitlements :many
SELECT organization_id, capability, enabled, created_at, updated_at
FROM organization_entitlements
WHERE organization_id = $1
ORDER BY capability
`

func (q *Queries) ListOrganizationEntitlements(ctx context.Context, organizationID uuid.UUID) ([]OrganizationEntitlement, error) {
	rows, err := q.db.Query(ctx, listOrganizationEntitlements, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationEntitlement{}
	for rows.Next() {
		var i OrganizationEntitlement
		if err := rows.Scan(
			&i.OrganizationID,
			&i.Capability,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOrganizationEntitlement = `-- name: UpsertOrganizationEntitlement :one
INSERT INTO organization_entitlements (
    organization_id,
    capability,
    enabled
)
VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (organization_id, capability)
DO UPDATE SET enabled = EXCLUDED.enabled
RETURNING organization_id, capability, enabled, created_at, updated_at
`

type UpsertOrganizationEntitlementParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	Capability     string    `db:"capability" json:"capability"`
	Enabled        bool      `db:"enabled" json:"enabled"`
}

func (q *Queries) UpsertOrganizationEntitlement(ctx context.Context, arg UpsertOrganizationEntitlementParams) (OrganizationEntitlement, error) {
	row := q.db.QueryRow(ctx, upsertOrganizationEntitlement, arg.OrganizationID, arg.Capability, arg.Enabled)
	var i OrganizationEntitlement
	err := row.Scan(
		&i.OrganizationID,
		&i.Capability,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
