// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_initiations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const claimPaymentInitiation = `-- name: ClaimPaymentInitiation :one
WITH available AS MATERIALIZED (
    SELECT p.id, p.checkout_id
    FROM payments AS p
    JOIN checkouts AS c ON c.id = p.checkout_id
    JOIN wallets AS w ON w.id = c.wallet_id
    WHERE p.id = $3::UUID
      AND w.organization_id = $4::UUID
      AND c.status = 'pending' AND c.expires_at > now()
      AND p.status = 'created' AND p.provider_reference IS NULL
    FOR UPDATE OF c
)
INSERT INTO payment_initiations (
    payment_id, checkout_id, request_hash, provider_reference
)
SELECT a.id, a.checkout_id, $1::TEXT,
       $2::TEXT
FROM available AS a
ON CONFLICT DO NOTHING
RETURNING payment_id, checkout_id, request_hash, state, provider_reference, client_secret, display_text, upstream_status, started_at, updated_at
`

type ClaimPaymentInitiationParams struct {
	RequestHash       string    `db:"request_hash" json:"request_hash"`
	ProviderReference *string   `db:"provider_reference" json:"provider_reference"`
	PaymentID         uuid.UUID `db:"payment_id" json:"payment_id"`
	OrganizationID    uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) ClaimPaymentInitiation(ctx context.Context, arg ClaimPaymentInitiationParams) (PaymentInitiation, error) {
	row := q.db.QueryRow(ctx, claimPaymentInitiation,
		arg.RequestHash,
		arg.ProviderReference,
		arg.PaymentID,
		arg.OrganizationID,
	)
	var i PaymentInitiation
	err := row.Scan(
		&i.PaymentID,
		&i.CheckoutID,
		&i.RequestHash,
		&i.State,
		&i.ProviderReference,
		&i.ClientSecret,
		&i.DisplayText,
		&i.UpstreamStatus,
		&i.StartedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentInitiation = `-- name: GetPaymentInitiation :one
SELECT i.payment_id, i.checkout_id, i.request_hash, i.state, i.provider_reference, i.client_secret, i.display_text, i.upstream_status, i.started_at, i.updated_at FROM payment_initiations AS i
JOIN payments AS p ON p.id = i.payment_id
JOIN checkouts AS c ON c.id = p.checkout_id
JOIN wallets AS w ON w.id = c.wallet_id
WHERE w.organization_id = $1::UUID
  AND i.payment_id = $2::UUID LIMIT 1
`

type GetPaymentInitiationParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	PaymentID      uuid.UUID `db:"payment_id" json:"payment_id"`
}

func (q *Queries) GetPaymentInitiation(ctx context.Context, arg GetPaymentInitiationParams) (PaymentInitiation, error) {
	row := q.db.QueryRow(ctx, getPaymentInitiation, arg.OrganizationID, arg.PaymentID)
	var i PaymentInitiation
	err := row.Scan(
		&i.PaymentID,
		&i.CheckoutID,
		&i.RequestHash,
		&i.State,
		&i.ProviderReference,
		&i.ClientSecret,
		&i.DisplayText,
		&i.UpstreamStatus,
		&i.StartedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPaymentInitiationSubmitted = `-- name: MarkPaymentInitiationSubmitted :one
UPDATE payment_initiations SET
    state = 'submitted',
    provider_reference = $1::TEXT,
    client_secret = $2::TEXT,
    display_text = $3::TEXT,
    upstream_status = $4::TEXT
WHERE payment_id = $5::UUID AND state = 'submitting'
  AND (provider_reference IS NULL OR provider_reference = $1::TEXT)
RETURNING payment_id, checkout_id, request_hash, state, provider_reference, client_secret, display_text, upstream_status, started_at, updated_at
`

type MarkPaymentInitiationSubmittedParams struct {
	ProviderReference string    `db:"provider_reference" json:"provider_reference"`
	ClientSecret      *string   `db:"client_secret" json:"client_secret"`
	DisplayText       *string   `db:"display_text" json:"display_text"`
	UpstreamStatus    string    `db:"upstream_status" json:"upstream_status"`
	PaymentID         uuid.UUID `db:"payment_id" json:"payment_id"`
}

func (q *Queries) MarkPaymentInitiationSubmitted(ctx context.Context, arg MarkPaymentInitiationSubmittedParams) (PaymentInitiation, error) {
	row := q.db.QueryRow(ctx, markPaymentInitiationSubmitted,
		arg.ProviderReference,
		arg.ClientSecret,
		arg.DisplayText,
		arg.UpstreamStatus,
		arg.PaymentID,
	)
	var i PaymentInitiation
	err := row.Scan(
		&i.PaymentID,
		&i.CheckoutID,
		&i.RequestHash,
		&i.State,
		&i.ProviderReference,
		&i.ClientSecret,
		&i.DisplayText,
		&i.UpstreamStatus,
		&i.StartedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPaymentInitiationUncertain = `-- name: MarkPaymentInitiationUncertain :exec
UPDATE payment_initiations SET state = 'uncertain'
WHERE payment_id = $1::UUID AND state = 'submitting'
`

func (q *Queries) MarkPaymentInitiationUncertain(ctx context.Context, paymentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPaymentInitiationUncertain, paymentID)
	return err
}

const savePaymentProviderReference = `-- name: SavePaymentProviderReference :one
UPDATE payments SET
    provider_reference = COALESCE(provider_reference, $1::TEXT),
    status = CASE WHEN status = 'created' THEN 'pending' ELSE status END
WHERE id = $2::UUID
  AND status IN ('created', 'pending', 'succeeded')
  AND (provider_reference IS NULL OR provider_reference = $1::TEXT)
RETURNING id, checkout_id, provider, attempt_key, provider_reference, amount_minor, currency, status, verified_at, wallet_transaction_id, failure_code, created_at, updated_at
`

type SavePaymentProviderReferenceParams struct {
	ProviderReference string    `db:"provider_reference" json:"provider_reference"`
	PaymentID         uuid.UUID `db:"payment_id" json:"payment_id"`
}

func (q *Queries) SavePaymentProviderReference(ctx context.Context, arg SavePaymentProviderReferenceParams) (Payment, error) {
	row := q.db.QueryRow(ctx, savePaymentProviderReference, arg.ProviderReference, arg.PaymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutID,
		&i.Provider,
		&i.AttemptKey,
		&i.ProviderReference,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.VerifiedAt,
		&i.WalletTransactionID,
		&i.FailureCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
