// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const attachPaymentProviderReference = `-- name: AttachPaymentProviderReference :one
UPDATE payments
SET provider_reference = $1
WHERE id = $2
  AND organization_id = $3
  AND status = 'pending'
  AND (
      provider_reference IS NULL
      OR provider_reference = $1
  )
RETURNING id, organization_id, purpose, provider, subscription_id, amount_micros, currency, status, provider_reference, provider_event_id, period_start, period_end, failure_code, completed_at, created_at, updated_at
`

type AttachPaymentProviderReferenceParams struct {
	ProviderReference *string   `db:"provider_reference" json:"provider_reference"`
	ID                uuid.UUID `db:"id" json:"id"`
	OrganizationID    uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) AttachPaymentProviderReference(ctx context.Context, arg AttachPaymentProviderReferenceParams) (Payment, error) {
	row := q.db.QueryRow(ctx, attachPaymentProviderReference, arg.ProviderReference, arg.ID, arg.OrganizationID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Purpose,
		&i.Provider,
		&i.SubscriptionID,
		&i.AmountMicros,
		&i.Currency,
		&i.Status,
		&i.ProviderReference,
		&i.ProviderEventID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.FailureCode,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimPaymentProviderEvent = `-- name: ClaimPaymentProviderEvent :one
UPDATE payments
SET provider_event_id = $1
WHERE id = $2
  AND organization_id = $3
  AND status = 'pending'
  AND (
      provider_event_id IS NULL
      OR provider_event_id = $1
  )
RETURNING id, organization_id, purpose, provider, subscription_id, amount_micros, currency, status, provider_reference, provider_event_id, period_start, period_end, failure_code, completed_at, created_at, updated_at
`

type ClaimPaymentProviderEventParams struct {
	ProviderEventID *string   `db:"provider_event_id" json:"provider_event_id"`
	ID              uuid.UUID `db:"id" json:"id"`
	OrganizationID  uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) ClaimPaymentProviderEvent(ctx context.Context, arg ClaimPaymentProviderEventParams) (Payment, error) {
	row := q.db.QueryRow(ctx, claimPaymentProviderEvent, arg.ProviderEventID, arg.ID, arg.OrganizationID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Purpose,
		&i.Provider,
		&i.SubscriptionID,
		&i.AmountMicros,
		&i.Currency,
		&i.Status,
		&i.ProviderReference,
		&i.ProviderEventID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.FailureCode,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubscriptionPayment = `-- name: CreateSubscriptionPayment :one
INSERT INTO payments (
    organization_id,
    purpose,
    provider,
    subscription_id,
    amount_micros,
    currency,
    period_start,
    period_end
)
VALUES (
    $1,
    'subscription',
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, organization_id, purpose, provider, subscription_id, amount_micros, currency, status, provider_reference, provider_event_id, period_start, period_end, failure_code, completed_at, created_at, updated_at
`

type CreateSubscriptionPaymentParams struct {
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	Provider       string             `db:"provider" json:"provider"`
	SubscriptionID *uuid.UUID         `db:"subscription_id" json:"subscription_id"`
	AmountMicros   int64              `db:"amount_micros" json:"amount_micros"`
	Currency       string             `db:"currency" json:"currency"`
	PeriodStart    pgtype.Timestamptz `db:"period_start" json:"period_start"`
	PeriodEnd      pgtype.Timestamptz `db:"period_end" json:"period_end"`
}

func (q *Queries) CreateSubscriptionPayment(ctx context.Context, arg CreateSubscriptionPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createSubscriptionPayment,
		arg.OrganizationID,
		arg.Provider,
		arg.SubscriptionID,
		arg.AmountMicros,
		arg.Currency,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Purpose,
		&i.Provider,
		&i.SubscriptionID,
		&i.AmountMicros,
		&i.Currency,
		&i.Status,
		&i.ProviderReference,
		&i.ProviderEventID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.FailureCode,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWalletTopupPayment = `-- name: CreateWalletTopupPayment :one
INSERT INTO payments (
    organization_id,
    purpose,
    provider,
    amount_micros,
    currency
)
VALUES (
    $1,
    'wallet_topup',
    $2,
    $3,
    $4
)
RETURNING id, organization_id, purpose, provider, subscription_id, amount_micros, currency, status, provider_reference, provider_event_id, period_start, period_end, failure_code, completed_at, created_at, updated_at
`

type CreateWalletTopupPaymentParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	Provider       string    `db:"provider" json:"provider"`
	AmountMicros   int64     `db:"amount_micros" json:"amount_micros"`
	Currency       string    `db:"currency" json:"currency"`
}

func (q *Queries) CreateWalletTopupPayment(ctx context.Context, arg CreateWalletTopupPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createWalletTopupPayment,
		arg.OrganizationID,
		arg.Provider,
		arg.AmountMicros,
		arg.Currency,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Purpose,
		&i.Provider,
		&i.SubscriptionID,
		&i.AmountMicros,
		&i.Currency,
		&i.Status,
		&i.ProviderReference,
		&i.ProviderEventID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.FailureCode,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, organization_id, purpose, provider, subscription_id, amount_micros, currency, status, provider_reference, provider_event_id, period_start, period_end, failure_code, completed_at, created_at, updated_at
FROM payments
WHERE id = $1
  AND organization_id = $2
LIMIT 1
`

type GetPaymentByIDParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetPaymentByID(ctx context.Context, arg GetPaymentByIDParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, arg.ID, arg.OrganizationID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Purpose,
		&i.Provider,
		&i.SubscriptionID,
		&i.AmountMicros,
		&i.Currency,
		&i.Status,
		&i.ProviderReference,
		&i.ProviderEventID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.FailureCode,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPaymentFailed = `-- name: MarkPaymentFailed :one
UPDATE payments
SET
    status = 'failed',
    failure_code = $1,
    completed_at = $2
WHERE id = $3
  AND organization_id = $4
  AND status = 'pending'
  AND provider_event_id = $5
RETURNING id, organization_id, purpose, provider, subscription_id, amount_micros, currency, status, provider_reference, provider_event_id, period_start, period_end, failure_code, completed_at, created_at, updated_at
`

type MarkPaymentFailedParams struct {
	FailureCode     *string            `db:"failure_code" json:"failure_code"`
	CompletedAt     pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	ID              uuid.UUID          `db:"id" json:"id"`
	OrganizationID  uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProviderEventID *string            `db:"provider_event_id" json:"provider_event_id"`
}

func (q *Queries) MarkPaymentFailed(ctx context.Context, arg MarkPaymentFailedParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentFailed,
		arg.FailureCode,
		arg.CompletedAt,
		arg.ID,
		arg.OrganizationID,
		arg.ProviderEventID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Purpose,
		&i.Provider,
		&i.SubscriptionID,
		&i.AmountMicros,
		&i.Currency,
		&i.Status,
		&i.ProviderReference,
		&i.ProviderEventID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.FailureCode,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPaymentSucceeded = `-- name: MarkPaymentSucceeded :one
UPDATE payments
SET
    status = 'succeeded',
    completed_at = $1
WHERE id = $2
  AND organization_id = $3
  AND status = 'pending'
  AND provider_event_id = $4
RETURNING id, organization_id, purpose, provider, subscription_id, amount_micros, currency, status, provider_reference, provider_event_id, period_start, period_end, failure_code, completed_at, created_at, updated_at
`

type MarkPaymentSucceededParams struct {
	CompletedAt     pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	ID              uuid.UUID          `db:"id" json:"id"`
	OrganizationID  uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProviderEventID *string            `db:"provider_event_id" json:"provider_event_id"`
}

func (q *Queries) MarkPaymentSucceeded(ctx context.Context, arg MarkPaymentSucceededParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentSucceeded,
		arg.CompletedAt,
		arg.ID,
		arg.OrganizationID,
		arg.ProviderEventID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Purpose,
		&i.Provider,
		&i.SubscriptionID,
		&i.AmountMicros,
		&i.Currency,
		&i.Status,
		&i.ProviderReference,
		&i.ProviderEventID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.FailureCode,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
