// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const attachProviderPaymentID = `-- name: AttachProviderPaymentID :one
UPDATE payments
SET
    provider_payment_id = $1,
    status = 'processing'
WHERE id = $2
  AND checkout_id = $3
  AND organization_id = $4
  AND status IN ('pending', 'processing')
  AND (
      provider_payment_id IS NULL
      OR provider_payment_id = $1
  )
RETURNING id, checkout_id, organization_id, provider, attempt, provider_payment_id, amount_micros, currency, status, failure_code, paid_at, metadata, created_at, updated_at
`

type AttachProviderPaymentIDParams struct {
	ProviderPaymentID *string   `db:"provider_payment_id" json:"provider_payment_id"`
	ID                uuid.UUID `db:"id" json:"id"`
	CheckoutID        uuid.UUID `db:"checkout_id" json:"checkout_id"`
	OrganizationID    uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) AttachProviderPaymentID(ctx context.Context, arg AttachProviderPaymentIDParams) (Payment, error) {
	row := q.db.QueryRow(ctx, attachProviderPaymentID,
		arg.ProviderPaymentID,
		arg.ID,
		arg.CheckoutID,
		arg.OrganizationID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutID,
		&i.OrganizationID,
		&i.Provider,
		&i.Attempt,
		&i.ProviderPaymentID,
		&i.AmountMicros,
		&i.Currency,
		&i.Status,
		&i.FailureCode,
		&i.PaidAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPaymentAttempt = `-- name: CreatePaymentAttempt :one
INSERT INTO payments (
    checkout_id,
    organization_id,
    provider,
    attempt,
    amount_micros,
    currency
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, checkout_id, organization_id, provider, attempt, provider_payment_id, amount_micros, currency, status, failure_code, paid_at, metadata, created_at, updated_at
`

type CreatePaymentAttemptParams struct {
	CheckoutID     uuid.UUID `db:"checkout_id" json:"checkout_id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	Provider       string    `db:"provider" json:"provider"`
	Attempt        int32     `db:"attempt" json:"attempt"`
	AmountMicros   int64     `db:"amount_micros" json:"amount_micros"`
	Currency       string    `db:"currency" json:"currency"`
}

func (q *Queries) CreatePaymentAttempt(ctx context.Context, arg CreatePaymentAttemptParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPaymentAttempt,
		arg.CheckoutID,
		arg.OrganizationID,
		arg.Provider,
		arg.Attempt,
		arg.AmountMicros,
		arg.Currency,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutID,
		&i.OrganizationID,
		&i.Provider,
		&i.Attempt,
		&i.ProviderPaymentID,
		&i.AmountMicros,
		&i.Currency,
		&i.Status,
		&i.FailureCode,
		&i.PaidAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivePaymentAttemptByCheckout = `-- name: GetActivePaymentAttemptByCheckout :one
SELECT id, checkout_id, organization_id, provider, attempt, provider_payment_id, amount_micros, currency, status, failure_code, paid_at, metadata, created_at, updated_at
FROM payments
WHERE checkout_id = $1
  AND organization_id = $2
  AND status IN ('pending', 'processing')
ORDER BY attempt DESC
LIMIT 1
`

type GetActivePaymentAttemptByCheckoutParams struct {
	CheckoutID     uuid.UUID `db:"checkout_id" json:"checkout_id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetActivePaymentAttemptByCheckout(ctx context.Context, arg GetActivePaymentAttemptByCheckoutParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getActivePaymentAttemptByCheckout, arg.CheckoutID, arg.OrganizationID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutID,
		&i.OrganizationID,
		&i.Provider,
		&i.Attempt,
		&i.ProviderPaymentID,
		&i.AmountMicros,
		&i.Currency,
		&i.Status,
		&i.FailureCode,
		&i.PaidAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextPaymentAttemptNumber = `-- name: GetNextPaymentAttemptNumber :one
SELECT COALESCE(MAX(attempt), 0)::bigint + 1 AS next_attempt
FROM payments
WHERE checkout_id = $1
  AND organization_id = $2
`

type GetNextPaymentAttemptNumberParams struct {
	CheckoutID     uuid.UUID `db:"checkout_id" json:"checkout_id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetNextPaymentAttemptNumber(ctx context.Context, arg GetNextPaymentAttemptNumberParams) (int32, error) {
	row := q.db.QueryRow(ctx, getNextPaymentAttemptNumber, arg.CheckoutID, arg.OrganizationID)
	var next_attempt int32
	err := row.Scan(&next_attempt)
	return next_attempt, err
}

const getPaymentAttemptByID = `-- name: GetPaymentAttemptByID :one
SELECT id, checkout_id, organization_id, provider, attempt, provider_payment_id, amount_micros, currency, status, failure_code, paid_at, metadata, created_at, updated_at
FROM payments
WHERE id = $1
  AND checkout_id = $2
  AND organization_id = $3
LIMIT 1
`

type GetPaymentAttemptByIDParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	CheckoutID     uuid.UUID `db:"checkout_id" json:"checkout_id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetPaymentAttemptByID(ctx context.Context, arg GetPaymentAttemptByIDParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentAttemptByID, arg.ID, arg.CheckoutID, arg.OrganizationID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutID,
		&i.OrganizationID,
		&i.Provider,
		&i.Attempt,
		&i.ProviderPaymentID,
		&i.AmountMicros,
		&i.Currency,
		&i.Status,
		&i.FailureCode,
		&i.PaidAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentAttemptByProviderPaymentID = `-- name: GetPaymentAttemptByProviderPaymentID :one
SELECT id, checkout_id, organization_id, provider, attempt, provider_payment_id, amount_micros, currency, status, failure_code, paid_at, metadata, created_at, updated_at
FROM payments
WHERE provider = $1
  AND provider_payment_id = $2
LIMIT 1
`

type GetPaymentAttemptByProviderPaymentIDParams struct {
	Provider          string  `db:"provider" json:"provider"`
	ProviderPaymentID *string `db:"provider_payment_id" json:"provider_payment_id"`
}

func (q *Queries) GetPaymentAttemptByProviderPaymentID(ctx context.Context, arg GetPaymentAttemptByProviderPaymentIDParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentAttemptByProviderPaymentID, arg.Provider, arg.ProviderPaymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutID,
		&i.OrganizationID,
		&i.Provider,
		&i.Attempt,
		&i.ProviderPaymentID,
		&i.AmountMicros,
		&i.Currency,
		&i.Status,
		&i.FailureCode,
		&i.PaidAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPaymentAttemptFailed = `-- name: MarkPaymentAttemptFailed :one
UPDATE payments
SET
    status = 'failed',
    failure_code = $1
WHERE id = $2
  AND checkout_id = $3
  AND organization_id = $4
  AND status IN ('pending', 'processing')
RETURNING id, checkout_id, organization_id, provider, attempt, provider_payment_id, amount_micros, currency, status, failure_code, paid_at, metadata, created_at, updated_at
`

type MarkPaymentAttemptFailedParams struct {
	FailureCode    *string   `db:"failure_code" json:"failure_code"`
	ID             uuid.UUID `db:"id" json:"id"`
	CheckoutID     uuid.UUID `db:"checkout_id" json:"checkout_id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) MarkPaymentAttemptFailed(ctx context.Context, arg MarkPaymentAttemptFailedParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentAttemptFailed,
		arg.FailureCode,
		arg.ID,
		arg.CheckoutID,
		arg.OrganizationID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutID,
		&i.OrganizationID,
		&i.Provider,
		&i.Attempt,
		&i.ProviderPaymentID,
		&i.AmountMicros,
		&i.Currency,
		&i.Status,
		&i.FailureCode,
		&i.PaidAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPaymentAttemptSucceeded = `-- name: MarkPaymentAttemptSucceeded :one
UPDATE payments
SET
    status = 'succeeded',
    failure_code = NULL,
    paid_at = $1
WHERE id = $2
  AND checkout_id = $3
  AND organization_id = $4
  AND status IN ('pending', 'processing')
RETURNING id, checkout_id, organization_id, provider, attempt, provider_payment_id, amount_micros, currency, status, failure_code, paid_at, metadata, created_at, updated_at
`

type MarkPaymentAttemptSucceededParams struct {
	PaidAt         pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
	ID             uuid.UUID          `db:"id" json:"id"`
	CheckoutID     uuid.UUID          `db:"checkout_id" json:"checkout_id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
}

func (q *Queries) MarkPaymentAttemptSucceeded(ctx context.Context, arg MarkPaymentAttemptSucceededParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentAttemptSucceeded,
		arg.PaidAt,
		arg.ID,
		arg.CheckoutID,
		arg.OrganizationID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.CheckoutID,
		&i.OrganizationID,
		&i.Provider,
		&i.Attempt,
		&i.ProviderPaymentID,
		&i.AmountMicros,
		&i.Currency,
		&i.Status,
		&i.FailureCode,
		&i.PaidAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
