// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_provider_events.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentProviderEvent = `-- name: CreatePaymentProviderEvent :one
INSERT INTO payment_provider_events (
    payment_id,
    organization_id,
    provider,
    provider_event_id,
    event_type,
    payload_sha256,
    payload,
    received_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, payment_id, organization_id, provider, provider_event_id, event_type, payload_sha256, payload, received_at, processed_at
`

type CreatePaymentProviderEventParams struct {
	PaymentID       uuid.UUID          `db:"payment_id" json:"payment_id"`
	OrganizationID  uuid.UUID          `db:"organization_id" json:"organization_id"`
	Provider        string             `db:"provider" json:"provider"`
	ProviderEventID string             `db:"provider_event_id" json:"provider_event_id"`
	EventType       string             `db:"event_type" json:"event_type"`
	PayloadSha256   string             `db:"payload_sha256" json:"payload_sha256"`
	Payload         []byte             `db:"payload" json:"payload"`
	ReceivedAt      pgtype.Timestamptz `db:"received_at" json:"received_at"`
}

func (q *Queries) CreatePaymentProviderEvent(ctx context.Context, arg CreatePaymentProviderEventParams) (PaymentProviderEvent, error) {
	row := q.db.QueryRow(ctx, createPaymentProviderEvent,
		arg.PaymentID,
		arg.OrganizationID,
		arg.Provider,
		arg.ProviderEventID,
		arg.EventType,
		arg.PayloadSha256,
		arg.Payload,
		arg.ReceivedAt,
	)
	var i PaymentProviderEvent
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.OrganizationID,
		&i.Provider,
		&i.ProviderEventID,
		&i.EventType,
		&i.PayloadSha256,
		&i.Payload,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getPaymentProviderEventByIdentity = `-- name: GetPaymentProviderEventByIdentity :one
SELECT id, payment_id, organization_id, provider, provider_event_id, event_type, payload_sha256, payload, received_at, processed_at
FROM payment_provider_events
WHERE provider = $1
  AND provider_event_id = $2
LIMIT 1
`

type GetPaymentProviderEventByIdentityParams struct {
	Provider        string `db:"provider" json:"provider"`
	ProviderEventID string `db:"provider_event_id" json:"provider_event_id"`
}

func (q *Queries) GetPaymentProviderEventByIdentity(ctx context.Context, arg GetPaymentProviderEventByIdentityParams) (PaymentProviderEvent, error) {
	row := q.db.QueryRow(ctx, getPaymentProviderEventByIdentity, arg.Provider, arg.ProviderEventID)
	var i PaymentProviderEvent
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.OrganizationID,
		&i.Provider,
		&i.ProviderEventID,
		&i.EventType,
		&i.PayloadSha256,
		&i.Payload,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const listUnprocessedPaymentProviderEvents = `-- name: ListUnprocessedPaymentProviderEvents :many
SELECT id, payment_id, organization_id, provider, provider_event_id, event_type, payload_sha256, payload, received_at, processed_at
FROM payment_provider_events
WHERE processed_at IS NULL
ORDER BY received_at, id
LIMIT $1
`

func (q *Queries) ListUnprocessedPaymentProviderEvents(ctx context.Context, limitCount int32) ([]PaymentProviderEvent, error) {
	rows, err := q.db.Query(ctx, listUnprocessedPaymentProviderEvents, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentProviderEvent{}
	for rows.Next() {
		var i PaymentProviderEvent
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.OrganizationID,
			&i.Provider,
			&i.ProviderEventID,
			&i.EventType,
			&i.PayloadSha256,
			&i.Payload,
			&i.ReceivedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentProviderEventProcessed = `-- name: MarkPaymentProviderEventProcessed :one
WITH updated AS (
    UPDATE payment_provider_events
    SET processed_at = $1
    WHERE id = $2
      AND processed_at IS NULL
    RETURNING id, payment_id, organization_id, provider, provider_event_id, event_type, payload_sha256, payload, received_at, processed_at
)
SELECT id, payment_id, organization_id, provider, provider_event_id, event_type, payload_sha256, payload, received_at, processed_at FROM updated
UNION ALL
SELECT id, payment_id, organization_id, provider, provider_event_id, event_type, payload_sha256, payload, received_at, processed_at
FROM payment_provider_events
WHERE id = $2
  AND processed_at IS NOT NULL
LIMIT 1
`

type MarkPaymentProviderEventProcessedParams struct {
	ProcessedAt pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
	ID          uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) MarkPaymentProviderEventProcessed(ctx context.Context, arg MarkPaymentProviderEventProcessedParams) (PaymentProviderEvent, error) {
	row := q.db.QueryRow(ctx, markPaymentProviderEventProcessed, arg.ProcessedAt, arg.ID)
	var i PaymentProviderEvent
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.OrganizationID,
		&i.Provider,
		&i.ProviderEventID,
		&i.EventType,
		&i.PayloadSha256,
		&i.Payload,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}
