// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_rates.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const resolveProductRate = `-- name: ResolveProductRate :one
SELECT pr.id, pr.organization_id, pr.product, pr.selector, pr.currency, pr.rate_micros, pr.effective_at, pr.expires_at, pr.created_at
FROM product_rates AS pr
JOIN organizations AS o
  ON o.id = $1
 AND o.status = 'active'
 AND o.deleted_at IS NULL
WHERE (pr.organization_id = o.id OR pr.organization_id IS NULL)
  AND pr.product = $2
  AND (pr.selector = $3 OR pr.selector = '*')
  AND pr.currency = $4
  AND pr.effective_at <= $5
  AND (pr.expires_at IS NULL OR pr.expires_at > $5)
ORDER BY
    (pr.organization_id IS NOT NULL) DESC,
    (pr.selector = $3) DESC,
    pr.effective_at DESC
LIMIT 1
`

type ResolveProductRateParams struct {
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	Product        string             `db:"product" json:"product"`
	Selector       string             `db:"selector" json:"selector"`
	Currency       string             `db:"currency" json:"currency"`
	ResolvedAt     pgtype.Timestamptz `db:"resolved_at" json:"resolved_at"`
}

func (q *Queries) ResolveProductRate(ctx context.Context, arg ResolveProductRateParams) (ProductRate, error) {
	row := q.db.QueryRow(ctx, resolveProductRate,
		arg.OrganizationID,
		arg.Product,
		arg.Selector,
		arg.Currency,
		arg.ResolvedAt,
	)
	var i ProductRate
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Product,
		&i.Selector,
		&i.Currency,
		&i.RateMicros,
		&i.EffectiveAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
