// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_cdrs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProviderCDR = `-- name: CreateProviderCDR :one
INSERT INTO provider_cdrs (
    provider_id,
    carrier_connection_id,
    call_id,
    provider_cdr_id,
    direction,
    source,
    destination,
    started_at,
    answered_at,
    ended_at,
    duration_seconds,
    billable_seconds,
    raw_payload,
    received_at
)
SELECT
    cp.id,
    cc.id,
    c.id,
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
FROM calls AS c
JOIN carrier_connections AS cc
  ON cc.id = $12
JOIN carrier_providers AS cp
  ON cp.id = $13
 AND cp.id = cc.provider_id
WHERE c.id = $14
  AND c.carrier_connection_id = cc.id
  AND c.state IN ('completed', 'failed', 'cancelled')
  AND c.ended_at IS NOT NULL
  AND cc.scope = 'platform'
  AND cc.organization_id IS NULL
  AND cc.status = 'active'
  AND cp.status = 'active'
ON CONFLICT (provider_id, provider_cdr_id) DO NOTHING
RETURNING id, provider_id, carrier_connection_id, call_id, provider_cdr_id, direction, source, destination, started_at, answered_at, ended_at, duration_seconds, billable_seconds, raw_payload, received_at, created_at
`

type CreateProviderCDRParams struct {
	ProviderCdrID       string             `db:"provider_cdr_id" json:"provider_cdr_id"`
	Direction           string             `db:"direction" json:"direction"`
	Source              *string            `db:"source" json:"source"`
	Destination         *string            `db:"destination" json:"destination"`
	StartedAt           pgtype.Timestamptz `db:"started_at" json:"started_at"`
	AnsweredAt          pgtype.Timestamptz `db:"answered_at" json:"answered_at"`
	EndedAt             pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	DurationSeconds     int64              `db:"duration_seconds" json:"duration_seconds"`
	BillableSeconds     int64              `db:"billable_seconds" json:"billable_seconds"`
	RawPayload          []byte             `db:"raw_payload" json:"raw_payload"`
	ReceivedAt          pgtype.Timestamptz `db:"received_at" json:"received_at"`
	CarrierConnectionID uuid.UUID          `db:"carrier_connection_id" json:"carrier_connection_id"`
	ProviderID          uuid.UUID          `db:"provider_id" json:"provider_id"`
	CallID              uuid.UUID          `db:"call_id" json:"call_id"`
}

func (q *Queries) CreateProviderCDR(ctx context.Context, arg CreateProviderCDRParams) (ProviderCdr, error) {
	row := q.db.QueryRow(ctx, createProviderCDR,
		arg.ProviderCdrID,
		arg.Direction,
		arg.Source,
		arg.Destination,
		arg.StartedAt,
		arg.AnsweredAt,
		arg.EndedAt,
		arg.DurationSeconds,
		arg.BillableSeconds,
		arg.RawPayload,
		arg.ReceivedAt,
		arg.CarrierConnectionID,
		arg.ProviderID,
		arg.CallID,
	)
	var i ProviderCdr
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.CarrierConnectionID,
		&i.CallID,
		&i.ProviderCdrID,
		&i.Direction,
		&i.Source,
		&i.Destination,
		&i.StartedAt,
		&i.AnsweredAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.BillableSeconds,
		&i.RawPayload,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getProviderCDRByID = `-- name: GetProviderCDRByID :one
SELECT id, provider_id, carrier_connection_id, call_id, provider_cdr_id, direction, source, destination, started_at, answered_at, ended_at, duration_seconds, billable_seconds, raw_payload, received_at, created_at
FROM provider_cdrs
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProviderCDRByID(ctx context.Context, id uuid.UUID) (ProviderCdr, error) {
	row := q.db.QueryRow(ctx, getProviderCDRByID, id)
	var i ProviderCdr
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.CarrierConnectionID,
		&i.CallID,
		&i.ProviderCdrID,
		&i.Direction,
		&i.Source,
		&i.Destination,
		&i.StartedAt,
		&i.AnsweredAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.BillableSeconds,
		&i.RawPayload,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getProviderCDRByProviderRecord = `-- name: GetProviderCDRByProviderRecord :one
SELECT id, provider_id, carrier_connection_id, call_id, provider_cdr_id, direction, source, destination, started_at, answered_at, ended_at, duration_seconds, billable_seconds, raw_payload, received_at, created_at
FROM provider_cdrs
WHERE provider_id = $1
  AND provider_cdr_id = $2
LIMIT 1
`

type GetProviderCDRByProviderRecordParams struct {
	ProviderID    uuid.UUID `db:"provider_id" json:"provider_id"`
	ProviderCdrID string    `db:"provider_cdr_id" json:"provider_cdr_id"`
}

func (q *Queries) GetProviderCDRByProviderRecord(ctx context.Context, arg GetProviderCDRByProviderRecordParams) (ProviderCdr, error) {
	row := q.db.QueryRow(ctx, getProviderCDRByProviderRecord, arg.ProviderID, arg.ProviderCdrID)
	var i ProviderCdr
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.CarrierConnectionID,
		&i.CallID,
		&i.ProviderCdrID,
		&i.Direction,
		&i.Source,
		&i.Destination,
		&i.StartedAt,
		&i.AnsweredAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.BillableSeconds,
		&i.RawPayload,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listProviderCDRsByCall = `-- name: ListProviderCDRsByCall :many
SELECT id, provider_id, carrier_connection_id, call_id, provider_cdr_id, direction, source, destination, started_at, answered_at, ended_at, duration_seconds, billable_seconds, raw_payload, received_at, created_at
FROM provider_cdrs
WHERE call_id = $1
ORDER BY started_at ASC, id ASC
`

func (q *Queries) ListProviderCDRsByCall(ctx context.Context, callID uuid.UUID) ([]ProviderCdr, error) {
	rows, err := q.db.Query(ctx, listProviderCDRsByCall, callID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderCdr{}
	for rows.Next() {
		var i ProviderCdr
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.CarrierConnectionID,
			&i.CallID,
			&i.ProviderCdrID,
			&i.Direction,
			&i.Source,
			&i.Destination,
			&i.StartedAt,
			&i.AnsweredAt,
			&i.EndedAt,
			&i.DurationSeconds,
			&i.BillableSeconds,
			&i.RawPayload,
			&i.ReceivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
