// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_charges.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProviderCharge = `-- name: CreateProviderCharge :one
INSERT INTO provider_charges (
    provider_id,
    operation_id,
    provider_record_type,
    provider_record_id,
    product,
    currency,
    amount_micros,
    incurred_at,
    raw_payload
)
SELECT
    cp.id,
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
FROM carrier_providers AS cp
WHERE cp.id = $9
  AND cp.status = 'active'
ON CONFLICT (provider_id, provider_record_type, provider_record_id) DO NOTHING
RETURNING provider_charges.id, provider_charges.provider_id, provider_charges.provider_cdr_id, provider_charges.operation_id, provider_charges.provider_record_type, provider_charges.provider_record_id, provider_charges.product, provider_charges.currency, provider_charges.rate_micros, provider_charges.billable_seconds, provider_charges.amount_micros, provider_charges.incurred_at, provider_charges.raw_payload, provider_charges.recorded_at
`

type CreateProviderChargeParams struct {
	OperationID        *uuid.UUID         `db:"operation_id" json:"operation_id"`
	ProviderRecordType string             `db:"provider_record_type" json:"provider_record_type"`
	ProviderRecordID   string             `db:"provider_record_id" json:"provider_record_id"`
	Product            string             `db:"product" json:"product"`
	Currency           string             `db:"currency" json:"currency"`
	AmountMicros       int64              `db:"amount_micros" json:"amount_micros"`
	IncurredAt         pgtype.Timestamptz `db:"incurred_at" json:"incurred_at"`
	RawPayload         []byte             `db:"raw_payload" json:"raw_payload"`
	ProviderID         uuid.UUID          `db:"provider_id" json:"provider_id"`
}

func (q *Queries) CreateProviderCharge(ctx context.Context, arg CreateProviderChargeParams) (ProviderCharge, error) {
	row := q.db.QueryRow(ctx, createProviderCharge,
		arg.OperationID,
		arg.ProviderRecordType,
		arg.ProviderRecordID,
		arg.Product,
		arg.Currency,
		arg.AmountMicros,
		arg.IncurredAt,
		arg.RawPayload,
		arg.ProviderID,
	)
	var i ProviderCharge
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ProviderCdrID,
		&i.OperationID,
		&i.ProviderRecordType,
		&i.ProviderRecordID,
		&i.Product,
		&i.Currency,
		&i.RateMicros,
		&i.BillableSeconds,
		&i.AmountMicros,
		&i.IncurredAt,
		&i.RawPayload,
		&i.RecordedAt,
	)
	return i, err
}

const createVoiceProviderCharge = `-- name: CreateVoiceProviderCharge :one
INSERT INTO provider_charges (
    provider_id,
    provider_cdr_id,
    operation_id,
    provider_record_type,
    provider_record_id,
    product,
    currency,
    rate_micros,
    billable_seconds,
    amount_micros,
    incurred_at,
    raw_payload
)
SELECT
    cdr.provider_id,
    cdr.id,
    $1,
    'voice_cdr',
    cdr.provider_cdr_id,
    'voice',
    $2,
    $3,
    $4,
    $5,
    $6,
    cdr.raw_payload
FROM provider_cdrs AS cdr
WHERE cdr.id = $7
  AND cdr.billable_seconds = $4
ON CONFLICT (provider_id, provider_record_type, provider_record_id) DO NOTHING
RETURNING id, provider_id, provider_cdr_id, operation_id, provider_record_type, provider_record_id, product, currency, rate_micros, billable_seconds, amount_micros, incurred_at, raw_payload, recorded_at
`

type CreateVoiceProviderChargeParams struct {
	OperationID     *uuid.UUID         `db:"operation_id" json:"operation_id"`
	Currency        string             `db:"currency" json:"currency"`
	RateMicros      *int64             `db:"rate_micros" json:"rate_micros"`
	BillableSeconds *int64             `db:"billable_seconds" json:"billable_seconds"`
	AmountMicros    int64              `db:"amount_micros" json:"amount_micros"`
	IncurredAt      pgtype.Timestamptz `db:"incurred_at" json:"incurred_at"`
	ProviderCdrID   uuid.UUID          `db:"provider_cdr_id" json:"provider_cdr_id"`
}

func (q *Queries) CreateVoiceProviderCharge(ctx context.Context, arg CreateVoiceProviderChargeParams) (ProviderCharge, error) {
	row := q.db.QueryRow(ctx, createVoiceProviderCharge,
		arg.OperationID,
		arg.Currency,
		arg.RateMicros,
		arg.BillableSeconds,
		arg.AmountMicros,
		arg.IncurredAt,
		arg.ProviderCdrID,
	)
	var i ProviderCharge
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ProviderCdrID,
		&i.OperationID,
		&i.ProviderRecordType,
		&i.ProviderRecordID,
		&i.Product,
		&i.Currency,
		&i.RateMicros,
		&i.BillableSeconds,
		&i.AmountMicros,
		&i.IncurredAt,
		&i.RawPayload,
		&i.RecordedAt,
	)
	return i, err
}

const getProviderChargeByID = `-- name: GetProviderChargeByID :one
SELECT id, provider_id, provider_cdr_id, operation_id, provider_record_type, provider_record_id, product, currency, rate_micros, billable_seconds, amount_micros, incurred_at, raw_payload, recorded_at FROM provider_charges WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProviderChargeByID(ctx context.Context, id uuid.UUID) (ProviderCharge, error) {
	row := q.db.QueryRow(ctx, getProviderChargeByID, id)
	var i ProviderCharge
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ProviderCdrID,
		&i.OperationID,
		&i.ProviderRecordType,
		&i.ProviderRecordID,
		&i.Product,
		&i.Currency,
		&i.RateMicros,
		&i.BillableSeconds,
		&i.AmountMicros,
		&i.IncurredAt,
		&i.RawPayload,
		&i.RecordedAt,
	)
	return i, err
}

const getProviderChargeByProviderCDR = `-- name: GetProviderChargeByProviderCDR :one
SELECT id, provider_id, provider_cdr_id, operation_id, provider_record_type, provider_record_id, product, currency, rate_micros, billable_seconds, amount_micros, incurred_at, raw_payload, recorded_at FROM provider_charges WHERE provider_cdr_id = $1 LIMIT 1
`

func (q *Queries) GetProviderChargeByProviderCDR(ctx context.Context, providerCdrID *uuid.UUID) (ProviderCharge, error) {
	row := q.db.QueryRow(ctx, getProviderChargeByProviderCDR, providerCdrID)
	var i ProviderCharge
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ProviderCdrID,
		&i.OperationID,
		&i.ProviderRecordType,
		&i.ProviderRecordID,
		&i.Product,
		&i.Currency,
		&i.RateMicros,
		&i.BillableSeconds,
		&i.AmountMicros,
		&i.IncurredAt,
		&i.RawPayload,
		&i.RecordedAt,
	)
	return i, err
}

const getProviderChargeByRecord = `-- name: GetProviderChargeByRecord :one
SELECT id, provider_id, provider_cdr_id, operation_id, provider_record_type, provider_record_id, product, currency, rate_micros, billable_seconds, amount_micros, incurred_at, raw_payload, recorded_at
FROM provider_charges
WHERE provider_id = $1
  AND provider_record_type = $2
  AND provider_record_id = $3
LIMIT 1
`

type GetProviderChargeByRecordParams struct {
	ProviderID         uuid.UUID `db:"provider_id" json:"provider_id"`
	ProviderRecordType string    `db:"provider_record_type" json:"provider_record_type"`
	ProviderRecordID   string    `db:"provider_record_id" json:"provider_record_id"`
}

func (q *Queries) GetProviderChargeByRecord(ctx context.Context, arg GetProviderChargeByRecordParams) (ProviderCharge, error) {
	row := q.db.QueryRow(ctx, getProviderChargeByRecord, arg.ProviderID, arg.ProviderRecordType, arg.ProviderRecordID)
	var i ProviderCharge
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ProviderCdrID,
		&i.OperationID,
		&i.ProviderRecordType,
		&i.ProviderRecordID,
		&i.Product,
		&i.Currency,
		&i.RateMicros,
		&i.BillableSeconds,
		&i.AmountMicros,
		&i.IncurredAt,
		&i.RawPayload,
		&i.RecordedAt,
	)
	return i, err
}

const listProviderChargesByCall = `-- name: ListProviderChargesByCall :many
SELECT charge.id, charge.provider_id, charge.provider_cdr_id, charge.operation_id, charge.provider_record_type, charge.provider_record_id, charge.product, charge.currency, charge.rate_micros, charge.billable_seconds, charge.amount_micros, charge.incurred_at, charge.raw_payload, charge.recorded_at
FROM provider_charges AS charge
JOIN provider_cdrs AS cdr ON cdr.id = charge.provider_cdr_id
WHERE cdr.call_id = $1
ORDER BY charge.incurred_at, charge.id
`

func (q *Queries) ListProviderChargesByCall(ctx context.Context, callID uuid.UUID) ([]ProviderCharge, error) {
	rows, err := q.db.Query(ctx, listProviderChargesByCall, callID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderCharge{}
	for rows.Next() {
		var i ProviderCharge
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ProviderCdrID,
			&i.OperationID,
			&i.ProviderRecordType,
			&i.ProviderRecordID,
			&i.Product,
			&i.Currency,
			&i.RateMicros,
			&i.BillableSeconds,
			&i.AmountMicros,
			&i.IncurredAt,
			&i.RawPayload,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderChargesByOperation = `-- name: ListProviderChargesByOperation :many
SELECT id, provider_id, provider_cdr_id, operation_id, provider_record_type, provider_record_id, product, currency, rate_micros, billable_seconds, amount_micros, incurred_at, raw_payload, recorded_at
FROM provider_charges
WHERE operation_id = $1
ORDER BY incurred_at, id
`

func (q *Queries) ListProviderChargesByOperation(ctx context.Context, operationID *uuid.UUID) ([]ProviderCharge, error) {
	rows, err := q.db.Query(ctx, listProviderChargesByOperation, operationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderCharge{}
	for rows.Next() {
		var i ProviderCharge
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ProviderCdrID,
			&i.OperationID,
			&i.ProviderRecordType,
			&i.ProviderRecordID,
			&i.Product,
			&i.Currency,
			&i.RateMicros,
			&i.BillableSeconds,
			&i.AmountMicros,
			&i.IncurredAt,
			&i.RawPayload,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreconciledProviderCharges = `-- name: ListUnreconciledProviderCharges :many
SELECT id, provider_id, provider_cdr_id, operation_id, provider_record_type, provider_record_id, product, currency, rate_micros, billable_seconds, amount_micros, incurred_at, raw_payload, recorded_at
FROM provider_charges
WHERE operation_id IS NULL
ORDER BY incurred_at, id
LIMIT $1
`

func (q *Queries) ListUnreconciledProviderCharges(ctx context.Context, batch int32) ([]ProviderCharge, error) {
	rows, err := q.db.Query(ctx, listUnreconciledProviderCharges, batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderCharge{}
	for rows.Next() {
		var i ProviderCharge
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ProviderCdrID,
			&i.OperationID,
			&i.ProviderRecordType,
			&i.ProviderRecordID,
			&i.Product,
			&i.Currency,
			&i.RateMicros,
			&i.BillableSeconds,
			&i.AmountMicros,
			&i.IncurredAt,
			&i.RawPayload,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
