// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_costs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProviderCost = `-- name: CreateProviderCost :one
INSERT INTO provider_costs (
    provider_id,
    operation_id,
    provider_record_id,
    product,
    currency,
    amount_micros,
    incurred_at,
    raw_payload
)
SELECT
    cp.id,
    ledger.operation_id,
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
FROM carrier_providers AS cp
JOIN wallet_ledger_entries AS ledger
  ON ledger.operation_id = $7
 AND ledger.direction = 'debit'
WHERE cp.id = $8
  AND cp.status = 'active'
ON CONFLICT (provider_id, provider_record_id) DO NOTHING
RETURNING provider_costs.id, provider_costs.provider_id, provider_costs.operation_id, provider_costs.provider_record_id, provider_costs.product, provider_costs.currency, provider_costs.amount_micros, provider_costs.incurred_at, provider_costs.raw_payload, provider_costs.recorded_at
`

type CreateProviderCostParams struct {
	ProviderRecordID string             `db:"provider_record_id" json:"provider_record_id"`
	Product          string             `db:"product" json:"product"`
	Currency         string             `db:"currency" json:"currency"`
	AmountMicros     int64              `db:"amount_micros" json:"amount_micros"`
	IncurredAt       pgtype.Timestamptz `db:"incurred_at" json:"incurred_at"`
	RawPayload       []byte             `db:"raw_payload" json:"raw_payload"`
	OperationID      uuid.UUID          `db:"operation_id" json:"operation_id"`
	ProviderID       uuid.UUID          `db:"provider_id" json:"provider_id"`
}

func (q *Queries) CreateProviderCost(ctx context.Context, arg CreateProviderCostParams) (ProviderCost, error) {
	row := q.db.QueryRow(ctx, createProviderCost,
		arg.ProviderRecordID,
		arg.Product,
		arg.Currency,
		arg.AmountMicros,
		arg.IncurredAt,
		arg.RawPayload,
		arg.OperationID,
		arg.ProviderID,
	)
	var i ProviderCost
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.OperationID,
		&i.ProviderRecordID,
		&i.Product,
		&i.Currency,
		&i.AmountMicros,
		&i.IncurredAt,
		&i.RawPayload,
		&i.RecordedAt,
	)
	return i, err
}

const getProviderCostByProviderRecord = `-- name: GetProviderCostByProviderRecord :one
SELECT id, provider_id, operation_id, provider_record_id, product, currency, amount_micros, incurred_at, raw_payload, recorded_at
FROM provider_costs
WHERE provider_id = $1
  AND provider_record_id = $2
LIMIT 1
`

type GetProviderCostByProviderRecordParams struct {
	ProviderID       uuid.UUID `db:"provider_id" json:"provider_id"`
	ProviderRecordID string    `db:"provider_record_id" json:"provider_record_id"`
}

func (q *Queries) GetProviderCostByProviderRecord(ctx context.Context, arg GetProviderCostByProviderRecordParams) (ProviderCost, error) {
	row := q.db.QueryRow(ctx, getProviderCostByProviderRecord, arg.ProviderID, arg.ProviderRecordID)
	var i ProviderCost
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.OperationID,
		&i.ProviderRecordID,
		&i.Product,
		&i.Currency,
		&i.AmountMicros,
		&i.IncurredAt,
		&i.RawPayload,
		&i.RecordedAt,
	)
	return i, err
}

const listProviderCostsByOperation = `-- name: ListProviderCostsByOperation :many
SELECT id, provider_id, operation_id, provider_record_id, product, currency, amount_micros, incurred_at, raw_payload, recorded_at
FROM provider_costs
WHERE operation_id = $1
ORDER BY incurred_at, id
`

func (q *Queries) ListProviderCostsByOperation(ctx context.Context, operationID uuid.UUID) ([]ProviderCost, error) {
	rows, err := q.db.Query(ctx, listProviderCostsByOperation, operationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderCost{}
	for rows.Next() {
		var i ProviderCost
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.OperationID,
			&i.ProviderRecordID,
			&i.Product,
			&i.Currency,
			&i.AmountMicros,
			&i.IncurredAt,
			&i.RawPayload,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
