// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routing.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCarrierRate = `-- name: CreateCarrierRate :one
INSERT INTO carrier_rates (
    carrier_connection_id,
    destination_prefix,
    rate_micros,
    billing_currency,
    effective_at,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, carrier_connection_id, destination_prefix, rate_micros, billing_currency, effective_at, expires_at, created_at
`

type CreateCarrierRateParams struct {
	CarrierConnectionID uuid.UUID          `db:"carrier_connection_id" json:"carrier_connection_id"`
	DestinationPrefix   string             `db:"destination_prefix" json:"destination_prefix"`
	RateMicros          int64              `db:"rate_micros" json:"rate_micros"`
	BillingCurrency     string             `db:"billing_currency" json:"billing_currency"`
	EffectiveAt         pgtype.Timestamptz `db:"effective_at" json:"effective_at"`
	ExpiresAt           pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateCarrierRate(ctx context.Context, arg CreateCarrierRateParams) (CarrierRate, error) {
	row := q.db.QueryRow(ctx, createCarrierRate,
		arg.CarrierConnectionID,
		arg.DestinationPrefix,
		arg.RateMicros,
		arg.BillingCurrency,
		arg.EffectiveAt,
		arg.ExpiresAt,
	)
	var i CarrierRate
	err := row.Scan(
		&i.ID,
		&i.CarrierConnectionID,
		&i.DestinationPrefix,
		&i.RateMicros,
		&i.BillingCurrency,
		&i.EffectiveAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRoutingDecision = `-- name: CreateRoutingDecision :one
INSERT INTO routing_decisions (
    organization_id,
    destination,
    selected_carrier_connection_id,
    selected_trunk_id,
    selected_trunk_endpoint_id,
    candidate_count
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, organization_id, destination, selected_carrier_connection_id, selected_trunk_id, selected_trunk_endpoint_id, candidate_count, created_at
`

type CreateRoutingDecisionParams struct {
	OrganizationID              uuid.UUID `db:"organization_id" json:"organization_id"`
	Destination                 string    `db:"destination" json:"destination"`
	SelectedCarrierConnectionID uuid.UUID `db:"selected_carrier_connection_id" json:"selected_carrier_connection_id"`
	SelectedTrunkID             uuid.UUID `db:"selected_trunk_id" json:"selected_trunk_id"`
	SelectedTrunkEndpointID     uuid.UUID `db:"selected_trunk_endpoint_id" json:"selected_trunk_endpoint_id"`
	CandidateCount              int32     `db:"candidate_count" json:"candidate_count"`
}

func (q *Queries) CreateRoutingDecision(ctx context.Context, arg CreateRoutingDecisionParams) (RoutingDecision, error) {
	row := q.db.QueryRow(ctx, createRoutingDecision,
		arg.OrganizationID,
		arg.Destination,
		arg.SelectedCarrierConnectionID,
		arg.SelectedTrunkID,
		arg.SelectedTrunkEndpointID,
		arg.CandidateCount,
	)
	var i RoutingDecision
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Destination,
		&i.SelectedCarrierConnectionID,
		&i.SelectedTrunkID,
		&i.SelectedTrunkEndpointID,
		&i.CandidateCount,
		&i.CreatedAt,
	)
	return i, err
}

const createRoutingDecisionCandidate = `-- name: CreateRoutingDecisionCandidate :exec
INSERT INTO routing_decision_candidates (
    routing_decision_id,
    rank,
    carrier_connection_id,
    trunk_id,
    trunk_endpoint_id,
    rate_micros,
    asr_basis_points,
    aloc_milliseconds,
    latency_milliseconds,
    packet_loss_basis_points,
    metrics_observed_at,
    score_micros
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
`

type CreateRoutingDecisionCandidateParams struct {
	RoutingDecisionID     uuid.UUID          `db:"routing_decision_id" json:"routing_decision_id"`
	Rank                  int32              `db:"rank" json:"rank"`
	CarrierConnectionID   uuid.UUID          `db:"carrier_connection_id" json:"carrier_connection_id"`
	TrunkID               uuid.UUID          `db:"trunk_id" json:"trunk_id"`
	TrunkEndpointID       uuid.UUID          `db:"trunk_endpoint_id" json:"trunk_endpoint_id"`
	RateMicros            int64              `db:"rate_micros" json:"rate_micros"`
	AsrBasisPoints        int32              `db:"asr_basis_points" json:"asr_basis_points"`
	AlocMilliseconds      int64              `db:"aloc_milliseconds" json:"aloc_milliseconds"`
	LatencyMilliseconds   int32              `db:"latency_milliseconds" json:"latency_milliseconds"`
	PacketLossBasisPoints int32              `db:"packet_loss_basis_points" json:"packet_loss_basis_points"`
	MetricsObservedAt     pgtype.Timestamptz `db:"metrics_observed_at" json:"metrics_observed_at"`
	ScoreMicros           int64              `db:"score_micros" json:"score_micros"`
}

func (q *Queries) CreateRoutingDecisionCandidate(ctx context.Context, arg CreateRoutingDecisionCandidateParams) error {
	_, err := q.db.Exec(ctx, createRoutingDecisionCandidate,
		arg.RoutingDecisionID,
		arg.Rank,
		arg.CarrierConnectionID,
		arg.TrunkID,
		arg.TrunkEndpointID,
		arg.RateMicros,
		arg.AsrBasisPoints,
		arg.AlocMilliseconds,
		arg.LatencyMilliseconds,
		arg.PacketLossBasisPoints,
		arg.MetricsObservedAt,
		arg.ScoreMicros,
	)
	return err
}

const listManagedRouteCandidates = `-- name: ListManagedRouteCandidates :many
SELECT
    cc.id AS carrier_connection_id,
    cc.max_cps,
    cc.max_concurrent_calls,
    cc.max_daily_minutes,
    t.id AS trunk_id,
    te.id AS trunk_endpoint_id,
    te.host,
    te.port,
    te.transport,
    te.health_status,
    rate.rate_micros,
    metrics.asr_basis_points,
    metrics.aloc_milliseconds,
    metrics.latency_milliseconds,
    metrics.packet_loss_basis_points,
    metrics.observed_at
FROM trunks AS t
JOIN carrier_connections AS cc ON cc.id = t.carrier_connection_id
JOIN trunk_endpoints AS te ON te.trunk_id = t.id
JOIN carrier_route_metrics AS metrics ON metrics.trunk_endpoint_id = te.id
JOIN LATERAL (
    SELECT cr.rate_micros
    FROM carrier_rates AS cr
    WHERE cr.carrier_connection_id = cc.id
      AND cr.billing_currency = 'USD'
      AND $1::TEXT LIKE cr.destination_prefix || '%'
      AND cr.effective_at <= $2
      AND (cr.expires_at IS NULL OR cr.expires_at > $2)
    ORDER BY length(cr.destination_prefix) DESC, cr.effective_at DESC
    LIMIT 1
) AS rate ON true
WHERE t.organization_id IS NULL
  AND t.provisioning_mode = 'managed'
  AND t.status = 'active'
  AND t.direction IN ('outbound', 'bidirectional')
  AND cc.scope = 'platform'
  AND cc.organization_id IS NULL
  AND cc.status = 'active'
  AND te.organization_id IS NULL
  AND te.enabled = true
  AND te.direction IN ('outbound', 'bidirectional')
`

type ListManagedRouteCandidatesParams struct {
	DestinationDigits string             `db:"destination_digits" json:"destination_digits"`
	ResolvedAt        pgtype.Timestamptz `db:"resolved_at" json:"resolved_at"`
}

type ListManagedRouteCandidatesRow struct {
	CarrierConnectionID   uuid.UUID          `db:"carrier_connection_id" json:"carrier_connection_id"`
	MaxCps                int32              `db:"max_cps" json:"max_cps"`
	MaxConcurrentCalls    int32              `db:"max_concurrent_calls" json:"max_concurrent_calls"`
	MaxDailyMinutes       *int64             `db:"max_daily_minutes" json:"max_daily_minutes"`
	TrunkID               uuid.UUID          `db:"trunk_id" json:"trunk_id"`
	TrunkEndpointID       uuid.UUID          `db:"trunk_endpoint_id" json:"trunk_endpoint_id"`
	Host                  string             `db:"host" json:"host"`
	Port                  int32              `db:"port" json:"port"`
	Transport             string             `db:"transport" json:"transport"`
	HealthStatus          string             `db:"health_status" json:"health_status"`
	RateMicros            int64              `db:"rate_micros" json:"rate_micros"`
	AsrBasisPoints        int32              `db:"asr_basis_points" json:"asr_basis_points"`
	AlocMilliseconds      int64              `db:"aloc_milliseconds" json:"aloc_milliseconds"`
	LatencyMilliseconds   int32              `db:"latency_milliseconds" json:"latency_milliseconds"`
	PacketLossBasisPoints int32              `db:"packet_loss_basis_points" json:"packet_loss_basis_points"`
	ObservedAt            pgtype.Timestamptz `db:"observed_at" json:"observed_at"`
}

func (q *Queries) ListManagedRouteCandidates(ctx context.Context, arg ListManagedRouteCandidatesParams) ([]ListManagedRouteCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listManagedRouteCandidates, arg.DestinationDigits, arg.ResolvedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListManagedRouteCandidatesRow{}
	for rows.Next() {
		var i ListManagedRouteCandidatesRow
		if err := rows.Scan(
			&i.CarrierConnectionID,
			&i.MaxCps,
			&i.MaxConcurrentCalls,
			&i.MaxDailyMinutes,
			&i.TrunkID,
			&i.TrunkEndpointID,
			&i.Host,
			&i.Port,
			&i.Transport,
			&i.HealthStatus,
			&i.RateMicros,
			&i.AsrBasisPoints,
			&i.AlocMilliseconds,
			&i.LatencyMilliseconds,
			&i.PacketLossBasisPoints,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCarrierRouteMetrics = `-- name: UpsertCarrierRouteMetrics :one
INSERT INTO carrier_route_metrics (
    trunk_endpoint_id,
    asr_basis_points,
    aloc_milliseconds,
    latency_milliseconds,
    packet_loss_basis_points,
    sample_count,
    observed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (trunk_endpoint_id) DO UPDATE SET
    asr_basis_points = EXCLUDED.asr_basis_points,
    aloc_milliseconds = EXCLUDED.aloc_milliseconds,
    latency_milliseconds = EXCLUDED.latency_milliseconds,
    packet_loss_basis_points = EXCLUDED.packet_loss_basis_points,
    sample_count = EXCLUDED.sample_count,
    observed_at = EXCLUDED.observed_at,
    updated_at = now()
WHERE carrier_route_metrics.observed_at <= EXCLUDED.observed_at
RETURNING trunk_endpoint_id, asr_basis_points, aloc_milliseconds, latency_milliseconds, packet_loss_basis_points, sample_count, observed_at, updated_at
`

type UpsertCarrierRouteMetricsParams struct {
	TrunkEndpointID       uuid.UUID          `db:"trunk_endpoint_id" json:"trunk_endpoint_id"`
	AsrBasisPoints        int32              `db:"asr_basis_points" json:"asr_basis_points"`
	AlocMilliseconds      int64              `db:"aloc_milliseconds" json:"aloc_milliseconds"`
	LatencyMilliseconds   int32              `db:"latency_milliseconds" json:"latency_milliseconds"`
	PacketLossBasisPoints int32              `db:"packet_loss_basis_points" json:"packet_loss_basis_points"`
	SampleCount           int64              `db:"sample_count" json:"sample_count"`
	ObservedAt            pgtype.Timestamptz `db:"observed_at" json:"observed_at"`
}

func (q *Queries) UpsertCarrierRouteMetrics(ctx context.Context, arg UpsertCarrierRouteMetricsParams) (CarrierRouteMetric, error) {
	row := q.db.QueryRow(ctx, upsertCarrierRouteMetrics,
		arg.TrunkEndpointID,
		arg.AsrBasisPoints,
		arg.AlocMilliseconds,
		arg.LatencyMilliseconds,
		arg.PacketLossBasisPoints,
		arg.SampleCount,
		arg.ObservedAt,
	)
	var i CarrierRouteMetric
	err := row.Scan(
		&i.TrunkEndpointID,
		&i.AsrBasisPoints,
		&i.AlocMilliseconds,
		&i.LatencyMilliseconds,
		&i.PacketLossBasisPoints,
		&i.SampleCount,
		&i.ObservedAt,
		&i.UpdatedAt,
	)
	return i, err
}
