// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtimes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createRuntime = `-- name: CreateRuntime :one
INSERT INTO runtimes (
    organization_id,
    name,
    region
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, organization_id, name, status, version, region, capabilities, capacity, active_sessions, last_seen_at, created_at, updated_at
`

type CreateRuntimeParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	Name           string    `db:"name" json:"name"`
	Region         *string   `db:"region" json:"region"`
}

func (q *Queries) CreateRuntime(ctx context.Context, arg CreateRuntimeParams) (Runtime, error) {
	row := q.db.QueryRow(ctx, createRuntime, arg.OrganizationID, arg.Name, arg.Region)
	var i Runtime
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.Region,
		&i.Capabilities,
		&i.Capacity,
		&i.ActiveSessions,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRuntime = `-- name: GetRuntime :one
SELECT id, organization_id, name, status, version, region, capabilities, capacity, active_sessions, last_seen_at, created_at, updated_at
FROM runtimes
WHERE organization_id = $1
  AND id = $2
`

type GetRuntimeParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetRuntime(ctx context.Context, arg GetRuntimeParams) (Runtime, error) {
	row := q.db.QueryRow(ctx, getRuntime, arg.OrganizationID, arg.ID)
	var i Runtime
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.Region,
		&i.Capabilities,
		&i.Capacity,
		&i.ActiveSessions,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const heartbeatRuntime = `-- name: HeartbeatRuntime :one
UPDATE runtimes
SET
    version = $1,
    capabilities = $2,
    capacity = $3,
    active_sessions = $4,
    last_seen_at = NOW()
WHERE organization_id = $5
  AND id = $6
  AND status = 'active'
RETURNING id, organization_id, name, status, version, region, capabilities, capacity, active_sessions, last_seen_at, created_at, updated_at
`

type HeartbeatRuntimeParams struct {
	Version        *string   `db:"version" json:"version"`
	Capabilities   []string  `db:"capabilities" json:"capabilities"`
	Capacity       int32     `db:"capacity" json:"capacity"`
	ActiveSessions int32     `db:"active_sessions" json:"active_sessions"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) HeartbeatRuntime(ctx context.Context, arg HeartbeatRuntimeParams) (Runtime, error) {
	row := q.db.QueryRow(ctx, heartbeatRuntime,
		arg.Version,
		arg.Capabilities,
		arg.Capacity,
		arg.ActiveSessions,
		arg.OrganizationID,
		arg.ID,
	)
	var i Runtime
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.Region,
		&i.Capabilities,
		&i.Capacity,
		&i.ActiveSessions,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRuntimes = `-- name: ListRuntimes :many
SELECT id, organization_id, name, status, version, region, capabilities, capacity, active_sessions, last_seen_at, created_at, updated_at
FROM runtimes
WHERE organization_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListRuntimes(ctx context.Context, organizationID uuid.UUID) ([]Runtime, error) {
	rows, err := q.db.Query(ctx, listRuntimes, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Runtime{}
	for rows.Next() {
		var i Runtime
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Status,
			&i.Version,
			&i.Region,
			&i.Capabilities,
			&i.Capacity,
			&i.ActiveSessions,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
