// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scim_provisioning.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSCIMGroups = `-- name: CountSCIMGroups :one
SELECT COUNT(*)::BIGINT
FROM scim_groups
WHERE organization_id = $1
`

func (q *Queries) CountSCIMGroups(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSCIMGroups, organizationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countSCIMUsers = `-- name: CountSCIMUsers :one
SELECT COUNT(*)::BIGINT
FROM scim_user_profiles AS profile
WHERE profile.organization_id = $1
`

func (q *Queries) CountSCIMUsers(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSCIMUsers, organizationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createSCIMGroup = `-- name: CreateSCIMGroup :one
INSERT INTO scim_groups (
    id,
    organization_id,
    external_id,
    display_name
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, organization_id, external_id, display_name, created_at, updated_at
`

type CreateSCIMGroupParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ExternalID     *string   `db:"external_id" json:"external_id"`
	DisplayName    string    `db:"display_name" json:"display_name"`
}

func (q *Queries) CreateSCIMGroup(ctx context.Context, arg CreateSCIMGroupParams) (ScimGroup, error) {
	row := q.db.QueryRow(ctx, createSCIMGroup,
		arg.ID,
		arg.OrganizationID,
		arg.ExternalID,
		arg.DisplayName,
	)
	var i ScimGroup
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ExternalID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSCIMUser = `-- name: CreateSCIMUser :one
WITH existing_user AS (
    SELECT users.id
    FROM users
    WHERE users.email = $1
), created_user AS (
    INSERT INTO users (name, email, email_verified)
    SELECT $2, $1, TRUE
    WHERE NOT EXISTS (SELECT 1 FROM existing_user)
    RETURNING id
), target_user AS (
    SELECT id FROM existing_user
    UNION ALL
    SELECT id FROM created_user
), membership AS (
    INSERT INTO organization_members (
        organization_id,
        user_id,
        role,
        status
    )
    SELECT
        $3,
        target_user.id,
        'member',
        CASE WHEN $4::boolean THEN 'active' ELSE 'disabled' END
    FROM target_user
    ON CONFLICT (organization_id, user_id)
    DO UPDATE SET
        status = CASE
            WHEN organization_members.role = 'owner' THEN organization_members.status
            ELSE EXCLUDED.status
        END,
        updated_at = NOW()
    RETURNING user_id
), identity AS (
    INSERT INTO scim_identities (
        id,
        organization_id,
        user_id,
        external_id
    )
    SELECT
        $5,
        $3,
        membership.user_id,
        $6
    FROM membership
    RETURNING id, organization_id, user_id, external_id, created_at, updated_at
), profile AS (
    INSERT INTO scim_user_profiles (
        identity_id,
        organization_id,
        user_id,
        user_name,
        display_name,
        active
    )
    SELECT
        identity.id,
        identity.organization_id,
        identity.user_id,
        $1,
        $2,
        $4
    FROM identity
    RETURNING identity_id, organization_id, user_id, user_name, display_name, active, created_at, updated_at
)
SELECT
    profile.identity_id AS id,
    profile.organization_id,
    profile.user_id,
    identity.external_id,
    profile.user_name::TEXT AS user_name,
    profile.display_name,
    profile.active,
    profile.created_at,
    profile.updated_at
FROM profile
JOIN identity ON identity.id = profile.identity_id
`

type CreateSCIMUserParams struct {
	UserName       string    `db:"user_name" json:"user_name"`
	DisplayName    *string   `db:"display_name" json:"display_name"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	Active         bool      `db:"active" json:"active"`
	ID             uuid.UUID `db:"id" json:"id"`
	ExternalID     string    `db:"external_id" json:"external_id"`
}

type CreateSCIMUserRow struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	UserID         uuid.UUID          `db:"user_id" json:"user_id"`
	ExternalID     string             `db:"external_id" json:"external_id"`
	UserName       string             `db:"user_name" json:"user_name"`
	DisplayName    *string            `db:"display_name" json:"display_name"`
	Active         bool               `db:"active" json:"active"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateSCIMUser(ctx context.Context, arg CreateSCIMUserParams) (CreateSCIMUserRow, error) {
	row := q.db.QueryRow(ctx, createSCIMUser,
		arg.UserName,
		arg.DisplayName,
		arg.OrganizationID,
		arg.Active,
		arg.ID,
		arg.ExternalID,
	)
	var i CreateSCIMUserRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.ExternalID,
		&i.UserName,
		&i.DisplayName,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSCIMGroup = `-- name: DeleteSCIMGroup :exec
DELETE FROM scim_groups
WHERE organization_id = $1
  AND id = $2
`

type DeleteSCIMGroupParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) DeleteSCIMGroup(ctx context.Context, arg DeleteSCIMGroupParams) error {
	_, err := q.db.Exec(ctx, deleteSCIMGroup, arg.OrganizationID, arg.ID)
	return err
}

const deleteSCIMUser = `-- name: DeleteSCIMUser :one
WITH target AS (
    SELECT profile.identity_id, profile.user_id
    FROM scim_user_profiles AS profile
    JOIN organization_members AS member
      ON member.organization_id = profile.organization_id
     AND member.user_id = profile.user_id
    WHERE profile.organization_id = $1
      AND profile.identity_id = $2
      AND member.role <> 'owner'
), disabled AS (
    UPDATE organization_members AS member
    SET status = 'disabled', updated_at = NOW()
    FROM target
    WHERE member.organization_id = $1
      AND member.user_id = target.user_id
    RETURNING member.user_id
), deleted AS (
    DELETE FROM scim_identities AS identity
    USING target
    WHERE identity.organization_id = $1
      AND identity.id = target.identity_id
    RETURNING identity.id
)
SELECT id FROM deleted
`

type DeleteSCIMUserParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) DeleteSCIMUser(ctx context.Context, arg DeleteSCIMUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteSCIMUser, arg.OrganizationID, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getSCIMGroup = `-- name: GetSCIMGroup :one
SELECT id, organization_id, external_id, display_name, created_at, updated_at
FROM scim_groups
WHERE organization_id = $1
  AND id = $2
LIMIT 1
`

type GetSCIMGroupParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetSCIMGroup(ctx context.Context, arg GetSCIMGroupParams) (ScimGroup, error) {
	row := q.db.QueryRow(ctx, getSCIMGroup, arg.OrganizationID, arg.ID)
	var i ScimGroup
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ExternalID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSCIMGroupByDisplayName = `-- name: GetSCIMGroupByDisplayName :one
SELECT id, organization_id, external_id, display_name, created_at, updated_at
FROM scim_groups
WHERE organization_id = $1
  AND display_name = $2
LIMIT 1
`

type GetSCIMGroupByDisplayNameParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	DisplayName    string    `db:"display_name" json:"display_name"`
}

func (q *Queries) GetSCIMGroupByDisplayName(ctx context.Context, arg GetSCIMGroupByDisplayNameParams) (ScimGroup, error) {
	row := q.db.QueryRow(ctx, getSCIMGroupByDisplayName, arg.OrganizationID, arg.DisplayName)
	var i ScimGroup
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ExternalID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSCIMUser = `-- name: GetSCIMUser :one
SELECT
    profile.identity_id AS id,
    profile.organization_id,
    profile.user_id,
    identity.external_id,
    profile.user_name::TEXT AS user_name,
    profile.display_name,
    profile.active,
    profile.created_at,
    profile.updated_at
FROM scim_user_profiles AS profile
JOIN scim_identities AS identity
  ON identity.id = profile.identity_id
 AND identity.organization_id = profile.organization_id
WHERE profile.organization_id = $1
  AND profile.identity_id = $2
LIMIT 1
`

type GetSCIMUserParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

type GetSCIMUserRow struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	UserID         uuid.UUID          `db:"user_id" json:"user_id"`
	ExternalID     string             `db:"external_id" json:"external_id"`
	UserName       string             `db:"user_name" json:"user_name"`
	DisplayName    *string            `db:"display_name" json:"display_name"`
	Active         bool               `db:"active" json:"active"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetSCIMUser(ctx context.Context, arg GetSCIMUserParams) (GetSCIMUserRow, error) {
	row := q.db.QueryRow(ctx, getSCIMUser, arg.OrganizationID, arg.ID)
	var i GetSCIMUserRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.ExternalID,
		&i.UserName,
		&i.DisplayName,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSCIMUserByUserName = `-- name: GetSCIMUserByUserName :one
SELECT
    profile.identity_id AS id,
    profile.organization_id,
    profile.user_id,
    identity.external_id,
    profile.user_name::TEXT AS user_name,
    profile.display_name,
    profile.active,
    profile.created_at,
    profile.updated_at
FROM scim_user_profiles AS profile
JOIN scim_identities AS identity
  ON identity.id = profile.identity_id
 AND identity.organization_id = profile.organization_id
WHERE profile.organization_id = $1
  AND profile.user_name = $2
LIMIT 1
`

type GetSCIMUserByUserNameParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	UserName       string    `db:"user_name" json:"user_name"`
}

type GetSCIMUserByUserNameRow struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	UserID         uuid.UUID          `db:"user_id" json:"user_id"`
	ExternalID     string             `db:"external_id" json:"external_id"`
	UserName       string             `db:"user_name" json:"user_name"`
	DisplayName    *string            `db:"display_name" json:"display_name"`
	Active         bool               `db:"active" json:"active"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetSCIMUserByUserName(ctx context.Context, arg GetSCIMUserByUserNameParams) (GetSCIMUserByUserNameRow, error) {
	row := q.db.QueryRow(ctx, getSCIMUserByUserName, arg.OrganizationID, arg.UserName)
	var i GetSCIMUserByUserNameRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.ExternalID,
		&i.UserName,
		&i.DisplayName,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSCIMGroupMembers = `-- name: ListSCIMGroupMembers :many
SELECT
    profile.identity_id AS id,
    profile.user_name::TEXT AS user_name,
    profile.display_name
FROM scim_group_members AS member
JOIN scim_user_profiles AS profile
  ON profile.organization_id = member.organization_id
 AND profile.identity_id = member.identity_id
WHERE member.organization_id = $1
  AND member.group_id = $2
ORDER BY profile.user_name
`

type ListSCIMGroupMembersParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	GroupID        uuid.UUID `db:"group_id" json:"group_id"`
}

type ListSCIMGroupMembersRow struct {
	ID          uuid.UUID `db:"id" json:"id"`
	UserName    string    `db:"user_name" json:"user_name"`
	DisplayName *string   `db:"display_name" json:"display_name"`
}

func (q *Queries) ListSCIMGroupMembers(ctx context.Context, arg ListSCIMGroupMembersParams) ([]ListSCIMGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listSCIMGroupMembers, arg.OrganizationID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSCIMGroupMembersRow{}
	for rows.Next() {
		var i ListSCIMGroupMembersRow
		if err := rows.Scan(&i.ID, &i.UserName, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSCIMGroups = `-- name: ListSCIMGroups :many
SELECT id, organization_id, external_id, display_name, created_at, updated_at
FROM scim_groups
WHERE organization_id = $1
ORDER BY created_at, id
LIMIT $3
OFFSET $2
`

type ListSCIMGroupsParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	OffsetCount    int32     `db:"offset_count" json:"offset_count"`
	LimitCount     int32     `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListSCIMGroups(ctx context.Context, arg ListSCIMGroupsParams) ([]ScimGroup, error) {
	rows, err := q.db.Query(ctx, listSCIMGroups, arg.OrganizationID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScimGroup{}
	for rows.Next() {
		var i ScimGroup
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ExternalID,
			&i.DisplayName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSCIMUsers = `-- name: ListSCIMUsers :many
SELECT
    profile.identity_id AS id,
    profile.organization_id,
    profile.user_id,
    identity.external_id,
    profile.user_name::TEXT AS user_name,
    profile.display_name,
    profile.active,
    profile.created_at,
    profile.updated_at
FROM scim_user_profiles AS profile
JOIN scim_identities AS identity
  ON identity.id = profile.identity_id
 AND identity.organization_id = profile.organization_id
WHERE profile.organization_id = $1
ORDER BY profile.created_at, profile.identity_id
LIMIT $3
OFFSET $2
`

type ListSCIMUsersParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	OffsetCount    int32     `db:"offset_count" json:"offset_count"`
	LimitCount     int32     `db:"limit_count" json:"limit_count"`
}

type ListSCIMUsersRow struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	UserID         uuid.UUID          `db:"user_id" json:"user_id"`
	ExternalID     string             `db:"external_id" json:"external_id"`
	UserName       string             `db:"user_name" json:"user_name"`
	DisplayName    *string            `db:"display_name" json:"display_name"`
	Active         bool               `db:"active" json:"active"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListSCIMUsers(ctx context.Context, arg ListSCIMUsersParams) ([]ListSCIMUsersRow, error) {
	rows, err := q.db.Query(ctx, listSCIMUsers, arg.OrganizationID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSCIMUsersRow{}
	for rows.Next() {
		var i ListSCIMUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.ExternalID,
			&i.UserName,
			&i.DisplayName,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceSCIMGroup = `-- name: ReplaceSCIMGroup :one
UPDATE scim_groups
SET
    external_id = $1,
    display_name = $2
WHERE organization_id = $3
  AND id = $4
RETURNING id, organization_id, external_id, display_name, created_at, updated_at
`

type ReplaceSCIMGroupParams struct {
	ExternalID     *string   `db:"external_id" json:"external_id"`
	DisplayName    string    `db:"display_name" json:"display_name"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) ReplaceSCIMGroup(ctx context.Context, arg ReplaceSCIMGroupParams) (ScimGroup, error) {
	row := q.db.QueryRow(ctx, replaceSCIMGroup,
		arg.ExternalID,
		arg.DisplayName,
		arg.OrganizationID,
		arg.ID,
	)
	var i ScimGroup
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ExternalID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const replaceSCIMGroupMembers = `-- name: ReplaceSCIMGroupMembers :many
WITH cleared AS (
    DELETE FROM scim_group_members AS member
    WHERE member.organization_id = $1
      AND member.group_id = $2
), requested AS (
    SELECT unnest($3::UUID[]) AS identity_id
), inserted AS (
    INSERT INTO scim_group_members (
        organization_id,
        group_id,
        identity_id
    )
    SELECT
        $1,
        $2,
        profile.identity_id
    FROM requested
    JOIN scim_user_profiles AS profile
      ON profile.organization_id = $1
     AND profile.identity_id = requested.identity_id
    RETURNING identity_id
)
SELECT inserted.identity_id AS id
FROM inserted
ORDER BY inserted.identity_id
`

type ReplaceSCIMGroupMembersParams struct {
	OrganizationID uuid.UUID   `db:"organization_id" json:"organization_id"`
	GroupID        uuid.UUID   `db:"group_id" json:"group_id"`
	MemberIds      []uuid.UUID `db:"member_ids" json:"member_ids"`
}

func (q *Queries) ReplaceSCIMGroupMembers(ctx context.Context, arg ReplaceSCIMGroupMembersParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, replaceSCIMGroupMembers, arg.OrganizationID, arg.GroupID, arg.MemberIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceSCIMUser = `-- name: ReplaceSCIMUser :one
WITH target AS (
    SELECT profile.identity_id, profile.user_id
    FROM scim_user_profiles AS profile
    WHERE profile.organization_id = $1
      AND profile.identity_id = $2
), membership AS (
    UPDATE organization_members AS member
    SET
        status = CASE
            WHEN member.role = 'owner' THEN member.status
            WHEN $3::boolean THEN 'active'
            ELSE 'disabled'
        END,
        updated_at = NOW()
    FROM target
    WHERE member.organization_id = $1
      AND member.user_id = target.user_id
    RETURNING member.user_id
), updated AS (
    UPDATE scim_user_profiles AS profile
    SET
        user_name = $4,
        display_name = $5,
        active = $3
    FROM target
    WHERE profile.organization_id = $1
      AND profile.identity_id = target.identity_id
    RETURNING profile.identity_id, profile.organization_id, profile.user_id, profile.user_name, profile.display_name, profile.active, profile.created_at, profile.updated_at
)
SELECT
    updated.identity_id AS id,
    updated.organization_id,
    updated.user_id,
    identity.external_id,
    updated.user_name::TEXT AS user_name,
    updated.display_name,
    updated.active,
    updated.created_at,
    updated.updated_at
FROM updated
JOIN scim_identities AS identity
  ON identity.id = updated.identity_id
 AND identity.organization_id = updated.organization_id
`

type ReplaceSCIMUserParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
	Active         bool      `db:"active" json:"active"`
	UserName       string    `db:"user_name" json:"user_name"`
	DisplayName    *string   `db:"display_name" json:"display_name"`
}

type ReplaceSCIMUserRow struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	UserID         uuid.UUID          `db:"user_id" json:"user_id"`
	ExternalID     string             `db:"external_id" json:"external_id"`
	UserName       string             `db:"user_name" json:"user_name"`
	DisplayName    *string            `db:"display_name" json:"display_name"`
	Active         bool               `db:"active" json:"active"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ReplaceSCIMUser(ctx context.Context, arg ReplaceSCIMUserParams) (ReplaceSCIMUserRow, error) {
	row := q.db.QueryRow(ctx, replaceSCIMUser,
		arg.OrganizationID,
		arg.ID,
		arg.Active,
		arg.UserName,
		arg.DisplayName,
	)
	var i ReplaceSCIMUserRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.ExternalID,
		&i.UserName,
		&i.DisplayName,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
