// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateSubscription = `-- name: ActivateSubscription :one
UPDATE subscriptions AS s
SET
    status = 'active',
    current_period_start = CASE
        WHEN s.status = 'active' THEN s.current_period_start
        ELSE $1
    END,
    current_period_end = CASE
        WHEN s.status = 'active' THEN s.current_period_end
        ELSE $2
    END,
    started_at = COALESCE(s.started_at, $1),
    updated_at = NOW()
WHERE s.id = $3
  AND s.organization_id = $4
  AND s.status IN ('pending', 'past_due', 'active')
  AND EXISTS (
      SELECT 1
      FROM organizations AS o
      WHERE o.id = s.organization_id
        AND o.status = 'active'
        AND o.deleted_at IS NULL
  )
RETURNING s.id, s.organization_id, s.plan_id, s.status, s.currency, s.amount_micros, s.interval, s.current_period_start, s.current_period_end, s.cancel_at_period_end, s.started_at, s.cancelled_at, s.created_at, s.updated_at
`

type ActivateSubscriptionParams struct {
	CurrentPeriodStart pgtype.Timestamptz `db:"current_period_start" json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz `db:"current_period_end" json:"current_period_end"`
	ID                 uuid.UUID          `db:"id" json:"id"`
	OrganizationID     uuid.UUID          `db:"organization_id" json:"organization_id"`
}

func (q *Queries) ActivateSubscription(ctx context.Context, arg ActivateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, activateSubscription,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.ID,
		arg.OrganizationID,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlanID,
		&i.Status,
		&i.Currency,
		&i.AmountMicros,
		&i.Interval,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.StartedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelSubscription = `-- name: CancelSubscription :one
UPDATE subscriptions
SET
    status = 'cancelled',
    cancel_at_period_end = false,
    cancelled_at = $1,
    updated_at = NOW()
WHERE id = $2
  AND organization_id = $3
  AND status IN ('pending', 'active', 'past_due')
RETURNING id, organization_id, plan_id, status, currency, amount_micros, interval, current_period_start, current_period_end, cancel_at_period_end, started_at, cancelled_at, created_at, updated_at
`

type CancelSubscriptionParams struct {
	CancelledAt    pgtype.Timestamptz `db:"cancelled_at" json:"cancelled_at"`
	ID             uuid.UUID          `db:"id" json:"id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
}

func (q *Queries) CancelSubscription(ctx context.Context, arg CancelSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, cancelSubscription, arg.CancelledAt, arg.ID, arg.OrganizationID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlanID,
		&i.Status,
		&i.Currency,
		&i.AmountMicros,
		&i.Interval,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.StartedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
    organization_id,
    plan_id,
    status,
    currency,
    amount_micros,
    interval
)
SELECT
    o.id,
    p.id,
    'pending',
    p.currency,
    p.amount_micros,
    p.interval
FROM organizations AS o
JOIN subscription_plans AS p
  ON p.id = $1
 AND p.status = 'active'
WHERE o.id = $2
  AND o.status = 'active'
  AND o.deleted_at IS NULL
RETURNING id, organization_id, plan_id, status, currency, amount_micros, interval, current_period_start, current_period_end, cancel_at_period_end, started_at, cancelled_at, created_at, updated_at
`

type CreateSubscriptionParams struct {
	PlanID         uuid.UUID `db:"plan_id" json:"plan_id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription, arg.PlanID, arg.OrganizationID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlanID,
		&i.Status,
		&i.Currency,
		&i.AmountMicros,
		&i.Interval,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.StartedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrentSubscriptionByOrganization = `-- name: GetCurrentSubscriptionByOrganization :one
SELECT s.id, s.organization_id, s.plan_id, s.status, s.currency, s.amount_micros, s.interval, s.current_period_start, s.current_period_end, s.cancel_at_period_end, s.started_at, s.cancelled_at, s.created_at, s.updated_at
FROM subscriptions AS s
JOIN organizations AS o
  ON o.id = s.organization_id
WHERE s.organization_id = $1
  AND s.status IN ('pending', 'active', 'past_due')
  AND o.status = 'active'
  AND o.deleted_at IS NULL
ORDER BY s.created_at DESC
LIMIT 1
`

func (q *Queries) GetCurrentSubscriptionByOrganization(ctx context.Context, organizationID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getCurrentSubscriptionByOrganization, organizationID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlanID,
		&i.Status,
		&i.Currency,
		&i.AmountMicros,
		&i.Interval,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.StartedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT s.id, s.organization_id, s.plan_id, s.status, s.currency, s.amount_micros, s.interval, s.current_period_start, s.current_period_end, s.cancel_at_period_end, s.started_at, s.cancelled_at, s.created_at, s.updated_at
FROM subscriptions AS s
JOIN organizations AS o
  ON o.id = s.organization_id
WHERE s.id = $1
  AND s.organization_id = $2
  AND o.status = 'active'
  AND o.deleted_at IS NULL
LIMIT 1
`

type GetSubscriptionByIDParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetSubscriptionByID(ctx context.Context, arg GetSubscriptionByIDParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, arg.ID, arg.OrganizationID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlanID,
		&i.Status,
		&i.Currency,
		&i.AmountMicros,
		&i.Interval,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.StartedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubscriptionsByOrganization = `-- name: ListSubscriptionsByOrganization :many
SELECT s.id, s.organization_id, s.plan_id, s.status, s.currency, s.amount_micros, s.interval, s.current_period_start, s.current_period_end, s.cancel_at_period_end, s.started_at, s.cancelled_at, s.created_at, s.updated_at
FROM subscriptions AS s
JOIN organizations AS o
  ON o.id = s.organization_id
WHERE s.organization_id = $1
  AND o.status = 'active'
  AND o.deleted_at IS NULL
ORDER BY s.created_at DESC, s.id DESC
LIMIT $3
OFFSET $2
`

type ListSubscriptionsByOrganizationParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	OffsetCount    int32     `db:"offset_count" json:"offset_count"`
	LimitCount     int32     `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListSubscriptionsByOrganization(ctx context.Context, arg ListSubscriptionsByOrganizationParams) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsByOrganization, arg.OrganizationID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PlanID,
			&i.Status,
			&i.Currency,
			&i.AmountMicros,
			&i.Interval,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.CancelAtPeriodEnd,
			&i.StartedAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSubscriptionPastDue = `-- name: MarkSubscriptionPastDue :one
UPDATE subscriptions
SET
    status = 'past_due',
    updated_at = NOW()
WHERE id = $1
  AND organization_id = $2
  AND status = 'active'
RETURNING id, organization_id, plan_id, status, currency, amount_micros, interval, current_period_start, current_period_end, cancel_at_period_end, started_at, cancelled_at, created_at, updated_at
`

type MarkSubscriptionPastDueParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) MarkSubscriptionPastDue(ctx context.Context, arg MarkSubscriptionPastDueParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, markSubscriptionPastDue, arg.ID, arg.OrganizationID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlanID,
		&i.Status,
		&i.Currency,
		&i.AmountMicros,
		&i.Interval,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.StartedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionCancelAtPeriodEnd = `-- name: UpdateSubscriptionCancelAtPeriodEnd :one
UPDATE subscriptions
SET
    cancel_at_period_end = $1,
    updated_at = NOW()
WHERE id = $2
  AND organization_id = $3
  AND status IN ('active', 'past_due')
RETURNING id, organization_id, plan_id, status, currency, amount_micros, interval, current_period_start, current_period_end, cancel_at_period_end, started_at, cancelled_at, created_at, updated_at
`

type UpdateSubscriptionCancelAtPeriodEndParams struct {
	CancelAtPeriodEnd bool      `db:"cancel_at_period_end" json:"cancel_at_period_end"`
	ID                uuid.UUID `db:"id" json:"id"`
	OrganizationID    uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) UpdateSubscriptionCancelAtPeriodEnd(ctx context.Context, arg UpdateSubscriptionCancelAtPeriodEndParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionCancelAtPeriodEnd, arg.CancelAtPeriodEnd, arg.ID, arg.OrganizationID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlanID,
		&i.Status,
		&i.Currency,
		&i.AmountMicros,
		&i.Interval,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.StartedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
