// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage_events.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUsageEvent = `-- name: CreateUsageEvent :one
INSERT INTO usage_events (
    organization_id, meter_id, quantity, source_type, source_id,
    idempotency_key, dimensions, occurred_at
)
SELECT m.organization_id, m.id, $1::BIGINT,
       $2::TEXT, $3::TEXT,
       $4::TEXT, $5::JSONB,
       $6::TIMESTAMPTZ
FROM meters AS m
JOIN organizations AS o ON o.id = m.organization_id
WHERE m.id = $7::UUID
  AND m.organization_id = $8::UUID
  AND m.active = true
  AND o.status = 'active'
  AND o.deleted_at IS NULL
ON CONFLICT (organization_id, idempotency_key) DO NOTHING
RETURNING id, organization_id, meter_id, quantity, source_type, source_id, idempotency_key, dimensions, occurred_at, created_at
`

type CreateUsageEventParams struct {
	Quantity       int64              `db:"quantity" json:"quantity"`
	SourceType     string             `db:"source_type" json:"source_type"`
	SourceID       string             `db:"source_id" json:"source_id"`
	IdempotencyKey string             `db:"idempotency_key" json:"idempotency_key"`
	Dimensions     []byte             `db:"dimensions" json:"dimensions"`
	OccurredAt     pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	MeterID        uuid.UUID          `db:"meter_id" json:"meter_id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
}

// Usage writes are internal observations, not charges. The database checks
// that the meter belongs to the organization and is currently active.
func (q *Queries) CreateUsageEvent(ctx context.Context, arg CreateUsageEventParams) (UsageEvent, error) {
	row := q.db.QueryRow(ctx, createUsageEvent,
		arg.Quantity,
		arg.SourceType,
		arg.SourceID,
		arg.IdempotencyKey,
		arg.Dimensions,
		arg.OccurredAt,
		arg.MeterID,
		arg.OrganizationID,
	)
	var i UsageEvent
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MeterID,
		&i.Quantity,
		&i.SourceType,
		&i.SourceID,
		&i.IdempotencyKey,
		&i.Dimensions,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMatchingUsageEventByKey = `-- name: GetMatchingUsageEventByKey :one
SELECT id, organization_id, meter_id, quantity, source_type, source_id, idempotency_key, dimensions, occurred_at, created_at FROM usage_events
WHERE organization_id = $1::UUID
  AND idempotency_key = $2::TEXT
  AND meter_id = $3::UUID
  AND quantity = $4::BIGINT
  AND source_type = $5::TEXT
  AND source_id = $6::TEXT
  AND dimensions = $7::JSONB
  AND occurred_at = $8::TIMESTAMPTZ
LIMIT 1
`

type GetMatchingUsageEventByKeyParams struct {
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	IdempotencyKey string             `db:"idempotency_key" json:"idempotency_key"`
	MeterID        uuid.UUID          `db:"meter_id" json:"meter_id"`
	Quantity       int64              `db:"quantity" json:"quantity"`
	SourceType     string             `db:"source_type" json:"source_type"`
	SourceID       string             `db:"source_id" json:"source_id"`
	Dimensions     []byte             `db:"dimensions" json:"dimensions"`
	OccurredAt     pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

// A repeated event is equivalent only if every material field matches.
// PostgreSQL JSONB equality avoids differences in key ordering and whitespace.
func (q *Queries) GetMatchingUsageEventByKey(ctx context.Context, arg GetMatchingUsageEventByKeyParams) (UsageEvent, error) {
	row := q.db.QueryRow(ctx, getMatchingUsageEventByKey,
		arg.OrganizationID,
		arg.IdempotencyKey,
		arg.MeterID,
		arg.Quantity,
		arg.SourceType,
		arg.SourceID,
		arg.Dimensions,
		arg.OccurredAt,
	)
	var i UsageEvent
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MeterID,
		&i.Quantity,
		&i.SourceType,
		&i.SourceID,
		&i.IdempotencyKey,
		&i.Dimensions,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUsageEvent = `-- name: GetUsageEvent :one
SELECT id, organization_id, meter_id, quantity, source_type, source_id, idempotency_key, dimensions, occurred_at, created_at FROM usage_events
WHERE organization_id = $1::UUID
  AND id = $2::UUID
LIMIT 1
`

type GetUsageEventParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ID             uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetUsageEvent(ctx context.Context, arg GetUsageEventParams) (UsageEvent, error) {
	row := q.db.QueryRow(ctx, getUsageEvent, arg.OrganizationID, arg.ID)
	var i UsageEvent
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MeterID,
		&i.Quantity,
		&i.SourceType,
		&i.SourceID,
		&i.IdempotencyKey,
		&i.Dimensions,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUsageEventByKey = `-- name: GetUsageEventByKey :one
SELECT id, organization_id, meter_id, quantity, source_type, source_id, idempotency_key, dimensions, occurred_at, created_at FROM usage_events
WHERE organization_id = $1::UUID
  AND idempotency_key = $2::TEXT
LIMIT 1
`

type GetUsageEventByKeyParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	IdempotencyKey string    `db:"idempotency_key" json:"idempotency_key"`
}

func (q *Queries) GetUsageEventByKey(ctx context.Context, arg GetUsageEventByKeyParams) (UsageEvent, error) {
	row := q.db.QueryRow(ctx, getUsageEventByKey, arg.OrganizationID, arg.IdempotencyKey)
	var i UsageEvent
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MeterID,
		&i.Quantity,
		&i.SourceType,
		&i.SourceID,
		&i.IdempotencyKey,
		&i.Dimensions,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listUsageEventsByMeter = `-- name: ListUsageEventsByMeter :many
SELECT id, organization_id, meter_id, quantity, source_type, source_id, idempotency_key, dimensions, occurred_at, created_at FROM usage_events
WHERE organization_id = $1::UUID
  AND meter_id = $2::UUID
ORDER BY occurred_at DESC, id DESC
LIMIT $3::INTEGER
`

type ListUsageEventsByMeterParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	MeterID        uuid.UUID `db:"meter_id" json:"meter_id"`
	RowLimit       int32     `db:"row_limit" json:"row_limit"`
}

func (q *Queries) ListUsageEventsByMeter(ctx context.Context, arg ListUsageEventsByMeterParams) ([]UsageEvent, error) {
	rows, err := q.db.Query(ctx, listUsageEventsByMeter, arg.OrganizationID, arg.MeterID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageEvent{}
	for rows.Next() {
		var i UsageEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MeterID,
			&i.Quantity,
			&i.SourceType,
			&i.SourceID,
			&i.IdempotencyKey,
			&i.Dimensions,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
