// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: voice_agent_tools.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createVoiceAgentTool = `-- name: CreateVoiceAgentTool :one
INSERT INTO voice_agent_tools (
    organization_id,
    voice_agent_id,
    type,
    name,
    description,
    parameters,
    endpoint_url,
    timeout_ms,
    enabled
)
SELECT
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
FROM voice_agents AS agent
WHERE agent.id = $2
  AND agent.organization_id = $1
  AND agent.status = 'active'
RETURNING id, organization_id, voice_agent_id, type, name, description, parameters, endpoint_url, method, headers, timeout_ms, enabled, created_at, updated_at
`

type CreateVoiceAgentToolParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	VoiceAgentID   uuid.UUID `db:"voice_agent_id" json:"voice_agent_id"`
	Type           string    `db:"type" json:"type"`
	Name           string    `db:"name" json:"name"`
	Description    string    `db:"description" json:"description"`
	Parameters     []byte    `db:"parameters" json:"parameters"`
	EndpointUrl    *string   `db:"endpoint_url" json:"endpoint_url"`
	TimeoutMs      int32     `db:"timeout_ms" json:"timeout_ms"`
	Enabled        bool      `db:"enabled" json:"enabled"`
}

func (q *Queries) CreateVoiceAgentTool(ctx context.Context, arg CreateVoiceAgentToolParams) (VoiceAgentTool, error) {
	row := q.db.QueryRow(ctx, createVoiceAgentTool,
		arg.OrganizationID,
		arg.VoiceAgentID,
		arg.Type,
		arg.Name,
		arg.Description,
		arg.Parameters,
		arg.EndpointUrl,
		arg.TimeoutMs,
		arg.Enabled,
	)
	var i VoiceAgentTool
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.VoiceAgentID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.Parameters,
		&i.EndpointUrl,
		&i.Method,
		&i.Headers,
		&i.TimeoutMs,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVoiceAgentTool = `-- name: DeleteVoiceAgentTool :exec
DELETE FROM voice_agent_tools
WHERE id = $1
  AND organization_id = $2
  AND voice_agent_id = $3
`

type DeleteVoiceAgentToolParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	VoiceAgentID   uuid.UUID `db:"voice_agent_id" json:"voice_agent_id"`
}

func (q *Queries) DeleteVoiceAgentTool(ctx context.Context, arg DeleteVoiceAgentToolParams) error {
	_, err := q.db.Exec(ctx, deleteVoiceAgentTool, arg.ID, arg.OrganizationID, arg.VoiceAgentID)
	return err
}

const getVoiceAgentToolByID = `-- name: GetVoiceAgentToolByID :one
SELECT tool.id, tool.organization_id, tool.voice_agent_id, tool.type, tool.name, tool.description, tool.parameters, tool.endpoint_url, tool.method, tool.headers, tool.timeout_ms, tool.enabled, tool.created_at, tool.updated_at
FROM voice_agent_tools AS tool
JOIN voice_agents AS agent ON agent.id = tool.voice_agent_id
WHERE tool.id = $1
  AND tool.organization_id = $2
  AND tool.voice_agent_id = $3
  AND agent.status = 'active'
LIMIT 1
`

type GetVoiceAgentToolByIDParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	VoiceAgentID   uuid.UUID `db:"voice_agent_id" json:"voice_agent_id"`
}

func (q *Queries) GetVoiceAgentToolByID(ctx context.Context, arg GetVoiceAgentToolByIDParams) (VoiceAgentTool, error) {
	row := q.db.QueryRow(ctx, getVoiceAgentToolByID, arg.ID, arg.OrganizationID, arg.VoiceAgentID)
	var i VoiceAgentTool
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.VoiceAgentID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.Parameters,
		&i.EndpointUrl,
		&i.Method,
		&i.Headers,
		&i.TimeoutMs,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVoiceAgentToolsByAgentID = `-- name: ListVoiceAgentToolsByAgentID :many
SELECT tool.id, tool.organization_id, tool.voice_agent_id, tool.type, tool.name, tool.description, tool.parameters, tool.endpoint_url, tool.method, tool.headers, tool.timeout_ms, tool.enabled, tool.created_at, tool.updated_at
FROM voice_agent_tools AS tool
JOIN voice_agents AS agent ON agent.id = tool.voice_agent_id
WHERE tool.organization_id = $1
  AND tool.voice_agent_id = $2
  AND agent.status = 'active'
ORDER BY tool.created_at ASC
`

type ListVoiceAgentToolsByAgentIDParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	VoiceAgentID   uuid.UUID `db:"voice_agent_id" json:"voice_agent_id"`
}

func (q *Queries) ListVoiceAgentToolsByAgentID(ctx context.Context, arg ListVoiceAgentToolsByAgentIDParams) ([]VoiceAgentTool, error) {
	rows, err := q.db.Query(ctx, listVoiceAgentToolsByAgentID, arg.OrganizationID, arg.VoiceAgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoiceAgentTool{}
	for rows.Next() {
		var i VoiceAgentTool
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.VoiceAgentID,
			&i.Type,
			&i.Name,
			&i.Description,
			&i.Parameters,
			&i.EndpointUrl,
			&i.Method,
			&i.Headers,
			&i.TimeoutMs,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVoiceAgentTool = `-- name: UpdateVoiceAgentTool :one
UPDATE voice_agent_tools
SET
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    parameters = COALESCE($3, parameters),
    endpoint_url = COALESCE($4, endpoint_url),
    timeout_ms = COALESCE($5, timeout_ms),
    enabled = COALESCE($6, enabled),
    updated_at = NOW()
WHERE id = $7
  AND organization_id = $8
  AND voice_agent_id = $9
RETURNING id, organization_id, voice_agent_id, type, name, description, parameters, endpoint_url, method, headers, timeout_ms, enabled, created_at, updated_at
`

type UpdateVoiceAgentToolParams struct {
	Name           *string   `db:"name" json:"name"`
	Description    *string   `db:"description" json:"description"`
	Parameters     []byte    `db:"parameters" json:"parameters"`
	EndpointUrl    *string   `db:"endpoint_url" json:"endpoint_url"`
	TimeoutMs      *int32    `db:"timeout_ms" json:"timeout_ms"`
	Enabled        *bool     `db:"enabled" json:"enabled"`
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	VoiceAgentID   uuid.UUID `db:"voice_agent_id" json:"voice_agent_id"`
}

func (q *Queries) UpdateVoiceAgentTool(ctx context.Context, arg UpdateVoiceAgentToolParams) (VoiceAgentTool, error) {
	row := q.db.QueryRow(ctx, updateVoiceAgentTool,
		arg.Name,
		arg.Description,
		arg.Parameters,
		arg.EndpointUrl,
		arg.TimeoutMs,
		arg.Enabled,
		arg.ID,
		arg.OrganizationID,
		arg.VoiceAgentID,
	)
	var i VoiceAgentTool
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.VoiceAgentID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.Parameters,
		&i.EndpointUrl,
		&i.Method,
		&i.Headers,
		&i.TimeoutMs,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
