// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: voice_rates.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVoiceRate = `-- name: CreateVoiceRate :one
INSERT INTO voice_rates (
    organization_id,
    destination_prefix,
    direction,
    currency,
    rate_micros,
    effective_at,
    expires_at
)
SELECT
    $1::UUID,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
WHERE $1::UUID IS NULL
   OR EXISTS (
       SELECT 1
       FROM organizations AS o
       WHERE o.id = $1::UUID
         AND o.status = 'active'
         AND o.deleted_at IS NULL
   )
RETURNING id, organization_id, destination_prefix, direction, currency, rate_micros, effective_at, expires_at, created_at
`

type CreateVoiceRateParams struct {
	OrganizationID    *uuid.UUID         `db:"organization_id" json:"organization_id"`
	DestinationPrefix string             `db:"destination_prefix" json:"destination_prefix"`
	Direction         string             `db:"direction" json:"direction"`
	Currency          string             `db:"currency" json:"currency"`
	RateMicros        int64              `db:"rate_micros" json:"rate_micros"`
	EffectiveAt       pgtype.Timestamptz `db:"effective_at" json:"effective_at"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateVoiceRate(ctx context.Context, arg CreateVoiceRateParams) (VoiceRate, error) {
	row := q.db.QueryRow(ctx, createVoiceRate,
		arg.OrganizationID,
		arg.DestinationPrefix,
		arg.Direction,
		arg.Currency,
		arg.RateMicros,
		arg.EffectiveAt,
		arg.ExpiresAt,
	)
	var i VoiceRate
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DestinationPrefix,
		&i.Direction,
		&i.Currency,
		&i.RateMicros,
		&i.EffectiveAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getVoiceRateByID = `-- name: GetVoiceRateByID :one
SELECT id, organization_id, destination_prefix, direction, currency, rate_micros, effective_at, expires_at, created_at
FROM voice_rates
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetVoiceRateByID(ctx context.Context, id uuid.UUID) (VoiceRate, error) {
	row := q.db.QueryRow(ctx, getVoiceRateByID, id)
	var i VoiceRate
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DestinationPrefix,
		&i.Direction,
		&i.Currency,
		&i.RateMicros,
		&i.EffectiveAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const resolveVoiceRate = `-- name: ResolveVoiceRate :one
SELECT vr.id, vr.organization_id, vr.destination_prefix, vr.direction, vr.currency, vr.rate_micros, vr.effective_at, vr.expires_at, vr.created_at
FROM voice_rates AS vr
JOIN organizations AS o
  ON o.id = $1
 AND o.status = 'active'
 AND o.deleted_at IS NULL
WHERE (vr.organization_id = o.id OR vr.organization_id IS NULL)
  AND vr.direction = $2
  AND vr.currency = $3
  AND $4::TEXT LIKE vr.destination_prefix || '%'
  AND vr.effective_at <= $5
  AND (vr.expires_at IS NULL OR vr.expires_at > $5)
ORDER BY
    (vr.organization_id IS NOT NULL) DESC,
    length(vr.destination_prefix) DESC,
    vr.effective_at DESC
LIMIT 1
`

type ResolveVoiceRateParams struct {
	OrganizationID    uuid.UUID          `db:"organization_id" json:"organization_id"`
	Direction         string             `db:"direction" json:"direction"`
	Currency          string             `db:"currency" json:"currency"`
	DestinationDigits string             `db:"destination_digits" json:"destination_digits"`
	ResolvedAt        pgtype.Timestamptz `db:"resolved_at" json:"resolved_at"`
}

func (q *Queries) ResolveVoiceRate(ctx context.Context, arg ResolveVoiceRateParams) (VoiceRate, error) {
	row := q.db.QueryRow(ctx, resolveVoiceRate,
		arg.OrganizationID,
		arg.Direction,
		arg.Currency,
		arg.DestinationDigits,
		arg.ResolvedAt,
	)
	var i VoiceRate
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DestinationPrefix,
		&i.Direction,
		&i.Currency,
		&i.RateMicros,
		&i.EffectiveAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
