// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: voice_agents.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createVoiceAgent = `-- name: CreateVoiceAgent :one
INSERT INTO voice_agents (
    organization_id,
    name,
    engine,
    instructions,
    voice,
    language
)
SELECT
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
FROM organizations AS o
WHERE o.id = $1
  AND o.status = 'active'
  AND o.deleted_at IS NULL
RETURNING id, organization_id, name, engine, instructions, voice, language, status, engine_config, created_at, updated_at
`

type CreateVoiceAgentParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	Name           string    `db:"name" json:"name"`
	Engine         string    `db:"engine" json:"engine"`
	Instructions   string    `db:"instructions" json:"instructions"`
	Voice          *string   `db:"voice" json:"voice"`
	Language       *string   `db:"language" json:"language"`
}

func (q *Queries) CreateVoiceAgent(ctx context.Context, arg CreateVoiceAgentParams) (VoiceAgent, error) {
	row := q.db.QueryRow(ctx, createVoiceAgent,
		arg.OrganizationID,
		arg.Name,
		arg.Engine,
		arg.Instructions,
		arg.Voice,
		arg.Language,
	)
	var i VoiceAgent
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Engine,
		&i.Instructions,
		&i.Voice,
		&i.Language,
		&i.Status,
		&i.EngineConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disableVoiceAgent = `-- name: DisableVoiceAgent :exec
UPDATE voice_agents
SET
    status = 'disabled',
    updated_at = NOW()
WHERE id = $1
  AND organization_id = $2
  AND status = 'active'
`

type DisableVoiceAgentParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) DisableVoiceAgent(ctx context.Context, arg DisableVoiceAgentParams) error {
	_, err := q.db.Exec(ctx, disableVoiceAgent, arg.ID, arg.OrganizationID)
	return err
}

const getVoiceAgentByID = `-- name: GetVoiceAgentByID :one
SELECT va.id, va.organization_id, va.name, va.engine, va.instructions, va.voice, va.language, va.status, va.engine_config, va.created_at, va.updated_at
FROM voice_agents AS va
JOIN organizations AS o ON o.id = va.organization_id
WHERE va.id = $1
  AND va.organization_id = $2
  AND va.status = 'active'
  AND o.status = 'active'
  AND o.deleted_at IS NULL
LIMIT 1
`

type GetVoiceAgentByIDParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetVoiceAgentByID(ctx context.Context, arg GetVoiceAgentByIDParams) (VoiceAgent, error) {
	row := q.db.QueryRow(ctx, getVoiceAgentByID, arg.ID, arg.OrganizationID)
	var i VoiceAgent
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Engine,
		&i.Instructions,
		&i.Voice,
		&i.Language,
		&i.Status,
		&i.EngineConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVoiceAgentsByOrganizationID = `-- name: ListVoiceAgentsByOrganizationID :many
SELECT va.id, va.organization_id, va.name, va.engine, va.instructions, va.voice, va.language, va.status, va.engine_config, va.created_at, va.updated_at
FROM voice_agents AS va
JOIN organizations AS o ON o.id = va.organization_id
WHERE va.organization_id = $1
  AND va.status = 'active'
  AND o.status = 'active'
  AND o.deleted_at IS NULL
ORDER BY va.created_at DESC
`

func (q *Queries) ListVoiceAgentsByOrganizationID(ctx context.Context, organizationID uuid.UUID) ([]VoiceAgent, error) {
	rows, err := q.db.Query(ctx, listVoiceAgentsByOrganizationID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoiceAgent{}
	for rows.Next() {
		var i VoiceAgent
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Engine,
			&i.Instructions,
			&i.Voice,
			&i.Language,
			&i.Status,
			&i.EngineConfig,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVoiceAgent = `-- name: UpdateVoiceAgent :one
UPDATE voice_agents
SET
    name = COALESCE($1, name),
    engine = COALESCE($2, engine),
    instructions = COALESCE($3, instructions),
    voice = COALESCE($4, voice),
    language = COALESCE($5, language),
    updated_at = NOW()
WHERE id = $6
  AND organization_id = $7
  AND status = 'active'
RETURNING id, organization_id, name, engine, instructions, voice, language, status, engine_config, created_at, updated_at
`

type UpdateVoiceAgentParams struct {
	Name           *string   `db:"name" json:"name"`
	Engine         *string   `db:"engine" json:"engine"`
	Instructions   *string   `db:"instructions" json:"instructions"`
	Voice          *string   `db:"voice" json:"voice"`
	Language       *string   `db:"language" json:"language"`
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) UpdateVoiceAgent(ctx context.Context, arg UpdateVoiceAgentParams) (VoiceAgent, error) {
	row := q.db.QueryRow(ctx, updateVoiceAgent,
		arg.Name,
		arg.Engine,
		arg.Instructions,
		arg.Voice,
		arg.Language,
		arg.ID,
		arg.OrganizationID,
	)
	var i VoiceAgent
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Engine,
		&i.Instructions,
		&i.Voice,
		&i.Language,
		&i.Status,
		&i.EngineConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
