// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: voice_agent_recovery.sql

package sqlc

import (
	"context"
)

const listCallsForVoiceAgentRecovery = `-- name: ListCallsForVoiceAgentRecovery :many
SELECT c.id, c.organization_id, c.voice_agent_id, c.trunk_id, c.trunk_endpoint_id, c.direction, c.state, c.media_state, c.from_uri, c.to_uri, c.sip_call_id, c.started_at, c.answered_at, c.ended_at, c.hangup_reason, c.created_at, c.updated_at
FROM calls AS c
JOIN organizations AS o ON o.id = c.organization_id
WHERE c.voice_agent_id IS NOT NULL
  AND c.state IN ('answered', 'active')
  AND c.ended_at IS NULL
  AND o.status = 'active'
  AND o.deleted_at IS NULL
ORDER BY c.created_at ASC
`

func (q *Queries) ListCallsForVoiceAgentRecovery(ctx context.Context) ([]Call, error) {
	rows, err := q.db.Query(ctx, listCallsForVoiceAgentRecovery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Call{}
	for rows.Next() {
		var i Call
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.VoiceAgentID,
			&i.TrunkID,
			&i.TrunkEndpointID,
			&i.Direction,
			&i.State,
			&i.MediaState,
			&i.FromUri,
			&i.ToUri,
			&i.SipCallID,
			&i.StartedAt,
			&i.AnsweredAt,
			&i.EndedAt,
			&i.HangupReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
