// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: voice_agent_sessions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeVoiceAgentSession = `-- name: CompleteVoiceAgentSession :one
UPDATE voice_agent_sessions
SET
    state = $1,
    turn_count = $2,
    interruption_count = $3,
    first_response_latency_ms = $4,
    avg_turn_latency_ms = $5,
    ended_at = $6,
    updated_at = NOW()
WHERE id = $7
  AND organization_id = $8
  AND state = 'active'
RETURNING id, organization_id, call_id, voice_agent_id, engine, instructions_snapshot, voice, language, state, turn_count, interruption_count, first_response_latency_ms, avg_turn_latency_ms, started_at, ended_at, created_at, updated_at
`

type CompleteVoiceAgentSessionParams struct {
	State                  string             `db:"state" json:"state"`
	TurnCount              int32              `db:"turn_count" json:"turn_count"`
	InterruptionCount      int32              `db:"interruption_count" json:"interruption_count"`
	FirstResponseLatencyMs *int32             `db:"first_response_latency_ms" json:"first_response_latency_ms"`
	AvgTurnLatencyMs       *int32             `db:"avg_turn_latency_ms" json:"avg_turn_latency_ms"`
	EndedAt                pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	ID                     uuid.UUID          `db:"id" json:"id"`
	OrganizationID         uuid.UUID          `db:"organization_id" json:"organization_id"`
}

func (q *Queries) CompleteVoiceAgentSession(ctx context.Context, arg CompleteVoiceAgentSessionParams) (VoiceAgentSession, error) {
	row := q.db.QueryRow(ctx, completeVoiceAgentSession,
		arg.State,
		arg.TurnCount,
		arg.InterruptionCount,
		arg.FirstResponseLatencyMs,
		arg.AvgTurnLatencyMs,
		arg.EndedAt,
		arg.ID,
		arg.OrganizationID,
	)
	var i VoiceAgentSession
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CallID,
		&i.VoiceAgentID,
		&i.Engine,
		&i.InstructionsSnapshot,
		&i.Voice,
		&i.Language,
		&i.State,
		&i.TurnCount,
		&i.InterruptionCount,
		&i.FirstResponseLatencyMs,
		&i.AvgTurnLatencyMs,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVoiceAgentSession = `-- name: CreateVoiceAgentSession :one
INSERT INTO voice_agent_sessions (
    organization_id,
    call_id,
    voice_agent_id,
    engine,
    instructions_snapshot,
    voice,
    language
)
SELECT
    $1,
    $2,
    agent.id,
    agent.engine,
    agent.instructions,
    agent.voice,
    agent.language
FROM voice_agents AS agent
JOIN calls AS c
  ON c.id = $2
 AND c.organization_id = $1
WHERE agent.id = $3
  AND agent.organization_id = $1
  AND agent.status = 'active'
RETURNING id, organization_id, call_id, voice_agent_id, engine, instructions_snapshot, voice, language, state, turn_count, interruption_count, first_response_latency_ms, avg_turn_latency_ms, started_at, ended_at, created_at, updated_at
`

type CreateVoiceAgentSessionParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	CallID         uuid.UUID `db:"call_id" json:"call_id"`
	VoiceAgentID   uuid.UUID `db:"voice_agent_id" json:"voice_agent_id"`
}

func (q *Queries) CreateVoiceAgentSession(ctx context.Context, arg CreateVoiceAgentSessionParams) (VoiceAgentSession, error) {
	row := q.db.QueryRow(ctx, createVoiceAgentSession, arg.OrganizationID, arg.CallID, arg.VoiceAgentID)
	var i VoiceAgentSession
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CallID,
		&i.VoiceAgentID,
		&i.Engine,
		&i.InstructionsSnapshot,
		&i.Voice,
		&i.Language,
		&i.State,
		&i.TurnCount,
		&i.InterruptionCount,
		&i.FirstResponseLatencyMs,
		&i.AvgTurnLatencyMs,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveVoiceAgentSessionByCallID = `-- name: GetActiveVoiceAgentSessionByCallID :one
SELECT id, organization_id, call_id, voice_agent_id, engine, instructions_snapshot, voice, language, state, turn_count, interruption_count, first_response_latency_ms, avg_turn_latency_ms, started_at, ended_at, created_at, updated_at
FROM voice_agent_sessions
WHERE organization_id = $1
  AND call_id = $2
  AND state = 'active'
LIMIT 1
`

type GetActiveVoiceAgentSessionByCallIDParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	CallID         uuid.UUID `db:"call_id" json:"call_id"`
}

func (q *Queries) GetActiveVoiceAgentSessionByCallID(ctx context.Context, arg GetActiveVoiceAgentSessionByCallIDParams) (VoiceAgentSession, error) {
	row := q.db.QueryRow(ctx, getActiveVoiceAgentSessionByCallID, arg.OrganizationID, arg.CallID)
	var i VoiceAgentSession
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CallID,
		&i.VoiceAgentID,
		&i.Engine,
		&i.InstructionsSnapshot,
		&i.Voice,
		&i.Language,
		&i.State,
		&i.TurnCount,
		&i.InterruptionCount,
		&i.FirstResponseLatencyMs,
		&i.AvgTurnLatencyMs,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVoiceAgentSessionByID = `-- name: GetVoiceAgentSessionByID :one
SELECT id, organization_id, call_id, voice_agent_id, engine, instructions_snapshot, voice, language, state, turn_count, interruption_count, first_response_latency_ms, avg_turn_latency_ms, started_at, ended_at, created_at, updated_at
FROM voice_agent_sessions
WHERE id = $1
  AND organization_id = $2
LIMIT 1
`

type GetVoiceAgentSessionByIDParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetVoiceAgentSessionByID(ctx context.Context, arg GetVoiceAgentSessionByIDParams) (VoiceAgentSession, error) {
	row := q.db.QueryRow(ctx, getVoiceAgentSessionByID, arg.ID, arg.OrganizationID)
	var i VoiceAgentSession
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CallID,
		&i.VoiceAgentID,
		&i.Engine,
		&i.InstructionsSnapshot,
		&i.Voice,
		&i.Language,
		&i.State,
		&i.TurnCount,
		&i.InterruptionCount,
		&i.FirstResponseLatencyMs,
		&i.AvgTurnLatencyMs,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
