// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: voice_agent_runtime.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeVoiceAgentSession = `-- name: CompleteVoiceAgentSession :one
UPDATE voice_agent_sessions
SET
    state = $1,
    turn_count = $2,
    interruption_count = $3,
    first_response_latency_ms = $4,
    avg_turn_latency_ms = $5,
    ended_at = $6,
    updated_at = NOW()
WHERE id = $7
  AND organization_id = $8
  AND state = 'active'
RETURNING id, organization_id, call_id, voice_agent_id, engine, instructions_snapshot, voice, language, state, turn_count, interruption_count, first_response_latency_ms, avg_turn_latency_ms, started_at, ended_at, created_at, updated_at
`

type CompleteVoiceAgentSessionParams struct {
	State                  string             `db:"state" json:"state"`
	TurnCount              int32              `db:"turn_count" json:"turn_count"`
	InterruptionCount      int32              `db:"interruption_count" json:"interruption_count"`
	FirstResponseLatencyMs *int32             `db:"first_response_latency_ms" json:"first_response_latency_ms"`
	AvgTurnLatencyMs       *int32             `db:"avg_turn_latency_ms" json:"avg_turn_latency_ms"`
	EndedAt                pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	ID                     uuid.UUID          `db:"id" json:"id"`
	OrganizationID         uuid.UUID          `db:"organization_id" json:"organization_id"`
}

func (q *Queries) CompleteVoiceAgentSession(ctx context.Context, arg CompleteVoiceAgentSessionParams) (VoiceAgentSession, error) {
	row := q.db.QueryRow(ctx, completeVoiceAgentSession,
		arg.State,
		arg.TurnCount,
		arg.InterruptionCount,
		arg.FirstResponseLatencyMs,
		arg.AvgTurnLatencyMs,
		arg.EndedAt,
		arg.ID,
		arg.OrganizationID,
	)
	var i VoiceAgentSession
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CallID,
		&i.VoiceAgentID,
		&i.Engine,
		&i.InstructionsSnapshot,
		&i.Voice,
		&i.Language,
		&i.State,
		&i.TurnCount,
		&i.InterruptionCount,
		&i.FirstResponseLatencyMs,
		&i.AvgTurnLatencyMs,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVoiceAgentSession = `-- name: CreateVoiceAgentSession :one
INSERT INTO voice_agent_sessions (
    organization_id,
    call_id,
    voice_agent_id,
    engine,
    instructions_snapshot,
    voice,
    language
)
SELECT
    $1,
    $2,
    agent.id,
    agent.engine,
    agent.instructions,
    agent.voice,
    agent.language
FROM voice_agents AS agent
JOIN calls AS c
  ON c.id = $2
 AND c.organization_id = $1
WHERE agent.id = $3
  AND agent.organization_id = $1
  AND agent.status = 'active'
RETURNING id, organization_id, call_id, voice_agent_id, engine, instructions_snapshot, voice, language, state, turn_count, interruption_count, first_response_latency_ms, avg_turn_latency_ms, started_at, ended_at, created_at, updated_at
`

type CreateVoiceAgentSessionParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	CallID         uuid.UUID `db:"call_id" json:"call_id"`
	VoiceAgentID   uuid.UUID `db:"voice_agent_id" json:"voice_agent_id"`
}

func (q *Queries) CreateVoiceAgentSession(ctx context.Context, arg CreateVoiceAgentSessionParams) (VoiceAgentSession, error) {
	row := q.db.QueryRow(ctx, createVoiceAgentSession, arg.OrganizationID, arg.CallID, arg.VoiceAgentID)
	var i VoiceAgentSession
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CallID,
		&i.VoiceAgentID,
		&i.Engine,
		&i.InstructionsSnapshot,
		&i.Voice,
		&i.Language,
		&i.State,
		&i.TurnCount,
		&i.InterruptionCount,
		&i.FirstResponseLatencyMs,
		&i.AvgTurnLatencyMs,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVoiceAgentTool = `-- name: CreateVoiceAgentTool :one
INSERT INTO voice_agent_tools (
    organization_id,
    voice_agent_id,
    type,
    name,
    description,
    parameters,
    endpoint_url,
    timeout_ms,
    enabled
)
SELECT
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
FROM voice_agents AS agent
WHERE agent.id = $2
  AND agent.organization_id = $1
  AND agent.status = 'active'
RETURNING id, organization_id, voice_agent_id, type, name, description, parameters, endpoint_url, timeout_ms, enabled, created_at, updated_at
`

type CreateVoiceAgentToolParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	VoiceAgentID   uuid.UUID `db:"voice_agent_id" json:"voice_agent_id"`
	Type           string    `db:"type" json:"type"`
	Name           string    `db:"name" json:"name"`
	Description    string    `db:"description" json:"description"`
	Parameters     []byte    `db:"parameters" json:"parameters"`
	EndpointUrl    *string   `db:"endpoint_url" json:"endpoint_url"`
	TimeoutMs      int32     `db:"timeout_ms" json:"timeout_ms"`
	Enabled        bool      `db:"enabled" json:"enabled"`
}

func (q *Queries) CreateVoiceAgentTool(ctx context.Context, arg CreateVoiceAgentToolParams) (VoiceAgentTool, error) {
	row := q.db.QueryRow(ctx, createVoiceAgentTool,
		arg.OrganizationID,
		arg.VoiceAgentID,
		arg.Type,
		arg.Name,
		arg.Description,
		arg.Parameters,
		arg.EndpointUrl,
		arg.TimeoutMs,
		arg.Enabled,
	)
	var i VoiceAgentTool
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.VoiceAgentID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.Parameters,
		&i.EndpointUrl,
		&i.TimeoutMs,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVoiceAgentTurn = `-- name: CreateVoiceAgentTurn :one
INSERT INTO voice_agent_turns (
    organization_id,
    session_id,
    sequence,
    role,
    content,
    provider_id,
    tool_name,
    tool_call_id,
    metadata,
    speech_started_at,
    speech_ended_at,
    stt_latency_ms,
    llm_ttft_ms,
    tts_ttfb_ms,
    turn_latency_ms
)
SELECT
    $1,
    session.id,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14
FROM voice_agent_sessions AS session
WHERE session.id = $15
  AND session.organization_id = $1
RETURNING id, organization_id, session_id, sequence, role, content, provider_id, tool_name, tool_call_id, metadata, speech_started_at, speech_ended_at, stt_latency_ms, llm_ttft_ms, tts_ttfb_ms, turn_latency_ms, created_at
`

type CreateVoiceAgentTurnParams struct {
	OrganizationID  uuid.UUID          `db:"organization_id" json:"organization_id"`
	Sequence        int32              `db:"sequence" json:"sequence"`
	Role            string             `db:"role" json:"role"`
	Content         string             `db:"content" json:"content"`
	ProviderID      *string            `db:"provider_id" json:"provider_id"`
	ToolName        *string            `db:"tool_name" json:"tool_name"`
	ToolCallID      *string            `db:"tool_call_id" json:"tool_call_id"`
	Metadata        []byte             `db:"metadata" json:"metadata"`
	SpeechStartedAt pgtype.Timestamptz `db:"speech_started_at" json:"speech_started_at"`
	SpeechEndedAt   pgtype.Timestamptz `db:"speech_ended_at" json:"speech_ended_at"`
	SttLatencyMs    *int32             `db:"stt_latency_ms" json:"stt_latency_ms"`
	LlmTtftMs       *int32             `db:"llm_ttft_ms" json:"llm_ttft_ms"`
	TtsTtfbMs       *int32             `db:"tts_ttfb_ms" json:"tts_ttfb_ms"`
	TurnLatencyMs   *int32             `db:"turn_latency_ms" json:"turn_latency_ms"`
	SessionID       uuid.UUID          `db:"session_id" json:"session_id"`
}

func (q *Queries) CreateVoiceAgentTurn(ctx context.Context, arg CreateVoiceAgentTurnParams) (VoiceAgentTurn, error) {
	row := q.db.QueryRow(ctx, createVoiceAgentTurn,
		arg.OrganizationID,
		arg.Sequence,
		arg.Role,
		arg.Content,
		arg.ProviderID,
		arg.ToolName,
		arg.ToolCallID,
		arg.Metadata,
		arg.SpeechStartedAt,
		arg.SpeechEndedAt,
		arg.SttLatencyMs,
		arg.LlmTtftMs,
		arg.TtsTtfbMs,
		arg.TurnLatencyMs,
		arg.SessionID,
	)
	var i VoiceAgentTurn
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SessionID,
		&i.Sequence,
		&i.Role,
		&i.Content,
		&i.ProviderID,
		&i.ToolName,
		&i.ToolCallID,
		&i.Metadata,
		&i.SpeechStartedAt,
		&i.SpeechEndedAt,
		&i.SttLatencyMs,
		&i.LlmTtftMs,
		&i.TtsTtfbMs,
		&i.TurnLatencyMs,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVoiceAgentTool = `-- name: DeleteVoiceAgentTool :exec
DELETE FROM voice_agent_tools
WHERE id = $1
  AND organization_id = $2
  AND voice_agent_id = $3
`

type DeleteVoiceAgentToolParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	VoiceAgentID   uuid.UUID `db:"voice_agent_id" json:"voice_agent_id"`
}

func (q *Queries) DeleteVoiceAgentTool(ctx context.Context, arg DeleteVoiceAgentToolParams) error {
	_, err := q.db.Exec(ctx, deleteVoiceAgentTool, arg.ID, arg.OrganizationID, arg.VoiceAgentID)
	return err
}

const getActiveVoiceAgentSessionByCallID = `-- name: GetActiveVoiceAgentSessionByCallID :one
SELECT id, organization_id, call_id, voice_agent_id, engine, instructions_snapshot, voice, language, state, turn_count, interruption_count, first_response_latency_ms, avg_turn_latency_ms, started_at, ended_at, created_at, updated_at
FROM voice_agent_sessions
WHERE organization_id = $1
  AND call_id = $2
  AND state = 'active'
LIMIT 1
`

type GetActiveVoiceAgentSessionByCallIDParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	CallID         uuid.UUID `db:"call_id" json:"call_id"`
}

func (q *Queries) GetActiveVoiceAgentSessionByCallID(ctx context.Context, arg GetActiveVoiceAgentSessionByCallIDParams) (VoiceAgentSession, error) {
	row := q.db.QueryRow(ctx, getActiveVoiceAgentSessionByCallID, arg.OrganizationID, arg.CallID)
	var i VoiceAgentSession
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CallID,
		&i.VoiceAgentID,
		&i.Engine,
		&i.InstructionsSnapshot,
		&i.Voice,
		&i.Language,
		&i.State,
		&i.TurnCount,
		&i.InterruptionCount,
		&i.FirstResponseLatencyMs,
		&i.AvgTurnLatencyMs,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVoiceAgentSessionByID = `-- name: GetVoiceAgentSessionByID :one
SELECT id, organization_id, call_id, voice_agent_id, engine, instructions_snapshot, voice, language, state, turn_count, interruption_count, first_response_latency_ms, avg_turn_latency_ms, started_at, ended_at, created_at, updated_at
FROM voice_agent_sessions
WHERE id = $1
  AND organization_id = $2
LIMIT 1
`

type GetVoiceAgentSessionByIDParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetVoiceAgentSessionByID(ctx context.Context, arg GetVoiceAgentSessionByIDParams) (VoiceAgentSession, error) {
	row := q.db.QueryRow(ctx, getVoiceAgentSessionByID, arg.ID, arg.OrganizationID)
	var i VoiceAgentSession
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CallID,
		&i.VoiceAgentID,
		&i.Engine,
		&i.InstructionsSnapshot,
		&i.Voice,
		&i.Language,
		&i.State,
		&i.TurnCount,
		&i.InterruptionCount,
		&i.FirstResponseLatencyMs,
		&i.AvgTurnLatencyMs,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVoiceAgentToolByID = `-- name: GetVoiceAgentToolByID :one
SELECT tool.id, tool.organization_id, tool.voice_agent_id, tool.type, tool.name, tool.description, tool.parameters, tool.endpoint_url, tool.timeout_ms, tool.enabled, tool.created_at, tool.updated_at
FROM voice_agent_tools AS tool
JOIN voice_agents AS agent ON agent.id = tool.voice_agent_id
WHERE tool.id = $1
  AND tool.organization_id = $2
  AND tool.voice_agent_id = $3
  AND agent.status = 'active'
LIMIT 1
`

type GetVoiceAgentToolByIDParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	VoiceAgentID   uuid.UUID `db:"voice_agent_id" json:"voice_agent_id"`
}

func (q *Queries) GetVoiceAgentToolByID(ctx context.Context, arg GetVoiceAgentToolByIDParams) (VoiceAgentTool, error) {
	row := q.db.QueryRow(ctx, getVoiceAgentToolByID, arg.ID, arg.OrganizationID, arg.VoiceAgentID)
	var i VoiceAgentTool
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.VoiceAgentID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.Parameters,
		&i.EndpointUrl,
		&i.TimeoutMs,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVoiceAgentToolsByAgentID = `-- name: ListVoiceAgentToolsByAgentID :many
SELECT tool.id, tool.organization_id, tool.voice_agent_id, tool.type, tool.name, tool.description, tool.parameters, tool.endpoint_url, tool.timeout_ms, tool.enabled, tool.created_at, tool.updated_at
FROM voice_agent_tools AS tool
JOIN voice_agents AS agent ON agent.id = tool.voice_agent_id
WHERE tool.organization_id = $1
  AND tool.voice_agent_id = $2
  AND agent.status = 'active'
ORDER BY tool.created_at ASC
`

type ListVoiceAgentToolsByAgentIDParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	VoiceAgentID   uuid.UUID `db:"voice_agent_id" json:"voice_agent_id"`
}

func (q *Queries) ListVoiceAgentToolsByAgentID(ctx context.Context, arg ListVoiceAgentToolsByAgentIDParams) ([]VoiceAgentTool, error) {
	rows, err := q.db.Query(ctx, listVoiceAgentToolsByAgentID, arg.OrganizationID, arg.VoiceAgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoiceAgentTool{}
	for rows.Next() {
		var i VoiceAgentTool
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.VoiceAgentID,
			&i.Type,
			&i.Name,
			&i.Description,
			&i.Parameters,
			&i.EndpointUrl,
			&i.TimeoutMs,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoiceAgentTurnsBySessionID = `-- name: ListVoiceAgentTurnsBySessionID :many
SELECT id, organization_id, session_id, sequence, role, content, provider_id, tool_name, tool_call_id, metadata, speech_started_at, speech_ended_at, stt_latency_ms, llm_ttft_ms, tts_ttfb_ms, turn_latency_ms, created_at
FROM voice_agent_turns
WHERE organization_id = $1
  AND session_id = $2
ORDER BY sequence ASC
`

type ListVoiceAgentTurnsBySessionIDParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	SessionID      uuid.UUID `db:"session_id" json:"session_id"`
}

func (q *Queries) ListVoiceAgentTurnsBySessionID(ctx context.Context, arg ListVoiceAgentTurnsBySessionIDParams) ([]VoiceAgentTurn, error) {
	rows, err := q.db.Query(ctx, listVoiceAgentTurnsBySessionID, arg.OrganizationID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoiceAgentTurn{}
	for rows.Next() {
		var i VoiceAgentTurn
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SessionID,
			&i.Sequence,
			&i.Role,
			&i.Content,
			&i.ProviderID,
			&i.ToolName,
			&i.ToolCallID,
			&i.Metadata,
			&i.SpeechStartedAt,
			&i.SpeechEndedAt,
			&i.SttLatencyMs,
			&i.LlmTtftMs,
			&i.TtsTtfbMs,
			&i.TurnLatencyMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVoiceAgentTool = `-- name: UpdateVoiceAgentTool :one
UPDATE voice_agent_tools
SET
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    parameters = COALESCE($3, parameters),
    endpoint_url = COALESCE($4, endpoint_url),
    timeout_ms = COALESCE($5, timeout_ms),
    enabled = COALESCE($6, enabled),
    updated_at = NOW()
WHERE id = $7
  AND organization_id = $8
  AND voice_agent_id = $9
RETURNING id, organization_id, voice_agent_id, type, name, description, parameters, endpoint_url, timeout_ms, enabled, created_at, updated_at
`

type UpdateVoiceAgentToolParams struct {
	Name           *string   `db:"name" json:"name"`
	Description    *string   `db:"description" json:"description"`
	Parameters     []byte    `db:"parameters" json:"parameters"`
	EndpointUrl    *string   `db:"endpoint_url" json:"endpoint_url"`
	TimeoutMs      *int32    `db:"timeout_ms" json:"timeout_ms"`
	Enabled        *bool     `db:"enabled" json:"enabled"`
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	VoiceAgentID   uuid.UUID `db:"voice_agent_id" json:"voice_agent_id"`
}

func (q *Queries) UpdateVoiceAgentTool(ctx context.Context, arg UpdateVoiceAgentToolParams) (VoiceAgentTool, error) {
	row := q.db.QueryRow(ctx, updateVoiceAgentTool,
		arg.Name,
		arg.Description,
		arg.Parameters,
		arg.EndpointUrl,
		arg.TimeoutMs,
		arg.Enabled,
		arg.ID,
		arg.OrganizationID,
		arg.VoiceAgentID,
	)
	var i VoiceAgentTool
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.VoiceAgentID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.Parameters,
		&i.EndpointUrl,
		&i.TimeoutMs,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
