// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallets.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateWallet = `-- name: ActivateWallet :one
UPDATE wallets AS w
SET
    status = 'active',
    updated_at = NOW()
WHERE w.organization_id = $1
  AND w.status = 'frozen'
  AND EXISTS (
      SELECT 1
      FROM organizations AS o
      WHERE o.id = w.organization_id
        AND o.status = 'active'
        AND o.deleted_at IS NULL
  )
RETURNING w.id, w.organization_id, w.currency, w.status, w.balance_micros, w.created_at, w.updated_at
`

func (q *Queries) ActivateWallet(ctx context.Context, organizationID uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, activateWallet, organizationID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Currency,
		&i.Status,
		&i.BalanceMicros,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const applyWalletBalance = `-- name: ApplyWalletBalance :one
UPDATE wallets AS w
SET
    balance_micros = w.balance_micros + $1,
    updated_at = NOW()
WHERE w.organization_id = $2
  AND w.status = 'active'
  AND w.balance_micros + $1 >= 0
  AND EXISTS (
      SELECT 1
      FROM organizations AS o
      WHERE o.id = w.organization_id
        AND o.status = 'active'
        AND o.deleted_at IS NULL
  )
RETURNING w.id, w.organization_id, w.currency, w.status, w.balance_micros, w.created_at, w.updated_at
`

type ApplyWalletBalanceParams struct {
	DeltaMicros    int64     `db:"delta_micros" json:"delta_micros"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) ApplyWalletBalance(ctx context.Context, arg ApplyWalletBalanceParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, applyWalletBalance, arg.DeltaMicros, arg.OrganizationID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Currency,
		&i.Status,
		&i.BalanceMicros,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const closeWallet = `-- name: CloseWallet :one
UPDATE wallets
SET
    status = 'closed',
    updated_at = NOW()
WHERE organization_id = $1
  AND status IN ('active', 'frozen')
  AND balance_micros = 0
RETURNING id, organization_id, currency, status, balance_micros, created_at, updated_at
`

func (q *Queries) CloseWallet(ctx context.Context, organizationID uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, closeWallet, organizationID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Currency,
		&i.Status,
		&i.BalanceMicros,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (
    organization_id
)
SELECT
    o.id
FROM organizations AS o
WHERE o.id = $1
  AND o.status = 'active'
  AND o.deleted_at IS NULL
ON CONFLICT (organization_id) DO NOTHING
RETURNING id, organization_id, currency, status, balance_micros, created_at, updated_at
`

func (q *Queries) CreateWallet(ctx context.Context, organizationID uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet, organizationID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Currency,
		&i.Status,
		&i.BalanceMicros,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWalletLedgerEntry = `-- name: CreateWalletLedgerEntry :one
INSERT INTO wallet_ledger_entries (
    wallet_id,
    organization_id,
    operation_id,
    direction,
    reason,
    amount_micros,
    balance_after_micros,
    reference_type,
    reference_id,
    occurred_at
)
SELECT
    w.id,
    w.organization_id,
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
FROM wallets AS w
JOIN organizations AS o
  ON o.id = w.organization_id
WHERE w.organization_id = $9
  AND w.status = 'active'
  AND w.balance_micros = $5
  AND o.status = 'active'
  AND o.deleted_at IS NULL
RETURNING id, wallet_id, organization_id, operation_id, direction, reason, amount_micros, balance_after_micros, reference_type, reference_id, occurred_at, created_at
`

type CreateWalletLedgerEntryParams struct {
	OperationID        uuid.UUID          `db:"operation_id" json:"operation_id"`
	Direction          string             `db:"direction" json:"direction"`
	Reason             string             `db:"reason" json:"reason"`
	AmountMicros       int64              `db:"amount_micros" json:"amount_micros"`
	BalanceAfterMicros int64              `db:"balance_after_micros" json:"balance_after_micros"`
	ReferenceType      *string            `db:"reference_type" json:"reference_type"`
	ReferenceID        *uuid.UUID         `db:"reference_id" json:"reference_id"`
	OccurredAt         pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	OrganizationID     uuid.UUID          `db:"organization_id" json:"organization_id"`
}

func (q *Queries) CreateWalletLedgerEntry(ctx context.Context, arg CreateWalletLedgerEntryParams) (WalletLedgerEntry, error) {
	row := q.db.QueryRow(ctx, createWalletLedgerEntry,
		arg.OperationID,
		arg.Direction,
		arg.Reason,
		arg.AmountMicros,
		arg.BalanceAfterMicros,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.OccurredAt,
		arg.OrganizationID,
	)
	var i WalletLedgerEntry
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.OrganizationID,
		&i.OperationID,
		&i.Direction,
		&i.Reason,
		&i.AmountMicros,
		&i.BalanceAfterMicros,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const freezeWallet = `-- name: FreezeWallet :one
UPDATE wallets
SET
    status = 'frozen',
    updated_at = NOW()
WHERE organization_id = $1
  AND status = 'active'
RETURNING id, organization_id, currency, status, balance_micros, created_at, updated_at
`

func (q *Queries) FreezeWallet(ctx context.Context, organizationID uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, freezeWallet, organizationID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Currency,
		&i.Status,
		&i.BalanceMicros,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveWalletByOrganization = `-- name: GetActiveWalletByOrganization :one
SELECT w.id, w.organization_id, w.currency, w.status, w.balance_micros, w.created_at, w.updated_at
FROM wallets AS w
JOIN organizations AS o
  ON o.id = w.organization_id
WHERE w.organization_id = $1
  AND w.status = 'active'
  AND o.status = 'active'
  AND o.deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetActiveWalletByOrganization(ctx context.Context, organizationID uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, getActiveWalletByOrganization, organizationID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Currency,
		&i.Status,
		&i.BalanceMicros,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletLedgerEntryByOperationID = `-- name: GetWalletLedgerEntryByOperationID :one
SELECT id, wallet_id, organization_id, operation_id, direction, reason, amount_micros, balance_after_micros, reference_type, reference_id, occurred_at, created_at
FROM wallet_ledger_entries
WHERE organization_id = $1
  AND operation_id = $2
LIMIT 1
`

type GetWalletLedgerEntryByOperationIDParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	OperationID    uuid.UUID `db:"operation_id" json:"operation_id"`
}

func (q *Queries) GetWalletLedgerEntryByOperationID(ctx context.Context, arg GetWalletLedgerEntryByOperationIDParams) (WalletLedgerEntry, error) {
	row := q.db.QueryRow(ctx, getWalletLedgerEntryByOperationID, arg.OrganizationID, arg.OperationID)
	var i WalletLedgerEntry
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.OrganizationID,
		&i.OperationID,
		&i.Direction,
		&i.Reason,
		&i.AmountMicros,
		&i.BalanceAfterMicros,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listWalletLedgerEntries = `-- name: ListWalletLedgerEntries :many
SELECT id, wallet_id, organization_id, operation_id, direction, reason, amount_micros, balance_after_micros, reference_type, reference_id, occurred_at, created_at
FROM wallet_ledger_entries
WHERE organization_id = $1
ORDER BY occurred_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListWalletLedgerEntriesParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	OffsetCount    int32     `db:"offset_count" json:"offset_count"`
	LimitCount     int32     `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListWalletLedgerEntries(ctx context.Context, arg ListWalletLedgerEntriesParams) ([]WalletLedgerEntry, error) {
	rows, err := q.db.Query(ctx, listWalletLedgerEntries, arg.OrganizationID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WalletLedgerEntry{}
	for rows.Next() {
		var i WalletLedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.OrganizationID,
			&i.OperationID,
			&i.Direction,
			&i.Reason,
			&i.AmountMicros,
			&i.BalanceAfterMicros,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveWallet = `-- name: LockActiveWallet :one
SELECT w.id, w.organization_id, w.currency, w.status, w.balance_micros, w.created_at, w.updated_at
FROM wallets AS w
JOIN organizations AS o
  ON o.id = w.organization_id
WHERE w.organization_id = $1
  AND w.status = 'active'
  AND o.status = 'active'
  AND o.deleted_at IS NULL
FOR UPDATE OF w
`

func (q *Queries) LockActiveWallet(ctx context.Context, organizationID uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, lockActiveWallet, organizationID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Currency,
		&i.Status,
		&i.BalanceMicros,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
