// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wholesale_charges.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWholesaleCharge = `-- name: CreateWholesaleCharge :one
INSERT INTO wholesale_charges (
    provider_cdr_id,
    currency,
    rate_micros,
    billable_seconds,
    amount_micros,
    rated_at
)
SELECT
    cdr.id,
    $1,
    $2,
    $3,
    $4,
    $5
FROM provider_cdrs AS cdr
WHERE cdr.id = $6
  AND cdr.billable_seconds = $3
ON CONFLICT (provider_cdr_id) DO NOTHING
RETURNING id, provider_cdr_id, currency, rate_micros, billable_seconds, amount_micros, rated_at, created_at
`

type CreateWholesaleChargeParams struct {
	Currency        string             `db:"currency" json:"currency"`
	RateMicros      int64              `db:"rate_micros" json:"rate_micros"`
	BillableSeconds int64              `db:"billable_seconds" json:"billable_seconds"`
	AmountMicros    int64              `db:"amount_micros" json:"amount_micros"`
	RatedAt         pgtype.Timestamptz `db:"rated_at" json:"rated_at"`
	ProviderCdrID   uuid.UUID          `db:"provider_cdr_id" json:"provider_cdr_id"`
}

func (q *Queries) CreateWholesaleCharge(ctx context.Context, arg CreateWholesaleChargeParams) (WholesaleCharge, error) {
	row := q.db.QueryRow(ctx, createWholesaleCharge,
		arg.Currency,
		arg.RateMicros,
		arg.BillableSeconds,
		arg.AmountMicros,
		arg.RatedAt,
		arg.ProviderCdrID,
	)
	var i WholesaleCharge
	err := row.Scan(
		&i.ID,
		&i.ProviderCdrID,
		&i.Currency,
		&i.RateMicros,
		&i.BillableSeconds,
		&i.AmountMicros,
		&i.RatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWholesaleChargeByID = `-- name: GetWholesaleChargeByID :one
SELECT id, provider_cdr_id, currency, rate_micros, billable_seconds, amount_micros, rated_at, created_at
FROM wholesale_charges
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetWholesaleChargeByID(ctx context.Context, id uuid.UUID) (WholesaleCharge, error) {
	row := q.db.QueryRow(ctx, getWholesaleChargeByID, id)
	var i WholesaleCharge
	err := row.Scan(
		&i.ID,
		&i.ProviderCdrID,
		&i.Currency,
		&i.RateMicros,
		&i.BillableSeconds,
		&i.AmountMicros,
		&i.RatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWholesaleChargeByProviderCDR = `-- name: GetWholesaleChargeByProviderCDR :one
SELECT id, provider_cdr_id, currency, rate_micros, billable_seconds, amount_micros, rated_at, created_at
FROM wholesale_charges
WHERE provider_cdr_id = $1
LIMIT 1
`

func (q *Queries) GetWholesaleChargeByProviderCDR(ctx context.Context, providerCdrID uuid.UUID) (WholesaleCharge, error) {
	row := q.db.QueryRow(ctx, getWholesaleChargeByProviderCDR, providerCdrID)
	var i WholesaleCharge
	err := row.Scan(
		&i.ID,
		&i.ProviderCdrID,
		&i.Currency,
		&i.RateMicros,
		&i.BillableSeconds,
		&i.AmountMicros,
		&i.RatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listWholesaleChargesByCall = `-- name: ListWholesaleChargesByCall :many
SELECT wc.id, wc.provider_cdr_id, wc.currency, wc.rate_micros, wc.billable_seconds, wc.amount_micros, wc.rated_at, wc.created_at
FROM wholesale_charges AS wc
JOIN provider_cdrs AS cdr
  ON cdr.id = wc.provider_cdr_id
WHERE cdr.call_id = $1
ORDER BY wc.rated_at ASC, wc.id ASC
`

func (q *Queries) ListWholesaleChargesByCall(ctx context.Context, callID uuid.UUID) ([]WholesaleCharge, error) {
	rows, err := q.db.Query(ctx, listWholesaleChargesByCall, callID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WholesaleCharge{}
	for rows.Next() {
		var i WholesaleCharge
		if err := rows.Scan(
			&i.ID,
			&i.ProviderCdrID,
			&i.Currency,
			&i.RateMicros,
			&i.BillableSeconds,
			&i.AmountMicros,
			&i.RatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
